/* AUTO-GENERATED FILE. DO NOT EDIT. */
/* Source: config/knobs.json */
/* Generator: tools/gen_knobs.py */

#ifndef KNOBS_AUTOGEN_H
#define KNOBS_AUTOGEN_H

#define KNOB_INPUT_START_LONG_PRESS_MS           (1000)
#define KNOB_INPUT_START_SHIP_IMMINENT_MS        (11000)
#define KNOB_INPUT_START_SHIP_PREP_MS            (6000)
#define KNOB_INPUT_START_SHIP_WARN_MS            (9000)
#define KNOB_INPUT_START_STABLE_SAMPLES          (2)
#define KNOB_POWER_BATTERY_CRITICAL_SHIP_MV      (3300)
#define KNOB_POWER_BATTERY_MONITOR_PERIOD_MS     (1000)
#define KNOB_POWER_BATTERY_RESTART_ALLOW_MV      (3600)
#define KNOB_POWER_BATTERY_WARNING_MV            (3500)
#define KNOB_POWER_BOOT_LOW_BATTERY_SHIP_ENABLE  (0)
#define KNOB_POWER_CHARGER_THERMISTOR_CONTROL    (128)
#define KNOB_POWER_CRITICAL_SOFTWARE_SHIP_ENABLE (0)
#define KNOB_POWER_START_SOFTWARE_SHIP_ENABLE    (0)

#endif /* KNOBS_AUTOGEN_H */
