/* AUTO-GENERATED FILE. DO NOT EDIT. */
/* Source: config/knobs.json */
/* Generator: tools/gen_knobs.py */

#ifndef KNOBS_AUTOGEN_H
#define KNOBS_AUTOGEN_H

#define KNOB_COMM_BLE_BOOT_DRAIN_MS                        (200)
#define KNOB_COMM_BLE_BOOT_WAIT_MS                         (750)
#define KNOB_COMM_BLE_RESET_ASSERT_MS                      (20)
#define KNOB_COMM_BLE_RX_BUFFER_BYTES                      (128)
#define KNOB_COMM_BLE_RX_BYTE_TIMEOUT_MS                   (10)
#define KNOB_COMM_BLE_RX_QUIET_MS                          (50)
#define KNOB_COMM_BLE_RX_WINDOW_MS                         (1000)
#define KNOB_COMM_BLE_STOP_SETTLE_MS                       (1100)
#define KNOB_COMM_BLE_TX_TIMEOUT_MS                        (250)
#define KNOB_COMM_BLE_WAKE_SETTLE_MS                       (1100)
#define KNOB_DEBUG_SWO_LIFECYCLE_ENABLE                    (1)
#define KNOB_DEBUG_TRACEX_BUFFER_BYTES                     (32768)
#define KNOB_DEBUG_TRACEX_ENABLE                           (1)
#define KNOB_DEBUG_TRACEX_REGISTRY_ENTRIES                 (64)
#define KNOB_DEBUG_TRACEX_USER_EVENTS_ENABLE               (1)
#define KNOB_DISPLAY_CURSOR_BLINK_PERIOD_MS                (250)
#define KNOB_INPUT_BTN_DEBOUNCE_PRESS_MS                   (20)
#define KNOB_INPUT_BTN_DEBOUNCE_RELEASE_MS                 (20)
#define KNOB_INPUT_BTN_LONG_PRESS_MS                       (1000)
#define KNOB_INPUT_BTN_REPEAT_PERIOD_MS                    (150)
#define KNOB_INPUT_BTN_REPEAT_START_MS                     (500)
#define KNOB_INPUT_BTN_STUCK_MS                            (30000)
#define KNOB_INPUT_CHORD_WINDOW_MS                         (80)
#define KNOB_INPUT_JOYSTICK_AWAKE_POLL_PERIOD_MS           (50)
#define KNOB_INPUT_JOYSTICK_CAL_CARDINAL_MS                (700)
#define KNOB_INPUT_JOYSTICK_CAL_DEADZONE_PAD_PER_MILLE     (40)
#define KNOB_INPUT_JOYSTICK_CAL_MIN_CARDINAL_SPAN_COUNTS   (4000)
#define KNOB_INPUT_JOYSTICK_CAL_NEUTRAL_MS                 (1200)
#define KNOB_INPUT_JOYSTICK_CAL_PROGRESS_PERIOD_MS         (100)
#define KNOB_INPUT_JOYSTICK_CAL_REVIEW_PERIOD_MS           (50)
#define KNOB_INPUT_JOYSTICK_CAL_SAMPLE_PERIOD_MS           (20)
#define KNOB_INPUT_JOYSTICK_CAL_SWEEP_COVERAGE_PER_MILLE   (600)
#define KNOB_INPUT_JOYSTICK_CAL_SWEEP_MS                   (2500)
#define KNOB_INPUT_JOYSTICK_DIRECTION_ENTER_PER_MILLE      (450)
#define KNOB_INPUT_JOYSTICK_DIRECTION_RELEASE_PER_MILLE    (300)
#define KNOB_INPUT_JOYSTICK_DOMINANCE_HYSTERESIS_PER_MILLE (100)
#define KNOB_INPUT_JOYSTICK_WAKE_FIELD_HYSTERESIS_CODE     (7)
#define KNOB_INPUT_JOYSTICK_WAKE_FIELD_THRESHOLD_CODE      (48)
#define KNOB_INPUT_JOYSTICK_WAKE_SLEEP_PERIOD_MS           (20)
#define KNOB_INPUT_JOYSTICK_XYZ_CAPTURE_PERIOD_MS          (10)
#define KNOB_INPUT_JOYSTICK_XYZ_CAPTURE_SAMPLES            (512)
#define KNOB_INPUT_JOYSTICK_XYZ_CAPTURE_TIMEOUT_MS         (15000)
#define KNOB_INPUT_JOYSTICK_XYZ_REST_SAMPLES               (256)
#define KNOB_INPUT_JOYSTICK_XYZ_SWEEP_SAMPLES              (512)
#define KNOB_INPUT_START_LONG_PRESS_MS                     (1000)
#define KNOB_INPUT_START_SHIP_IMMINENT_MS                  (11000)
#define KNOB_INPUT_START_SHIP_PREP_MS                      (5000)
#define KNOB_INPUT_START_SHIP_WARN_MS                      (9000)
#define KNOB_INPUT_START_STABLE_SAMPLES                    (2)
#define KNOB_POWER_AUTO_STOP2_CHECK_PERIOD_MS              (100)
#define KNOB_POWER_AUTO_STOP2_ENABLE                       (1)
#define KNOB_POWER_AUTO_STOP2_IDLE_MS                      (0)
#define KNOB_POWER_BATTERY_CRITICAL_SHIP_MV                (3300)
#define KNOB_POWER_BATTERY_MONITOR_PERIOD_MS               (1000)
#define KNOB_POWER_BATTERY_RESTART_ALLOW_MV                (3600)
#define KNOB_POWER_BATTERY_WARNING_MV                      (3500)
#define KNOB_POWER_BOOT_LOW_BATTERY_SHIP_ENABLE            (0)
#define KNOB_POWER_CHARGER_CURRENT_SETTING                 (41)
#define KNOB_POWER_CHARGER_FUNCTION_SETTING                (172)
#define KNOB_POWER_CHARGER_TERMINATION_SETTING             (130)
#define KNOB_POWER_CHARGER_THERMISTOR_CONTROL              (128)
#define KNOB_POWER_CHARGER_VBUS_ILIM                       (129)
#define KNOB_POWER_CLOCK_IO_HIGH_HZ                        (160000000)
#define KNOB_POWER_CLOCK_PLL2_AUTOGATE_ENABLE              (1)
#define KNOB_POWER_CLOCK_REACTIVE_BASE_HZ                  (24000000)
#define KNOB_POWER_CLOCK_REACTIVE_BURST_HZ                 (48000000)
#define KNOB_POWER_CLOCK_REALTIME_BALANCED_HZ              (80000000)
#define KNOB_POWER_CRITICAL_SOFTWARE_SHIP_ENABLE           (0)
#define KNOB_POWER_PMIC_INTERRUPT_ENABLE1                  (3)
#define KNOB_POWER_PMIC_INTERRUPT_ENABLE2                  (0)
#define KNOB_POWER_START_SOFTWARE_SHIP_ENABLE              (0)
#define KNOB_POWER_STOP2_DISPLAY_WAIT_BACKEND              (2)
#define KNOB_POWER_STOP2_GPIO_PARK_GROUP_MASK              (30)
#define KNOB_RTOS_DEFAULT_STACK_BYTES                      (1024)
#define KNOB_RTOS_DISPLAY_STACK_BYTES                      (3072)
#define KNOB_RTOS_INPUT_STACK_BYTES                        (1536)
#define KNOB_RTOS_POWER_STACK_BYTES                        (4096)
#define KNOB_RTOS_SENSOR_STACK_BYTES                       (3072)
#define KNOB_RTOS_STORAGE_STACK_BYTES                      (2048)
#define KNOB_RUNTIME_EGG_HASH_TIMEOUT_MS                   (100)

#endif /* KNOBS_AUTOGEN_H */
