/* AUTO-GENERATED FILE. DO NOT EDIT. */
/* Source: config/knobs.json */
/* Generator: tools/gen_knobs.py */

#ifndef KNOBS_AUTOGEN_H
#define KNOBS_AUTOGEN_H

#define KNOB_DEBUG_SWO_LIFECYCLE_ENABLE          (1)
#define KNOB_DEBUG_TRACEX_BUFFER_BYTES           (32768)
#define KNOB_DEBUG_TRACEX_ENABLE                 (1)
#define KNOB_DEBUG_TRACEX_REGISTRY_ENTRIES       (64)
#define KNOB_DEBUG_TRACEX_USER_EVENTS_ENABLE     (1)
#define KNOB_INPUT_START_LONG_PRESS_MS           (1000)
#define KNOB_INPUT_START_SHIP_IMMINENT_MS        (11000)
#define KNOB_INPUT_START_SHIP_PREP_MS            (5000)
#define KNOB_INPUT_START_SHIP_WARN_MS            (9000)
#define KNOB_INPUT_START_STABLE_SAMPLES          (2)
#define KNOB_POWER_BATTERY_CRITICAL_SHIP_MV      (3300)
#define KNOB_POWER_BATTERY_MONITOR_PERIOD_MS     (1000)
#define KNOB_POWER_BATTERY_RESTART_ALLOW_MV      (3600)
#define KNOB_POWER_BATTERY_WARNING_MV            (3500)
#define KNOB_POWER_BOOT_LOW_BATTERY_SHIP_ENABLE  (0)
#define KNOB_POWER_CHARGER_CURRENT_SETTING       (41)
#define KNOB_POWER_CHARGER_FUNCTION_SETTING      (172)
#define KNOB_POWER_CHARGER_TERMINATION_SETTING   (130)
#define KNOB_POWER_CHARGER_THERMISTOR_CONTROL    (128)
#define KNOB_POWER_CHARGER_VBUS_ILIM             (129)
#define KNOB_POWER_CLOCK_IO_HIGH_HZ              (160000000)
#define KNOB_POWER_CLOCK_PLL2_AUTOGATE_ENABLE    (1)
#define KNOB_POWER_CLOCK_REACTIVE_BASE_HZ        (24000000)
#define KNOB_POWER_CLOCK_REACTIVE_BURST_HZ       (48000000)
#define KNOB_POWER_CLOCK_REALTIME_BALANCED_HZ    (80000000)
#define KNOB_POWER_CRITICAL_SOFTWARE_SHIP_ENABLE (0)
#define KNOB_POWER_PMIC_INTERRUPT_ENABLE1        (3)
#define KNOB_POWER_PMIC_INTERRUPT_ENABLE2        (0)
#define KNOB_POWER_START_SOFTWARE_SHIP_ENABLE    (0)

#endif /* KNOBS_AUTOGEN_H */
