#ifndef PS_AUDIO_EVENTS_H
#define PS_AUDIO_EVENTS_H

typedef enum
{
  AUDIO_EV_INIT_REQ = 1,
  AUDIO_EV_INIT_OK,
  AUDIO_EV_TONE_REQ,
  AUDIO_EV_DMA_START_OK,
  AUDIO_EV_PLAYBACK_DONE,
  AUDIO_EV_DISABLE_DONE,
  AUDIO_EV_QUIESCE,
  AUDIO_EV_RESUME,
  AUDIO_EV_DMA_ERROR,
  AUDIO_EV_UNDERRUN,
  AUDIO_EV_RECOVER_OK
} PS_AudioEvent;

typedef enum
{
  SPK_EV_ENABLE_REQUEST = 1,
  SPK_EV_ENABLED,
  SPK_EV_PRELOAD,
  SPK_EV_DMA_START_OK,
  SPK_EV_PLAYBACK_DONE,
  SPK_EV_DRAINED,
  SPK_EV_DISABLE,
  SPK_EV_FAULT,
  SPK_EV_RECOVER_OK
} PS_SpeakerEvent;

#endif /* PS_AUDIO_EVENTS_H */
