#ifndef PS_COMM_EVENTS_H
#define PS_COMM_EVENTS_H

typedef enum
{
  BLE_EV_ENABLE_REQUEST = 1,
  BLE_EV_DISABLE_REQUEST,
  BLE_EV_RESET_ASSERTED,
  BLE_EV_BOOT_READY,
  BLE_EV_BOOT_TIMEOUT,
  BLE_EV_CONFIG_OK,
  BLE_EV_CONFIG_FAIL,
  BLE_EV_ADV_START_REQUEST,
  BLE_EV_ADV_STOP_REQUEST,
  BLE_EV_CONNECTED,
  BLE_EV_DISCONNECTED,
  BLE_EV_PAIRING_START,
  BLE_EV_PAIRING_DONE,
  BLE_EV_BOND_STORE_OK,
  BLE_EV_BOND_STORE_FAIL,
  BLE_EV_TX_REQUEST,
  BLE_EV_RX_READY,
  BLE_EV_TRANSFER_DONE,
  BLE_EV_QUIESCE,
  BLE_EV_RESUME,
  BLE_EV_FAULT,
  BLE_EV_RECOVER_OK,
  BLE_EV_RECOVER_EXHAUSTED
} PS_BleEvent;

#endif /* PS_COMM_EVENTS_H */
