#ifndef PS_COMM_STATE_H
#define PS_COMM_STATE_H

typedef enum
{
  BLE_OFF = 0,
  BLE_RESET_ASSERT,
  BLE_BOOT_WAIT,
  BLE_CONFIG,
  BLE_IDLE,
  BLE_ADVERTISING,
  BLE_CONNECTED,
  BLE_PAIRING,
  BLE_TRANSFER,
  BLE_SUSPENDING,
  BLE_SUSPENDED,
  BLE_ERROR
} PS_BleState;

#endif /* PS_COMM_STATE_H */
