#ifndef PS_DISPLAY_STATE_H
#define PS_DISPLAY_STATE_H

typedef enum
{
  DISP_OFF = 0,
  DISP_INIT,
  DISP_STATIC_HOLD,
  DISP_LP_DIRTY,
  DISP_LP_FLUSH,
  DISP_RT_ACTIVE,
  DISP_RT_FLUSH,
  DISP_LPBAM_ARM,
  DISP_LPBAM_RUNNING,
  DISP_LPBAM_EXIT,
  DISP_SUSPENDING,
  DISP_SUSPENDED,
  DISP_RECOVERING,
  DISP_ERROR
} PS_DisplayState;

typedef enum
{
  FLUSH_IDLE = 0,
  FLUSH_BUILD_CMD,
  FLUSH_TRANSFER_ACTIVE,
  FLUSH_WAIT_COMPLETE,
  FLUSH_COMMIT,
  FLUSH_ABORT,
  FLUSH_ERROR
} PS_DisplayFlushState;

typedef enum
{
  LPBAM_DISP_UNAVAILABLE = 0,
  LPBAM_DISP_PREPARE,
  LPBAM_DISP_VALIDATE_LIST,
  LPBAM_DISP_ARMED,
  LPBAM_DISP_RUNNING,
  LPBAM_DISP_WAKE_REQUESTED,
  LPBAM_DISP_STOPPING,
  LPBAM_DISP_FAULT
} PS_LpbamDisplayState;

#endif /* PS_DISPLAY_STATE_H */
