#ifndef PS_DISPLAY_EVENTS_H
#define PS_DISPLAY_EVENTS_H

typedef enum
{
  DISP_EV_ENABLE_REQ = 1,
  DISP_EV_INIT_OK,
  DISP_EV_INVALIDATE,
  DISP_EV_PRESENT,
  DISP_EV_FLUSH_DONE,
  DISP_EV_STATIC_HOLD_REQ,
  DISP_EV_RT_ENTER,
  DISP_EV_LP_ENTER,
  DISP_EV_LPBAM_REQ,
  DISP_EV_LPBAM_RUNNING,
  DISP_EV_LPBAM_WAKE_REQ,
  DISP_EV_QUIESCE,
  DISP_EV_RESUME,
  DISP_EV_FAULT,
  DISP_EV_RECOVER_OK
} PS_DisplayEvent;

#endif /* PS_DISPLAY_EVENTS_H */
