#ifndef PS_INPUT_STATE_H
#define PS_INPUT_STATE_H

typedef enum
{
  BTN_DISABLED = 0,
  BTN_RELEASED,
  BTN_DEBOUNCE_PRESS,
  BTN_PRESSED,
  BTN_HELD,
  BTN_REPEAT,
  BTN_DEBOUNCE_RELEASE,
  BTN_STUCK,
  BTN_ERROR
} PS_ButtonState;

typedef enum
{
  BTN_CLASSIFIER_IDLE = 0,
  BTN_CLASSIFIER_SINGLE_PENDING,
  BTN_CLASSIFIER_CHORD_PENDING,
  BTN_CLASSIFIER_CHORD_ACTIVE,
  BTN_CLASSIFIER_REPEAT_ACTIVE,
  BTN_CLASSIFIER_LOCKED
} PS_ButtonClassifierState;

typedef enum
{
  START_IDLE = 0,
  START_NORMAL_PRESS,
  START_LONG_PRESS,
  START_SHIP_PREP,
  START_SHIP_WARNING,
  START_SHIP_IMMINENT,
  START_RELEASED
} PS_StartOverlayState;

typedef enum
{
  JOY_OFF = 0,
  JOY_PROBE,
  JOY_CONFIG,
  JOY_CAL_REQUIRED,
  JOY_CENTER_CAL,
  JOY_THRESHOLD_ARMED,
  JOY_WAKE_PENDING,
  JOY_DIRECTION_SAMPLE,
  JOY_SLOW_POLL,
  JOY_FAST_POLL,
  JOY_NORMALIZE,
  JOY_SAFE_MODE,
  JOY_SUSPENDED,
  JOY_RECOVERING,
  JOY_ERROR
} PS_JoystickState;

#endif /* PS_INPUT_STATE_H */
