#ifndef PS_INPUT_EVENTS_H
#define PS_INPUT_EVENTS_H

typedef enum
{
  BTN_EV_EDGE_ACTIVE = 1,
  BTN_EV_EDGE_INACTIVE,
  BTN_EV_DEBOUNCE_DONE,
  BTN_EV_LONG_THRESHOLD,
  BTN_EV_REPEAT_THRESHOLD,
  BTN_EV_REPEAT_TICK,
  BTN_EV_STUCK_THRESHOLD,
  BTN_EV_START_SHIP_PREP_THRESHOLD,
  BTN_EV_START_SHIP_WARN_THRESHOLD,
  BTN_EV_START_SHIP_IMMINENT_THRESHOLD,
  BTN_EV_LOCK,
  BTN_EV_UNLOCK,
  BTN_EV_FAULT
} PS_ButtonEvent;

typedef enum
{
  JOY_EV_ENABLE_REQUEST = 1,
  JOY_EV_DISABLE_REQUEST,
  JOY_EV_PROBE_OK,
  JOY_EV_CONFIG_OK,
  JOY_EV_CAL_MISSING,
  JOY_EV_CAL_START,
  JOY_EV_CAL_DONE,
  JOY_EV_THRESHOLD_ARM_REQUEST,
  JOY_EV_INTERRUPT,
  JOY_EV_SAMPLE_DONE,
  JOY_EV_NORMALIZE_DONE,
  JOY_EV_SLOW_POLL_REQUEST,
  JOY_EV_FAST_POLL_REQUEST,
  JOY_EV_QUIESCE,
  JOY_EV_RESUME,
  JOY_EV_I2C_ERROR,
  JOY_EV_RECOVER_OK
} PS_JoystickEvent;

#endif /* PS_INPUT_EVENTS_H */
