#ifndef PS_POWER_EVENTS_H
#define PS_POWER_EVENTS_H

typedef enum
{
  PWR_EV_BOOT = 1,
  PWR_EV_RAILS_OK,
  PWR_EV_RAILS_FAIL,
  PWR_EV_RT_REQUEST,
  PWR_EV_LP_REQUEST,
  PWR_EV_SLEEP_REQUEST,
  PWR_EV_STOP_ENTERED,
  PWR_EV_WAKE,
  PWR_EV_LOW_BATTERY,
  PWR_EV_SHIP_REQUEST,
  PWR_EV_FAULT,
  PWR_EV_RECOVER_OK
} PS_PowerEvent;

typedef enum
{
  PMIC_EV_PROBE_REQUEST = 1,
  PMIC_EV_PROBE_OK,
  PMIC_EV_PROBE_FAIL,
  PMIC_EV_CONFIG_OK,
  PMIC_EV_CHARGING,
  PMIC_EV_CHARGE_DONE,
  PMIC_EV_LOW_BATTERY,
  PMIC_EV_CRITICAL_BATTERY,
  PMIC_EV_SHIP_REQUEST,
  PMIC_EV_FAULT,
  PMIC_EV_RECOVER_OK
} PS_PmicEvent;

#endif /* PS_POWER_EVENTS_H */
