#ifndef PS_POWER_STATE_H
#define PS_POWER_STATE_H

typedef enum
{
  PWR_BOOTING = 0,
  PWR_RAIL_VALIDATE,
  PWR_ACTIVE_LP,
  PWR_ACTIVE_RT,
  PWR_SLEEP_PREP,
  PWR_STOP_RESIDENT,
  PWR_WAKE_RESUME,
  PWR_FORCED_SLEEP,
  PWR_SHIP_PREP,
  PWR_FAULT
} PS_PowerState;

typedef enum
{
  PMIC_OFFLINE = 0,
  PMIC_PROBE,
  PMIC_CONFIG,
  PMIC_MONITOR,
  PMIC_CHARGING,
  PMIC_CHARGE_DONE,
  PMIC_LOW_BATT,
  PMIC_CRITICAL_BATT,
  PMIC_SHIP_PENDING,
  PMIC_RECOVERING,
  PMIC_ERROR
} PS_PmicState;

#endif /* PS_POWER_STATE_H */
