#ifndef PS_SENSOR_STATE_H
#define PS_SENSOR_STATE_H

typedef enum
{
  IMU_OFF = 0,
  IMU_PROBE,
  IMU_CONFIG,
  IMU_EMBEDDED_FUNC_ENABLE,
  IMU_STEP_COUNTER_ACTIVE,
  IMU_EVENT_ARMED,
  IMU_LOW_RATE_SAMPLE,
  IMU_STREAMING,
  IMU_SUSPENDED,
  IMU_RECOVERING,
  IMU_ERROR
} PS_ImuState;

#endif /* PS_SENSOR_STATE_H */
