#ifndef PS_STATUS_H
#define PS_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum
{
  PS_STATUS_OK = 0,
  PS_STATUS_INVALID_ARGUMENT,
  PS_STATUS_NOT_INITIALIZED,
  PS_STATUS_BUSY,
  PS_STATUS_TIMEOUT,
  PS_STATUS_IO_ERROR,
  PS_STATUS_VERIFY_FAILED,
  PS_STATUS_IDENTITY_MISMATCH,
  PS_STATUS_EXPECTED_NACK,
  PS_STATUS_LEASE_EXPIRED,
  PS_STATUS_INVALID_STATE,
  PS_STATUS_UNSUPPORTED,
  PS_STATUS_RECOVERY_REQUIRED,
  PS_STATUS_INTERNAL_ERROR
} ps_status_t;

#ifdef __cplusplus
}
#endif

#endif /* PS_STATUS_H */
