#ifndef PS_STORAGE_STATE_H
#define PS_STORAGE_STATE_H

typedef enum
{
  STORAGE_OFFLINE = 0,
  STORAGE_INIT,
  STORAGE_FLASH_READY,
  STORAGE_LOCAL_MOUNT,
  STORAGE_LOCAL_READY,
  STORAGE_QUIESCE_LOCAL,
  STORAGE_PREPARE_USB,
  STORAGE_USB_STAGING_EXPORTED,
  STORAGE_USB_STAGING_DIRTY,
  STORAGE_USB_RELEASE,
  STORAGE_INSTALLING,
  STORAGE_RECOVERING,
  STORAGE_SAFE_MODE,
  STORAGE_ERROR
} PS_StorageState;

typedef enum
{
  FLASH_OFF = 0,
  FLASH_RESET,
  FLASH_PROBE,
  FLASH_CONFIG,
  FLASH_READY,
  FLASH_BUSY_READ,
  FLASH_BUSY_PROGRAM,
  FLASH_BUSY_ERASE,
  FLASH_DEEP_POWER_DOWN,
  FLASH_RECOVERING,
  FLASH_ERROR
} PS_FlashState;

#endif /* PS_STORAGE_STATE_H */
