#ifndef PS_SENSOR_EVENTS_H
#define PS_SENSOR_EVENTS_H

typedef enum
{
  IMU_EV_ENABLE_REQUEST = 1,
  IMU_EV_DISABLE_REQUEST,
  IMU_EV_PROBE_OK,
  IMU_EV_CONFIG_OK,
  IMU_EV_EMBEDDED_ENABLE_OK,
  IMU_EV_STEP_COUNTER_REQUEST,
  IMU_EV_WAKE_HINT_STEP,
  IMU_EV_WAKE_HINT_MOTION,
  IMU_EV_WAKE_HINT_GESTURE,
  IMU_EV_LOW_RATE_SAMPLE_REQUEST,
  IMU_EV_STREAM_REQUEST,
  IMU_EV_STREAM_STOP,
  IMU_EV_QUIESCE,
  IMU_EV_RESUME,
  IMU_EV_I2C_ERROR,
  IMU_EV_RECOVER_OK
} PS_ImuEvent;

#endif /* PS_SENSOR_EVENTS_H */
