#ifndef PS_STORAGE_EVENTS_H
#define PS_STORAGE_EVENTS_H

typedef enum
{
  STORAGE_EV_INIT = 1,
  STORAGE_EV_FLASH_READY,
  STORAGE_EV_MOUNT_OK,
  STORAGE_EV_MOUNT_FAIL,
  STORAGE_EV_LOCAL_QUIESCE_REQUEST,
  STORAGE_EV_LOCAL_QUIESCE_OK,
  STORAGE_EV_INSTALLER_ENTER,
  STORAGE_EV_UNMOUNT_OK,
  STORAGE_EV_USB_VBUS_PRESENT,
  STORAGE_EV_USB_ACTIVITY_DETECTED,
  STORAGE_EV_USB_ENUMERATED,
  STORAGE_EV_USB_MSC_ENTRY_ACCEPTED,
  STORAGE_EV_USB_DETACH,
  STORAGE_EV_USB_HOST_DIRTY,
  STORAGE_EV_USB_RELEASE_REQUEST,
  STORAGE_EV_USB_RESCAN_OK,
  STORAGE_EV_INSTALL_START,
  STORAGE_EV_INSTALL_DONE,
  STORAGE_EV_FAULT,
  STORAGE_EV_RECOVER_OK
} PS_StorageEvent;

typedef enum
{
  FLASH_EV_BOOT = 1,
  FLASH_EV_PROBE_OK,
  FLASH_EV_PROBE_FAIL,
  FLASH_EV_CONFIG_OK,
  FLASH_EV_REQUEST_READ,
  FLASH_EV_REQUEST_WRITE,
  FLASH_EV_REQUEST_ERASE,
  FLASH_EV_REQUEST_DEEP_POWER_DOWN,
  FLASH_EV_WAKE_REVALIDATE,
  FLASH_EV_OPERATION_DONE,
  FLASH_EV_FAULT,
  FLASH_EV_RECOVER_RETRY
} PS_FlashEvent;

#endif /* PS_STORAGE_EVENTS_H */
