#ifndef PS_UI_ROUTER_H
#define PS_UI_ROUTER_H

#include <stdint.h>

#include "ps_status.h"

#ifdef __cplusplus
extern "C" {
#endif

#define PS_UI_ROUTER_API_VERSION (18UL)
#define PS_UI_ROUTER_STATUS_NOT_RUN (0xFFFFFFFFUL)
#define PS_UI_ROUTER_PACKAGE_MENU_FOCUS_BASE (100UL)

typedef enum
{
  PS_UI_ROUTER_PAGE_BOOTSTRAP = 0,
  PS_UI_ROUTER_PAGE_HOME,
  PS_UI_ROUTER_PAGE_MENU,
  PS_UI_ROUTER_PAGE_SETTINGS,
  PS_UI_ROUTER_PAGE_CALIBRATION,
  PS_UI_ROUTER_PAGE_PACKAGE_BROWSER,
  PS_UI_ROUTER_PAGE_RUNTIME_HANDOFF,
  PS_UI_ROUTER_PAGE_ERROR,
  PS_UI_ROUTER_PAGE_SHUTDOWN,
  PS_UI_ROUTER_PAGE_INTERACTION_CUE,
  PS_UI_ROUTER_PAGE_INTERACTION_ACTIVATION,
  PS_UI_ROUTER_PAGE_INPUT_DIAGNOSTIC
} ps_ui_router_page_t;

typedef enum
{
  PS_UI_ROUTER_NAV_IDLE = 0,
  PS_UI_ROUTER_NAV_FOCUS,
  PS_UI_ROUTER_NAV_TRANSITION_LOCK,
  PS_UI_ROUTER_NAV_TEXT_ENTRY,
  PS_UI_ROUTER_NAV_NUMERIC_ENTRY,
  PS_UI_ROUTER_NAV_MODAL_LOCK
} ps_ui_router_nav_t;

typedef enum
{
  PS_UI_ROUTER_MODAL_NONE = 0,
  PS_UI_ROUTER_MODAL_DIALOG,
  PS_UI_ROUTER_MODAL_INPUT_ENTRY
} ps_ui_router_modal_t;

typedef enum
{
  PS_UI_ROUTER_CAL_NONE = 0,
  PS_UI_ROUTER_CAL_INPUT_ROOT,
  PS_UI_ROUTER_CAL_JOYSTICK_NEUTRAL,
  PS_UI_ROUTER_CAL_JOYSTICK_RIGHT,
  PS_UI_ROUTER_CAL_JOYSTICK_SWEEP,
  PS_UI_ROUTER_CAL_JOYSTICK_REVIEW,
  PS_UI_ROUTER_CAL_JOYSTICK_UP,
  PS_UI_ROUTER_CAL_JOYSTICK_DOWN,
  PS_UI_ROUTER_CAL_JOYSTICK_LEFT
} ps_ui_router_calibration_page_t;

typedef enum
{
  PS_UI_ROUTER_SHUTDOWN_NONE = 0,
  PS_UI_ROUTER_SHUTDOWN_PREP,
  PS_UI_ROUTER_SHUTDOWN_WARNING,
  PS_UI_ROUTER_SHUTDOWN_IMMINENT,
  PS_UI_ROUTER_SHUTDOWN_CANCELLED,
  PS_UI_ROUTER_SHUTDOWN_LOW_BATTERY_BOOT,
  PS_UI_ROUTER_SHUTDOWN_LOW_BATTERY_CHARGE,
  PS_UI_ROUTER_SHUTDOWN_FLASH_INIT,
  PS_UI_ROUTER_SHUTDOWN_FLASH_DONE,
  PS_UI_ROUTER_SHUTDOWN_FLASH_ERROR,
  PS_UI_ROUTER_SHUTDOWN_MSC_EXPORT,
  PS_UI_ROUTER_SHUTDOWN_MSC_ACTIVE,
  PS_UI_ROUTER_SHUTDOWN_MSC_RECLAIM,
  PS_UI_ROUTER_SHUTDOWN_MSC_DONE,
  PS_UI_ROUTER_SHUTDOWN_MSC_ERROR,
  PS_UI_ROUTER_SHUTDOWN_MSC_RECOVERY,
  PS_UI_ROUTER_SHUTDOWN_JOYSTICK_XYZ_REST,
  PS_UI_ROUTER_SHUTDOWN_JOYSTICK_XYZ_SWEEP,
  PS_UI_ROUTER_SHUTDOWN_JOYSTICK_XYZ_DONE,
  PS_UI_ROUTER_SHUTDOWN_JOYSTICK_XYZ_ERROR
} ps_ui_router_shutdown_state_t;

typedef enum
{
  PS_UI_ROUTER_PACKAGE_NONE = 0,
  PS_UI_ROUTER_PACKAGE_CANDIDATE,
  PS_UI_ROUTER_PACKAGE_VALID,
  PS_UI_ROUTER_PACKAGE_INSTALLING,
  PS_UI_ROUTER_PACKAGE_INSTALLED,
  PS_UI_ROUTER_PACKAGE_CANCELLED,
  PS_UI_ROUTER_PACKAGE_ERROR
} ps_ui_router_package_state_t;

typedef enum
{
  PS_UI_ROUTER_EVENT_BOOT_COMPLETE = 1,
  PS_UI_ROUTER_EVENT_NAV_HOME,
  PS_UI_ROUTER_EVENT_NAV_MENU,
  PS_UI_ROUTER_EVENT_NAV_SETTINGS,
  PS_UI_ROUTER_EVENT_NAV_CALIBRATION,
  PS_UI_ROUTER_EVENT_NAV_PACKAGES,
  PS_UI_ROUTER_EVENT_LAUNCH_RUNTIME,
  PS_UI_ROUTER_EVENT_RUNTIME_RETURNED,
  PS_UI_ROUTER_EVENT_SHELL_FAULT,
  PS_UI_ROUTER_EVENT_RECOVER_OK,
  PS_UI_ROUTER_EVENT_CAL_JOYSTICK_START,
  PS_UI_ROUTER_EVENT_CAL_JOYSTICK_NEUTRAL_ACCEPT,
  PS_UI_ROUTER_EVENT_CAL_JOYSTICK_RIGHT_ACCEPT,
  PS_UI_ROUTER_EVENT_CAL_JOYSTICK_SWEEP_ACCEPT,
  PS_UI_ROUTER_EVENT_CAL_JOYSTICK_REVIEW_ACCEPT,
  PS_UI_ROUTER_EVENT_PAGE_TRANSITION_END,
  PS_UI_ROUTER_EVENT_INPUT_BTN_A,
  PS_UI_ROUTER_EVENT_INPUT_BTN_B,
  PS_UI_ROUTER_EVENT_INPUT_BTN_L,
  PS_UI_ROUTER_EVENT_INPUT_BTN_R,
  PS_UI_ROUTER_EVENT_SHUTDOWN_PREP,
  PS_UI_ROUTER_EVENT_SHUTDOWN_WARNING,
  PS_UI_ROUTER_EVENT_SHUTDOWN_IMMINENT,
  PS_UI_ROUTER_EVENT_SHUTDOWN_CANCEL,
  PS_UI_ROUTER_EVENT_LOW_BATTERY_BOOT_BLOCK,
  PS_UI_ROUTER_EVENT_LOW_BATTERY_CHARGE_RECOVERY,
  PS_UI_ROUTER_EVENT_PACKAGE_CANDIDATE_FOUND,
  PS_UI_ROUTER_EVENT_PACKAGE_VALID_FOUND,
  PS_UI_ROUTER_EVENT_PACKAGE_VALIDATE_ERROR,
  PS_UI_ROUTER_EVENT_PACKAGE_INSTALL_STUB_DONE,
  PS_UI_ROUTER_EVENT_PACKAGE_INSTALL_STUB_ERROR,
  PS_UI_ROUTER_EVENT_PACKAGE_CLEAR,
  PS_UI_ROUTER_EVENT_JOYSTICK_XYZ_REST,
  PS_UI_ROUTER_EVENT_JOYSTICK_XYZ_SWEEP,
  PS_UI_ROUTER_EVENT_JOYSTICK_XYZ_DONE,
  PS_UI_ROUTER_EVENT_JOYSTICK_XYZ_ERROR,
  PS_UI_ROUTER_EVENT_RUNTIME_UNAVAILABLE,
  PS_UI_ROUTER_EVENT_CAL_JOYSTICK_UP_ACCEPT,
  PS_UI_ROUTER_EVENT_CAL_JOYSTICK_DOWN_ACCEPT,
  PS_UI_ROUTER_EVENT_CAL_JOYSTICK_LEFT_ACCEPT,
  PS_UI_ROUTER_EVENT_INPUT_JOY_LEFT,
  PS_UI_ROUTER_EVENT_INPUT_JOY_RIGHT,
  PS_UI_ROUTER_EVENT_INPUT_JOY_UP,
  PS_UI_ROUTER_EVENT_INPUT_JOY_DOWN,
  PS_UI_ROUTER_EVENT_NAV_INPUT_DIAGNOSTIC,
  PS_UI_ROUTER_EVENT_MSC_EXPORT,
  PS_UI_ROUTER_EVENT_MSC_ACTIVE,
  PS_UI_ROUTER_EVENT_MSC_RECLAIM,
  PS_UI_ROUTER_EVENT_MSC_DONE,
  PS_UI_ROUTER_EVENT_MSC_ERROR,
  PS_UI_ROUTER_EVENT_MSC_RECOVERY,
  PS_UI_ROUTER_EVENT_SYSTEM_MENU_REQUEST,
  PS_UI_ROUTER_EVENT_SYSTEM_MENU_ACTIVE,
  PS_UI_ROUTER_EVENT_SYSTEM_MENU_SHELL,
  PS_UI_ROUTER_EVENT_SYSTEM_MENU_DISCARD,
  PS_UI_ROUTER_EVENT_SYSTEM_MENU_RESUMED,
  PS_UI_ROUTER_EVENT_PACKAGE_INSTALL_BEGIN
} ps_ui_router_event_t;

typedef enum
{
  PS_UI_ROUTER_ACTION_NONE = 0,
  PS_UI_ROUTER_ACTION_MSC_ENTER,
  PS_UI_ROUTER_ACTION_MSC_EXIT,
  PS_UI_ROUTER_ACTION_PACKAGE_SCAN,
  PS_UI_ROUTER_ACTION_PACKAGE_INSTALL_STUB,
  PS_UI_ROUTER_ACTION_PACKAGE_LAUNCH,
  PS_UI_ROUTER_ACTION_SYSTEM_MENU_ENTER,
  PS_UI_ROUTER_ACTION_RUNTIME_RESUME
} ps_ui_router_action_t;

typedef struct
{
  uint32_t api_version;
  uint32_t current_page;
  uint32_t previous_page;
  uint32_t requested_page;
  uint32_t nav_state;
  uint32_t modal_state;
  uint32_t calibration_page;
  uint32_t focus_index;
  uint32_t shutdown_state;
  uint32_t shutdown_countdown_seconds;
  uint32_t shutdown_event_count;
  uint32_t shutdown_return_page;
  uint32_t package_state;
  uint32_t package_event_count;
  uint32_t eggless;
  uint32_t resume_available;
  uint32_t last_button_event;
  uint32_t button_event_count;
  uint32_t last_joystick_event;
  uint32_t joystick_event_count;
  uint32_t joystick_candidate_direction_mask;
  uint32_t joystick_resolved_direction_mask;
  uint32_t joystick_state_update_count;
  uint32_t pending_action;
  uint32_t last_action;
  uint32_t action_request_count;
  uint32_t action_take_count;
  uint32_t last_event;
  uint32_t transition_count;
  uint32_t rejected_event_count;
  uint32_t last_status;
} ps_ui_router_probe_t;

extern volatile ps_ui_router_probe_t g_ps_ui_router_probe;
extern volatile uint32_t g_ps_ui_router_request;
extern volatile uint32_t g_ps_ui_router_request_event;

void PS_UIRouter_Init(void);
ps_status_t PS_UIRouter_Dispatch(uint32_t event);
ps_status_t PS_UIRouter_RecordJoystickState(uint32_t candidate_direction_mask,
                                            uint32_t resolved_direction_mask);
uint32_t PS_UIRouter_TakeAction(void);

#ifdef __cplusplus
}
#endif

#endif /* PS_UI_ROUTER_H */
