set pagination off
printf "=== FW0 PHASE6 LPBAM DISPLAY STOP TEST ===\n"
printf "stage                          = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_stage
printf "stop2_attempted                = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_stop2_attempted
printf "stop2_returned                 = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_stop2_returned
printf "stop2_return_count             = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_stop2_return_count
printf "button_wake_rearm_done         = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_button_wake_rearm_done
printf "exti_imr1_before_stop          = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_exti_imr1_before_stop
printf "exti_rtsr1_before_stop         = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_exti_rtsr1_before_stop
printf "exti_ftsr1_before_stop         = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_exti_ftsr1_before_stop
printf "exti_callback_count            = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_exti_callback_count
printf "wake_reason                    = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_wake_reason
printf "wake_button_id                 = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_wake_button_id
printf "wake_tick                      = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_wake_tick
printf "lpbam_display_enabled          = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_display_enabled
printf "lpbam_display_rows             = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_display_rows
printf "lpbam_rebuild_count            = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_rebuild_count
printf "lpbam_compile_variant          = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_compile_variant
printf "quiesce_tick                  = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_quiesce_tick
printf "quiesce_ack_mask              = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_quiesce_ack_mask
printf "quiesce_ack_wait_ticks        = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_quiesce_ack_wait_ticks
printf "quiesce_ack_wait_complete     = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_quiesce_ack_wait_complete
printf "lpbam_prearm_status            = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_prearm_status
printf "lpbam_prearm_tick              = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_prearm_tick
printf "lpbam_start_request_tick       = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_start_request_tick
printf "lpbam_dma_started_tick         = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_started_tick
printf "lpbam_lptim_started_tick       = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_lptim_started_tick
printf "lpbam_prepare_status           = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_prepare_status
printf "lpbam_fill_status              = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_fill_status
printf "lpbam_start_status             = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_start_status
printf "lpbam_dma_start_status         = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_start_status
printf "lpbam_lptim_start_status       = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_lptim_start_status
printf "lpbam_active_frames            = 0x%lx\n", ps_lpbam_display_active_frame_count
printf "lpbam_active_chunks            = {0x%lx, 0x%lx, 0x%lx, 0x%lx}\n", ps_lpbam_display_active_chunk_count[0], ps_lpbam_display_active_chunk_count[1], ps_lpbam_display_active_chunk_count[2], ps_lpbam_display_active_chunk_count[3]
printf "lpbam_queue_start_slot         = 0x%lx\n", ps_lpbam_display_queue_start_slot
printf "lpbam_tx_len_f0                = {0x%x, 0x%x, 0x%x}\n", ps_lpbam_display_tx_len[0][0], ps_lpbam_display_tx_len[0][1], ps_lpbam_display_tx_len[0][2]
printf "lpbam_tx_len_f1                = {0x%x, 0x%x, 0x%x}\n", ps_lpbam_display_tx_len[1][0], ps_lpbam_display_tx_len[1][1], ps_lpbam_display_tx_len[1][2]
printf "lpbam_tx_len_f2                = {0x%x, 0x%x, 0x%x}\n", ps_lpbam_display_tx_len[2][0], ps_lpbam_display_tx_len[2][1], ps_lpbam_display_tx_len[2][2]
printf "lpbam_tx_len_f3                = {0x%x, 0x%x, 0x%x}\n", ps_lpbam_display_tx_len[3][0], ps_lpbam_display_tx_len[3][1], ps_lpbam_display_tx_len[3][2]
printf "lpbam_dirty_start_row          = {0x%lx, 0x%lx, 0x%lx, 0x%lx}\n", ps_lpbam_display_dirty_start_row[0], ps_lpbam_display_dirty_start_row[1], ps_lpbam_display_dirty_start_row[2], ps_lpbam_display_dirty_start_row[3]
printf "lpbam_dirty_row_count          = {0x%lx, 0x%lx, 0x%lx, 0x%lx}\n", ps_lpbam_display_dirty_row_count[0], ps_lpbam_display_dirty_row_count[1], ps_lpbam_display_dirty_row_count[2], ps_lpbam_display_dirty_row_count[3]
printf "lpbam_dma_mode_after_link      = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_mode_after_link
printf "lpbam_dma_state_after_link     = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_state_after_link
printf "lpbam_dma_error_after_link     = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_error_after_link
printf "lpbam_queue_head               = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_queue_head
printf "lpbam_queue_first_circular     = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_queue_first_circular
printf "lpbam_queue_node_count         = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_queue_node_count
printf "lpbam_queue_state_after_link   = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_queue_state_after_link
printf "lpbam_queue_error_after_link   = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_queue_error_after_link
printf "lpbam_queue_type_after_link    = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_queue_type_after_link
printf "lpbam_dma_state_after_start    = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_state_after_start
printf "lpbam_dma_error_after_start    = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_error_after_start
printf "lpbam_queue_state_after_start  = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_queue_state_after_start
printf "lpbam_queue_error_after_start  = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_queue_error_after_start
printf "lpbam_dma_ccr_after_start      = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_ccr_after_start
printf "lpbam_dma_csr_after_start      = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_csr_after_start
printf "lpbam_dma_cllr_after_start     = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_cllr_after_start
printf "lpbam_spi_cr1_after_dma_start  = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_spi_cr1_after_dma_start
printf "lpbam_spi_autocr_after_dma_start = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_spi_autocr_after_dma_start
printf "lpbam_dma_state_before_stop    = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_state_before_stop
printf "lpbam_dma_state_after_stop     = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_state_after_stop
printf "lpbam_dma_csr_before_stop      = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_csr_before_stop
printf "lpbam_dma_csr_after_stop       = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_dma_csr_after_stop
printf "lpbam_spi_sr_before_stop       = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_spi_sr_before_stop
printf "lpbam_spi_sr_after_stop        = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_spi_sr_after_stop
printf "lpbam_spi_state_before_stop    = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_spi_state_before_stop
printf "lpbam_spi_state_after_stop     = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_spi_state_after_stop
printf "lpbam_spi_error_after_stop     = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_spi_error_after_stop
printf "lpbam_lptim_cr_before_stop     = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_lptim_cr_before_stop
printf "lpbam_lptim_cr_after_stop      = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_lptim_cr_after_stop
printf "lpbam_lptim_cnt_before_stop    = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_lptim_cnt_before_stop
printf "lpbam_lptim_cnt_after_stop     = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_lptim_cnt_after_stop
printf "lpbam_lptim_cfgr_before_stop   = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_lptim_cfgr_before_stop
printf "lpbam_lptim_arr_before_stop    = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_lptim_arr_before_stop
printf "lpbam_lptim_cmp_before_stop    = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_lptim_cmp_before_stop
printf "lpbam_lptim_isr_before_stop    = 0x%lx\n", g_ps_phase5_threadx_probe.phase6_lpbam_lptim_isr_before_stop
printf "\n--- live autonomous registers ---\n"
printf "LPTIM1_ISR                     = 0x%lx\n", hlptim1.Instance->ISR
printf "LPTIM1_CR                      = 0x%lx\n", hlptim1.Instance->CR
printf "LPTIM1_CNT                     = 0x%lx\n", hlptim1.Instance->CNT
printf "LPTIM1_CFGR                    = 0x%lx\n", hlptim1.Instance->CFGR
printf "LPTIM1_ARR                     = 0x%lx\n", hlptim1.Instance->ARR
printf "LPTIM1_CCR1                    = 0x%lx\n", hlptim1.Instance->CCR1
printf "SPI3_CR1                       = 0x%lx\n", hspi3.Instance->CR1
printf "SPI3_SR                        = 0x%lx\n", hspi3.Instance->SR
printf "SPI3_AUTOCR                    = 0x%lx\n", hspi3.Instance->AUTOCR
printf "LPDMA0_CSR                     = 0x%lx\n", handle_LPDMA1_Channel0.Instance->CSR
printf "LPDMA0_CCR                     = 0x%lx\n", handle_LPDMA1_Channel0.Instance->CCR
printf "LPDMA0_CTR1                    = 0x%lx\n", handle_LPDMA1_Channel0.Instance->CTR1
printf "LPDMA0_CTR2                    = 0x%lx\n", handle_LPDMA1_Channel0.Instance->CTR2
printf "LPDMA0_CBR1                    = 0x%lx\n", handle_LPDMA1_Channel0.Instance->CBR1
printf "LPDMA0_CLLR                    = 0x%lx\n", handle_LPDMA1_Channel0.Instance->CLLR
printf "=== END LPBAM DISPLAY STOP TEST ===\n"