set pagination off
printf "--- HW6 LPBAM mixed 2-phase/3-phase preferred timeline ---\n"
printf "rtos/owner api = %u / %u\n", g_ps_hw6_rtos_probe.version, g_ps_hw6_owner_probe.version
printf "variant/compile mode = %u / %u\n", g_display_renderer_waiting_test_variant, g_ps_hw6_owner_probe.display_lpbam_compile_mode
printf "elements count ids phase counts = %u / %u,%u / %u,%u\n", g_ps_hw6_owner_probe.display_lpbam_element_count, g_ps_hw6_owner_probe.display_lpbam_element_id[0], g_ps_hw6_owner_probe.display_lpbam_element_id[1], g_ps_hw6_owner_probe.display_lpbam_element_phase_count[0], g_ps_hw6_owner_probe.display_lpbam_element_phase_count[1]
printf "sequence count/start phases = %u / %u / %u,%u,%u,%u,%u,%u\n", g_ps_hw6_owner_probe.display_lpbam_sequence_frame_count, g_ps_hw6_owner_probe.display_lpbam_sequence_start_frame, g_ps_hw6_owner_probe.display_lpbam_sequence_phase[0], g_ps_hw6_owner_probe.display_lpbam_sequence_phase[1], g_ps_hw6_owner_probe.display_lpbam_sequence_phase[2], g_ps_hw6_owner_probe.display_lpbam_sequence_phase[3], g_ps_hw6_owner_probe.display_lpbam_sequence_phase[4], g_ps_hw6_owner_probe.display_lpbam_sequence_phase[5]
printf "preferred status/reason sequence/chunks/payload = 0x%x / %u / %u / %u / %u\n", g_ps_hw6_owner_probe.display_lpbam_preferred_status, g_ps_hw6_owner_probe.display_lpbam_preferred_reason, g_ps_hw6_owner_probe.display_lpbam_preferred_sequence_used, g_ps_hw6_owner_probe.display_lpbam_preferred_chunk_used, g_ps_hw6_owner_probe.display_lpbam_preferred_payload_used_bytes
printf "guaranteed attempt/status = %u / 0x%x\n", g_ps_hw6_owner_probe.display_lpbam_guaranteed_attempt_count, g_ps_hw6_owner_probe.display_lpbam_guaranteed_status
printf "edge start/target sequence frame = %u / %u\n", g_ps_hw6_rtos_probe.stop2_lpbam_edge_start_sequence_frame, g_ps_hw6_rtos_probe.stop2_lpbam_edge_target_sequence_frame
printf "wake selected/preferred frame/count/map = %u / %u / %u / 0x%x\n", g_ps_hw6_owner_probe.display_lpbam_wake_sequence_frame, g_ps_hw6_owner_probe.display_lpbam_wake_preferred_sequence_frame, g_ps_hw6_owner_probe.display_lpbam_wake_preferred_sequence_count, g_ps_hw6_owner_probe.display_lpbam_wake_preferred_map_status
printf "resume frame/count/phase/status = %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.stop2_lpbam_wake_resume_sequence_frame, g_ps_hw6_rtos_probe.stop2_lpbam_wake_resume_sequence_count, g_ps_hw6_rtos_probe.stop2_lpbam_wake_resume_phase, g_ps_hw6_rtos_probe.stop2_lpbam_wake_resume_status
printf "final admission status/reason sequence/chunks/payload = 0x%x / %u / %u/%u / %u/%u / %u/%u\n", g_ps_hw6_owner_probe.display_lpbam_admission_status, g_ps_hw6_owner_probe.display_lpbam_admission_reason, ps_lpbam_display_admission.sequence_used, ps_lpbam_display_admission.sequence_capacity, ps_lpbam_display_admission.chunk_used, ps_lpbam_display_admission.chunk_capacity, ps_lpbam_display_admission.payload_used_bytes, ps_lpbam_display_admission.payload_capacity_bytes
printf "ready/active STOP2 count/status = %u / %u / %u / 0x%x\n", g_ps_hw6_owner_probe.display_lpbam_ready, g_ps_hw6_owner_probe.display_lpbam_active, g_ps_hw6_owner_sm_probe.stop2_request_count, g_ps_hw6_owner_sm_probe.stop2_last_status
printf "expected: rtos/owner api=54/30 variant/mode=5/1 elements=2 ids=1,4 phases=2,3 sequence=6 phases=0,1,0,1,0,1 preferred=0/0 guaranteed attempts=0\n"
printf "expected after wake: preferred count=6 map/resume status=0 and resume frame equals preferred frame\n"
printf "--- end HW6 LPBAM mixed preferred timeline ---\n"
