set pagination off
printf "--- HW6 development HOME/AWAY scene exits ---\n"
if (g_ps_object_development_probe.api_version != 4) || (g_ps_scene_runtime_probe.api_version != 22) || (g_ps_object_candidate_probe.api_version != 2) || (g_ps_object_lpbam_probe.api_version != 1)
  printf "Probe mismatch: expected development/scene/candidate/LPBAM APIs 4/22/2/1. Use matching firmware and ELF.\n"
else
  printf "launch count/status/blockers active/development = %u / 0x%x / 0x%x / %u / %u\n", g_ps_object_development_probe.launch_count, g_ps_object_development_probe.launch_status, g_ps_object_development_probe.admission_blockers, g_ps_scene_runtime_probe.active, s_ps_scene_runtime_development_objects
  printf "scene/state/scene activation/state activation (HOME=1 AWAY=2; left=1 right=2) = %u / %u / %u / %u\n", g_ps_scene_runtime_probe.scene_id, g_ps_scene_runtime_probe.state_id, s_ps_scene_runtime_scene_activation, s_ps_scene_runtime_state_activation
  printf "replacement attempts/failures/source/target/status rejected event = %u / %u / %u / %u / 0x%x / %u\n", g_ps_scene_runtime_probe.scene_replace_count, g_ps_scene_runtime_probe.scene_replace_fail_count, g_ps_scene_runtime_probe.scene_replace_source_id, g_ps_scene_runtime_probe.scene_replace_target_id, g_ps_scene_runtime_probe.scene_replace_status, s_ps_object_replacement_rejected
  printf "candidate token/complete/lease/status scene = %u / %u / %u / 0x%x / %u\n", g_ps_object_candidate_probe.request_id, g_ps_object_candidate_probe.display_complete, g_ps_object_candidate_probe.leased, g_ps_object_candidate_probe.status, g_ps_object_candidate_probe.scene_id
  printf "candidate profile/reason/schedule/raster/payload chunks/bytes = 0x%x / %u / 0x%x / 0x%x / 0x%x / %u / %u\n", g_ps_object_candidate_probe.profile_status, g_ps_object_candidate_probe.profile_reason, g_ps_object_candidate_probe.schedule_status, g_ps_object_candidate_probe.raster_status, g_ps_object_candidate_probe.payload_status, g_ps_object_candidate_probe.chunks, g_ps_object_candidate_probe.bytes
  printf "last snapshot scene activation/elapsed/phase/remaining marker x/fill/moves = %u / %llu / %u / %u / %d / %u / %d\n", s_ps_object_snapshot.activation, s_ps_object_snapshot.elapsed_ms, s_ps_object_snapshot.objects[0].step, s_ps_object_snapshot.objects[0].remaining_ms, s_ps_object_snapshot.objects[1].effective.x, (s_ps_object_snapshot.objects[2].effective.flags & 1), s_ps_object_graph.variables[0]
  printf "timer due/applied/ignored/errors/RTC selections = %u / %u / %u / %u / %u\n", g_ps_hw6_rtos_probe.runtime_state_timer_due_count, g_ps_hw6_rtos_probe.runtime_state_timer_applied_count, g_ps_hw6_rtos_probe.runtime_state_timer_ignored_count, g_ps_hw6_rtos_probe.runtime_state_timer_error_count, g_ps_hw6_rtos_probe.runtime_state_timer_rtc_select_count
  printf "LPBAM enabled/fault/publish/status steps/quantum = %u / %u / %u / 0x%x / %u / %u\n", g_ps_object_lpbam_probe.enabled, g_ps_object_lpbam_probe.fault, g_ps_object_lpbam_probe.publish_count, g_ps_object_lpbam_probe.publish_status, g_ps_object_lpbam_prepare_probe.step_count, g_ps_object_lpbam_prepare_probe.quantum_ms
  printf "WFI returns/sleep measured/reconciled/clock status = %u / %u / %u / 0x%x\n", g_ps_object_lpbam_probe.physical_count, g_ps_object_lpbam_probe.sleep_count, g_ps_object_lpbam_probe.reconciled_count, g_ps_object_lpbam_probe.clock_status
  printf "wake snapshot/render/map/resume = 0x%x / 0x%x / 0x%x / 0x%x\n", g_ps_hw6_owner_probe.display_lpbam_wake_snapshot_status, g_ps_hw6_owner_probe.display_lpbam_wake_render_status, g_ps_hw6_owner_probe.display_lpbam_wake_preferred_map_status, g_ps_hw6_rtos_probe.stop2_lpbam_wake_resume_status
  printf "display request/complete/result/fault = %u / %u / 0x%x / %u\n", g_ps_object_development_probe.render_request, g_ps_object_development_probe.render_complete, g_ps_object_development_probe.render_status, g_ps_object_development_probe.lease_fault
  printf "Expected: launch/replacement/admission errors=0, candidate complete=token and lease=0; schedule 4 steps/400 ms. HOME fills after 2s; AWAY stays empty and returns after 6s.\n"
  printf "L/R moves marker x=32/120 at y=84 once; only scene entry restarts digits and resets moves. Current fields are last snapshots, not live DMA frames; halting in-flight can show NOT_RUN.\n"
  printf "Require observed HOME/AWAY transitions, fresh returns, continuous local animation, correct timers and low-current residency. Counters alone do not prove physical low-power drawing.\n"
end
