set pagination off

set $sm = &g_ps_hw6_owner_sm_probe
set $rt = &g_ps_hw6_rtos_probe
set $ui = &g_ps_ui_router_probe

printf "\n--- HW6 joystick wake threshold characterization ---\n"
if ($sm->magic != 0x48364653) || ($sm->version != 85)
  printf "Probe mismatch: expected owner magic/version 0x48364653/85. Reflash the exact ELF before interpreting any values.\n"
else
  printf "api rtos/owner/driver = %u / %u / %u\n", $rt->version, $sm->version, $sm->joystick_driver_api_version
  printf "UI page runtime class/lifecycle = %u / %u / %u\n", $ui->current_page, $rt->runtime_current_class, $rt->runtime_lifecycle
  printf "session start/active/complete/status/next pose/neutral pending = %u / %u / %u / 0x%x / %u / %u\n", $sm->joystick_wake_characterization_start_count, $sm->joystick_wake_characterization_active, $sm->joystick_wake_characterization_complete, $sm->joystick_wake_characterization_status, $sm->joystick_wake_characterization_pose, $sm->joystick_wake_characterization_neutral_pending
  printf "capture count/active/neutral/status/ticks = %u / %u / %u / 0x%x / %u..%u\n", $sm->joystick_wake_characterization_capture_count, $sm->joystick_wake_characterization_capture_active, $sm->joystick_wake_characterization_capture_neutral, $sm->joystick_wake_characterization_capture_status, $sm->joystick_wake_characterization_capture_start_tick, $sm->joystick_wake_characterization_capture_end_tick
  printf "capture stage/steps/next tick axis/boundary/trial/pending = %u / %u / %u / %u / %u / %u / %u\n", $sm->joystick_wake_characterization_capture_stage, $sm->joystick_wake_characterization_capture_step_count, $sm->joystick_wake_characterization_capture_next_tick, $sm->joystick_wake_characterization_capture_axis, $sm->joystick_wake_characterization_boundary_phase, $sm->joystick_wake_characterization_trial_threshold_code, $sm->joystick_wake_characterization_trial_pending
  printf "axis-isolated sensor config1 target/after X Y = 0x%x/0x%x 0x%x/0x%x\n", $sm->joystick_wake_characterization_x_sensor_config1_target, $sm->joystick_wake_characterization_x_sensor_config1_after, $sm->joystick_wake_characterization_y_sensor_config1_target, $sm->joystick_wake_characterization_y_sensor_config1_after
  printf "independent neutral returns count/target = %u / %u\n", $sm->joystick_wake_characterization_neutral_return_count, $sm->joystick_wake_characterization_neutral_return_target
  printf "neutral centroid X 0..4 = %d / %d / %d / %d / %d\n", $sm->joystick_wake_characterization_neutral_return_x[0], $sm->joystick_wake_characterization_neutral_return_x[1], $sm->joystick_wake_characterization_neutral_return_x[2], $sm->joystick_wake_characterization_neutral_return_x[3], $sm->joystick_wake_characterization_neutral_return_x[4]
  printf "neutral centroid Y 0..4 = %d / %d / %d / %d / %d\n", $sm->joystick_wake_characterization_neutral_return_y[0], $sm->joystick_wake_characterization_neutral_return_y[1], $sm->joystick_wake_characterization_neutral_return_y[2], $sm->joystick_wake_characterization_neutral_return_y[3], $sm->joystick_wake_characterization_neutral_return_y[4]
  printf "neutral peak abs X 0..4 = %u / %u / %u / %u / %u\n", $sm->joystick_wake_characterization_neutral_peak_x[0], $sm->joystick_wake_characterization_neutral_peak_x[1], $sm->joystick_wake_characterization_neutral_peak_x[2], $sm->joystick_wake_characterization_neutral_peak_x[3], $sm->joystick_wake_characterization_neutral_peak_x[4]
  printf "neutral peak abs Y 0..4 = %u / %u / %u / %u / %u\n", $sm->joystick_wake_characterization_neutral_peak_y[0], $sm->joystick_wake_characterization_neutral_peak_y[1], $sm->joystick_wake_characterization_neutral_peak_y[2], $sm->joystick_wake_characterization_neutral_peak_y[3], $sm->joystick_wake_characterization_neutral_peak_y[4]
  printf "neutral absolute bound X/Y = %u / %u counts\n", $sm->joystick_wake_characterization_neutral_bound_x_counts, $sm->joystick_wake_characterization_neutral_bound_y_counts
  printf "CENTER samples/stable raw X min/avg/max raw Y min/avg/max = %u / %u / %d / %d / %d / %d / %d / %d\n", $sm->joystick_wake_characterization_sample_count[0], ($sm->joystick_wake_characterization_sample_stable_mask >> 0) & 1, $sm->joystick_wake_characterization_raw_min_x[0], $sm->joystick_wake_characterization_raw_average_x[0], $sm->joystick_wake_characterization_raw_max_x[0], $sm->joystick_wake_characterization_raw_min_y[0], $sm->joystick_wake_characterization_raw_average_y[0], $sm->joystick_wake_characterization_raw_max_y[0]
  printf "CENTER max-assert X/Y trials X/Y boundary X/Y = %u / %u / %u / %u / %u / %u\n", $sm->joystick_wake_characterization_x_max_asserted_code[0], $sm->joystick_wake_characterization_y_max_asserted_code[0], $sm->joystick_wake_characterization_x_trial_count[0], $sm->joystick_wake_characterization_y_trial_count[0], ($sm->joystick_wake_characterization_x_boundary_valid_mask >> 0) & 1, ($sm->joystick_wake_characterization_y_boundary_valid_mask >> 0) & 1
  printf "UP samples/stable raw X min/avg/max raw Y min/avg/max = %u / %u / %d / %d / %d / %d / %d / %d\n", $sm->joystick_wake_characterization_sample_count[1], ($sm->joystick_wake_characterization_sample_stable_mask >> 1) & 1, $sm->joystick_wake_characterization_raw_min_x[1], $sm->joystick_wake_characterization_raw_average_x[1], $sm->joystick_wake_characterization_raw_max_x[1], $sm->joystick_wake_characterization_raw_min_y[1], $sm->joystick_wake_characterization_raw_average_y[1], $sm->joystick_wake_characterization_raw_max_y[1]
  printf "UP max-assert X/Y trials X/Y boundary X/Y = %u / %u / %u / %u / %u / %u\n", $sm->joystick_wake_characterization_x_max_asserted_code[1], $sm->joystick_wake_characterization_y_max_asserted_code[1], $sm->joystick_wake_characterization_x_trial_count[1], $sm->joystick_wake_characterization_y_trial_count[1], ($sm->joystick_wake_characterization_x_boundary_valid_mask >> 1) & 1, ($sm->joystick_wake_characterization_y_boundary_valid_mask >> 1) & 1
  printf "RIGHT samples/stable raw X min/avg/max raw Y min/avg/max = %u / %u / %d / %d / %d / %d / %d / %d\n", $sm->joystick_wake_characterization_sample_count[2], ($sm->joystick_wake_characterization_sample_stable_mask >> 2) & 1, $sm->joystick_wake_characterization_raw_min_x[2], $sm->joystick_wake_characterization_raw_average_x[2], $sm->joystick_wake_characterization_raw_max_x[2], $sm->joystick_wake_characterization_raw_min_y[2], $sm->joystick_wake_characterization_raw_average_y[2], $sm->joystick_wake_characterization_raw_max_y[2]
  printf "RIGHT max-assert X/Y trials X/Y boundary X/Y = %u / %u / %u / %u / %u / %u\n", $sm->joystick_wake_characterization_x_max_asserted_code[2], $sm->joystick_wake_characterization_y_max_asserted_code[2], $sm->joystick_wake_characterization_x_trial_count[2], $sm->joystick_wake_characterization_y_trial_count[2], ($sm->joystick_wake_characterization_x_boundary_valid_mask >> 2) & 1, ($sm->joystick_wake_characterization_y_boundary_valid_mask >> 2) & 1
  printf "DOWN samples/stable raw X min/avg/max raw Y min/avg/max = %u / %u / %d / %d / %d / %d / %d / %d\n", $sm->joystick_wake_characterization_sample_count[3], ($sm->joystick_wake_characterization_sample_stable_mask >> 3) & 1, $sm->joystick_wake_characterization_raw_min_x[3], $sm->joystick_wake_characterization_raw_average_x[3], $sm->joystick_wake_characterization_raw_max_x[3], $sm->joystick_wake_characterization_raw_min_y[3], $sm->joystick_wake_characterization_raw_average_y[3], $sm->joystick_wake_characterization_raw_max_y[3]
  printf "DOWN max-assert X/Y trials X/Y boundary X/Y = %u / %u / %u / %u / %u / %u\n", $sm->joystick_wake_characterization_x_max_asserted_code[3], $sm->joystick_wake_characterization_y_max_asserted_code[3], $sm->joystick_wake_characterization_x_trial_count[3], $sm->joystick_wake_characterization_y_trial_count[3], ($sm->joystick_wake_characterization_x_boundary_valid_mask >> 3) & 1, ($sm->joystick_wake_characterization_y_boundary_valid_mask >> 3) & 1
  printf "LEFT samples/stable raw X min/avg/max raw Y min/avg/max = %u / %u / %d / %d / %d / %d / %d / %d\n", $sm->joystick_wake_characterization_sample_count[4], ($sm->joystick_wake_characterization_sample_stable_mask >> 4) & 1, $sm->joystick_wake_characterization_raw_min_x[4], $sm->joystick_wake_characterization_raw_average_x[4], $sm->joystick_wake_characterization_raw_max_x[4], $sm->joystick_wake_characterization_raw_min_y[4], $sm->joystick_wake_characterization_raw_average_y[4], $sm->joystick_wake_characterization_raw_max_y[4]
  printf "LEFT max-assert X/Y trials X/Y boundary X/Y = %u / %u / %u / %u / %u / %u\n", $sm->joystick_wake_characterization_x_max_asserted_code[4], $sm->joystick_wake_characterization_y_max_asserted_code[4], $sm->joystick_wake_characterization_x_trial_count[4], $sm->joystick_wake_characterization_y_trial_count[4], ($sm->joystick_wake_characterization_x_boundary_valid_mask >> 4) & 1, ($sm->joystick_wake_characterization_y_boundary_valid_mask >> 4) & 1
  printf "stable/boundary X/boundary Y masks = 0x%x / 0x%x / 0x%x (complete each=0x1f)\n", $sm->joystick_wake_characterization_sample_stable_mask, $sm->joystick_wake_characterization_x_boundary_valid_mask, $sm->joystick_wake_characterization_y_boundary_valid_mask
  printf "hardware-ceiling X/Y masks = 0x%x / 0x%x\n", $sm->joystick_wake_characterization_x_ceiling_mask, $sm->joystick_wake_characterization_y_ceiling_mask
  printf "neutral-safe candidate X/Y = %u / %u\n", $sm->joystick_wake_characterization_candidate_x_code, $sm->joystick_wake_characterization_candidate_y_code
  printf "direction coverage UP/RIGHT/DOWN/LEFT mask = 0x%x (complete=0xf)\n", $sm->joystick_wake_characterization_direction_coverage_mask
  printf "one neutral-safe X/Y pair feasible = %u\n", $sm->joystick_wake_characterization_feasible
  printf "last driver/HAL/error = 0x%x / 0x%x / 0x%x\n", $sm->joystick_wake_characterization_last_driver_status, $sm->joystick_wake_characterization_last_hal_status, $sm->joystick_wake_characterization_last_hal_error
  printf "production profile remains status/reason threshold X/Y = 0x%x / %u / %u / %u\n", $sm->joystick_wake_profile_status, $sm->joystick_wake_profile_reason, $sm->joystick_wake_field_threshold_x_code, $sm->joystick_wake_field_threshold_y_code
  printf "capture stages: IDLE=0 PREPARE=1 SAMPLE=2 BOUNDARY_X=3 BOUNDARY_Y=4 COMPLETE=5 ERROR=6; axes NONE/X/Y=0/1/2\n"
  printf "boundary phases: IDLE=0 LOW=1 LOW_AGAIN=2 HIGH=3 HIGH_AGAIN=4 BINARY=5 VERIFY_LOW=6 VERIFY_HIGH=7 COMPLETE=8\n"
  printf "expected isolated Sensor_Config_1 target/after: X=0x14/0x14 and Y=0x24/0x24 for the current 20 ms period\n"
  printf "Interpretation: the five neutral bounds come from captures made after each physical release, not calibration history. Max-assert is the highest real TMAG code that asserted at that pose; code 127 with a ceiling bit is a valid hardware-censored result. Feasible=1 means the neutral-safe candidate also covers all four directions.\n"
end
printf "--- end joystick wake threshold characterization ---\n"
