set pagination off
printf "--- HW6 input lifecycle diagnostic ---\n"
printf "api rtos/buttons/ui = %u / %u / %u\n", g_ps_hw6_rtos_probe.version, g_ps_input_buttons_probe.api_version, g_ps_ui_router_probe.api_version
printf "ui page/status button event/count joystick event/count = %u / 0x%x / %u / %u / %u / %u\n", g_ps_ui_router_probe.current_page, g_ps_ui_router_probe.last_status, g_ps_ui_router_probe.last_button_event, g_ps_ui_router_probe.button_event_count, g_ps_ui_router_probe.last_joystick_event, g_ps_ui_router_probe.joystick_event_count
printf "ui joystick candidate/resolved updates = 0x%x / 0x%x / %u\n", g_ps_ui_router_probe.joystick_candidate_direction_mask, g_ps_ui_router_probe.joystick_resolved_direction_mask, g_ps_ui_router_probe.joystick_state_update_count
printf "input policy event/deliver/suppress target/reason/status = %u / %u / %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.input_policy_event_count, g_ps_hw6_rtos_probe.input_policy_deliver_count, g_ps_hw6_rtos_probe.input_policy_suppress_count, g_ps_hw6_rtos_probe.input_policy_last_target, g_ps_hw6_rtos_probe.input_policy_last_reason, g_ps_hw6_rtos_probe.input_policy_last_status
printf "input policy last event/source/mask/tick = %u / %u / 0x%x / %u\n", g_ps_hw6_rtos_probe.input_policy_last_event, g_ps_hw6_rtos_probe.input_policy_last_button_id, g_ps_hw6_rtos_probe.input_policy_last_mask, g_ps_hw6_rtos_probe.input_policy_last_timestamp
printf "button lifecycle press/release/hold/repeat pending = %u / %u / %u / %u / 0x%x\n", g_ps_input_buttons_probe.logical_press_count, g_ps_input_buttons_probe.logical_release_count, g_ps_input_buttons_probe.logical_long_count, g_ps_input_buttons_probe.logical_repeat_count, g_ps_input_buttons_probe.pending_mask
printf "button pending press/release/hold/repeat = 0x%x / 0x%x / 0x%x / 0x%x\n", g_ps_input_buttons_probe.logical_press_pending_mask, g_ps_input_buttons_probe.logical_release_pending_mask, g_ps_input_buttons_probe.logical_long_pending_mask, g_ps_input_buttons_probe.logical_repeat_pending_mask
printf "joystick lifecycle activate/release/hold/repeat/switch/drop = %u / %u / %u / %u / %u / %u\n", g_ps_hw6_rtos_probe.joystick_logical_activation_count, g_ps_hw6_rtos_probe.joystick_logical_release_count, g_ps_hw6_rtos_probe.joystick_logical_hold_count, g_ps_hw6_rtos_probe.joystick_logical_repeat_count, g_ps_hw6_rtos_probe.joystick_logical_switch_count, g_ps_hw6_rtos_probe.joystick_logical_drop_count
printf "joystick active/source last event/candidate/resolved/direction/source/status = 0x%x / %u / %u / 0x%x / 0x%x / 0x%x / %u / 0x%x\n", g_ps_hw6_rtos_probe.joystick_logical_active_direction_mask, g_ps_hw6_rtos_probe.joystick_logical_active_source, g_ps_hw6_rtos_probe.joystick_logical_last_event, g_ps_hw6_rtos_probe.joystick_logical_last_candidate_mask, g_ps_hw6_rtos_probe.joystick_logical_last_resolved_mask, g_ps_hw6_rtos_probe.joystick_logical_last_direction_mask, g_ps_hw6_rtos_probe.joystick_logical_last_source, g_ps_hw6_rtos_probe.joystick_logical_last_status
printf "display page/render primitive STOP2 entries/block/pending = %u / %u / %u / %u / 0x%x / 0x%x\n", g_ps_hw6_owner_probe.display_ui_page, g_ps_hw6_owner_probe.display_ui_render_count, g_ps_hw6_owner_probe.display_ui_primitive_id, g_ps_hw6_rtos_probe.stop2_auto_entry_count, g_ps_hw6_rtos_probe.stop2_auto_blocker_mask, g_ps_hw6_rtos_probe.stop2_auto_pending_mask
printf "expected diagnostic: UI page is INPUT TEST, use any controls freely, source/event labels match what you do, pending masks drain to zero, drops stay zero, STOP2 continues when idle\n"
printf "logical IDs: A/B/L/R/START=1/2/3/4/5; JOY LEFT/RIGHT/UP/DOWN=6/7/8/9; diagonals UL/UR/DL/DR=10/11/12/13; events PRESS/RELEASE/HOLD/REPEAT=1/2/3/4\n"
printf "--- end input lifecycle diagnostic ---\n"
