set pagination off
printf "--- HW6 STATE sampled-SFX proof ---\n"
printf "loader api/load/status/reason package/resident/chunks/scenes = %u / %u / 0x%x / %u / %u / %u / %u / %u\n", g_ps_egg_state_loader_probe.api_version, g_ps_egg_state_loader_probe.load_count, g_ps_egg_state_loader_probe.last_status, g_ps_egg_state_loader_probe.reason, g_ps_egg_state_loader_probe.package_size, g_ps_egg_state_loader_probe.resident_size, g_ps_egg_state_loader_probe.chunk_count, g_ps_egg_state_loader_probe.scene_count
printf "audio chunks asset/bank/cue assets/cues/adpcm/package-backed = %u / %u / %u / %u / %u / %u / %u\n", g_ps_egg_state_loader_probe.audio_asset_chunk_index, g_ps_egg_state_loader_probe.audio_bank_chunk_index, g_ps_egg_state_loader_probe.audio_cue_chunk_index, g_ps_egg_state_loader_probe.audio_asset_count, g_ps_egg_state_loader_probe.audio_cue_count, g_ps_egg_state_loader_probe.audio_adpcm_bytes, g_ps_egg_state_loader_probe.audio_package_backed
printf "scene api/active/status action errors SFX commit/take/cue = %u / %u / 0x%x / %u / %u / %u / %u\n", g_ps_scene_runtime_probe.api_version, g_ps_scene_runtime_probe.active, g_ps_scene_runtime_probe.last_status, g_ps_scene_runtime_probe.action_error_count, g_ps_scene_runtime_probe.sfx_action_commit_count, g_ps_scene_runtime_probe.sfx_request_take_count, g_ps_scene_runtime_probe.last_sfx_cue_index
printf "RTOS api dispatch/send owner/status clock req/release cue = %u / %u / 0x%x / %u / 0x%x / 0x%x / 0x%x / %u\n", g_ps_hw6_rtos_probe.version, g_ps_hw6_rtos_probe.audio_sfx_dispatch_count, g_ps_hw6_rtos_probe.audio_sfx_send_status, g_ps_hw6_rtos_probe.audio_sfx_owner_count, g_ps_hw6_rtos_probe.audio_sfx_owner_status, g_ps_hw6_rtos_probe.audio_sfx_clock_request_status, g_ps_hw6_rtos_probe.audio_sfx_clock_release_status, g_ps_hw6_rtos_probe.audio_sfx_last_cue_index
printf "clock grant status/stage required/managed/readback PLL2 ready/outputs SAI Hz = 0x%x / %u / 0x%x / 0x%x / 0x%x / %u / 0x%x / %u\n", g_ps_hw6_rtos_probe.audio_sfx_grant_policy_status, g_ps_hw6_rtos_probe.audio_sfx_grant_policy_stage, g_ps_hw6_rtos_probe.audio_sfx_grant_required_domains, g_ps_hw6_rtos_probe.audio_sfx_grant_managed_domains, g_ps_hw6_rtos_probe.audio_sfx_grant_readback_domains, g_ps_hw6_rtos_probe.audio_sfx_grant_pll2_ready, g_ps_hw6_rtos_probe.audio_sfx_grant_pll2_outputs, g_ps_hw6_rtos_probe.audio_sfx_grant_sai_kernel_hz
printf "PLL2 post-STOP pending/mask/invalidate/rearm attempt/success/status fast-path = %u / 0x%x / %u / %u / %u / 0x%x / %u\n", g_ps_hw6_clock_policy_probe.pll2_post_stop_rearm_pending, g_ps_hw6_clock_policy_probe.pll2_post_stop_rearm_pending_domain_mask, g_ps_hw6_clock_policy_probe.pll2_post_stop_invalidate_count, g_ps_hw6_clock_policy_probe.pll2_post_stop_rearm_attempt_count, g_ps_hw6_clock_policy_probe.pll2_post_stop_rearm_success_count, g_ps_hw6_clock_policy_probe.pll2_post_stop_rearm_status, g_ps_hw6_clock_policy_probe.pll2_fast_path_count
printf "post-STOP voltage VOSR/SVMSR before status after = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", g_ps_hw6_clock_policy_probe.post_stop_vosr_before, g_ps_hw6_clock_policy_probe.post_stop_svmsr_before, g_ps_hw6_clock_policy_probe.post_stop_voltage_scale_status, g_ps_hw6_clock_policy_probe.post_stop_vosr_after, g_ps_hw6_clock_policy_probe.post_stop_svmsr_after
printf "SAI post-STOP mux handoff count/success/status = %u / %u / 0x%x\n", g_ps_hw6_clock_policy_probe.sai_mux_handoff_count, g_ps_hw6_clock_policy_probe.sai_mux_handoff_success_count, g_ps_hw6_clock_policy_probe.sai_mux_handoff_status
printf "SAI restart park gate/reset/source/kernel restore gate/reset/source/kernel = %u/%u/0x%x/%u %u/%u/0x%x/%u\n", g_ps_hw6_clock_policy_probe.sai_mux_park_clock_enabled, g_ps_hw6_clock_policy_probe.sai_mux_park_reset_asserted, g_ps_hw6_clock_policy_probe.sai_mux_park_source, g_ps_hw6_clock_policy_probe.sai_mux_park_kernel_hz, g_ps_hw6_clock_policy_probe.sai_mux_restore_clock_enabled, g_ps_hw6_clock_policy_probe.sai_mux_restore_reset_asserted, g_ps_hw6_clock_policy_probe.sai_mux_restore_source, g_ps_hw6_clock_policy_probe.sai_mux_restore_kernel_hz
printf "power SAI active/gate/reset on/off/reset-count/epoch/status = %u / %u / %u / %u / %u / %u / %u / 0x%x\n", g_ps_hw6_clock_policy_probe.sai_domain_active, g_ps_hw6_clock_policy_probe.sai_clock_enabled, g_ps_hw6_clock_policy_probe.sai_reset_asserted, g_ps_hw6_clock_policy_probe.sai_domain_on_count, g_ps_hw6_clock_policy_probe.sai_domain_off_count, g_ps_hw6_clock_policy_probe.sai_reset_count, g_ps_hw6_clock_policy_probe.sai_grant_epoch, g_ps_hw6_clock_policy_probe.sai_domain_last_status
printf "STOP2 clock prepare owner/status count/status/physical/fail = 0x%x / %u / 0x%x / %u / 0x%x\n", g_ps_hw6_owner_sm_probe.stop2_clock_prepare_status, g_ps_hw6_clock_policy_probe.stop2_prepare_count, g_ps_hw6_clock_policy_probe.stop2_prepare_status, g_ps_hw6_clock_policy_probe.stop2_physical_ready, g_ps_hw6_clock_policy_probe.stop2_physical_failure_mask
printf "owner api request/cue/asset priority/volume adpcm/samples/blocks = %u / %u / %u / %u / %u / %u / %u / %u / %u\n", g_ps_hw6_owner_probe.version, g_ps_hw6_owner_probe.audio_sfx_request_count, g_ps_hw6_owner_probe.audio_sfx_cue_index, g_ps_hw6_owner_probe.audio_sfx_asset_index, g_ps_hw6_owner_probe.audio_sfx_priority, g_ps_hw6_owner_probe.audio_sfx_volume, g_ps_hw6_owner_probe.audio_sfx_adpcm_bytes, g_ps_hw6_owner_probe.audio_sfx_sample_count, g_ps_hw6_owner_probe.audio_sfx_block_count
printf "post-STOP audio mark/pending/recovery attempt/success/status = %u / %u / %u / %u / 0x%x\n", g_ps_hw6_owner_probe.audio_post_stop_resume_mark_count, g_ps_hw6_owner_probe.audio_post_stop_recovery_pending, g_ps_hw6_owner_probe.audio_post_stop_recovery_attempt_count, g_ps_hw6_owner_probe.audio_post_stop_recovery_success_count, g_ps_hw6_owner_probe.audio_post_stop_recovery_status
printf "ThreadX pool available before/after fragments = %u / %u / %u\n", g_ps_hw6_rtos_probe.pool_available_before, g_ps_hw6_rtos_probe.pool_available_after, g_ps_hw6_rtos_probe.pool_fragments_after
printf "audio stack bytes/start/end/ptr/lower margin = %u / 0x%x / 0x%x / 0x%x / %u\n", g_ps_hw6_rtos_probe.thread_stack_config_bytes[1], ps_threads[1].tx_thread_stack_start, ps_threads[1].tx_thread_stack_end, ps_threads[1].tx_thread_stack_ptr, (unsigned int)ps_threads[1].tx_thread_stack_ptr - (unsigned int)ps_threads[1].tx_thread_stack_start
printf "decode/status samples rearm/start/wait/callback/stop complete/success = 0x%x / %u / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / %u / %u\n", g_ps_hw6_owner_probe.audio_sfx_decode_status, g_ps_hw6_owner_probe.audio_sfx_decoded_samples, g_ps_hw6_owner_probe.audio_rearm_status, g_ps_hw6_owner_probe.audio_start_status, g_ps_hw6_owner_probe.audio_completion_wait_status, g_ps_hw6_owner_probe.audio_completion_callback_status, g_ps_hw6_owner_probe.audio_stop_status, g_ps_hw6_owner_probe.audio_complete, g_ps_hw6_owner_probe.audio_success
printf "SFX stream frames/half refills callbacks half/full underrun silence decoded/wait/status = %u / %u / %u / %u / %u / %u / %u / %u / 0x%x / 0x%x\n", g_ps_hw6_owner_probe.audio_sfx_stream_buffer_frames, g_ps_hw6_owner_probe.audio_sfx_stream_half_frames, g_ps_hw6_owner_probe.audio_sfx_stream_refill_count, g_ps_hw6_owner_probe.audio_sfx_stream_first_half_callback_count, g_ps_hw6_owner_probe.audio_sfx_stream_second_half_callback_count, g_ps_hw6_owner_probe.audio_sfx_stream_underrun_count, g_ps_hw6_owner_probe.audio_sfx_stream_silence_frames, g_ps_hw6_owner_probe.audio_sfx_decoded_samples, g_ps_hw6_owner_probe.audio_sfx_stream_wait_status, g_ps_hw6_owner_probe.audio_sfx_stream_status
printf "SFX wait preempt/system/current/expected-audio = 0x%x / 0x%x / 0x%x / 0x%x\n", g_ps_hw6_owner_probe.audio_sfx_stream_wait_preempt_disable_before, g_ps_hw6_owner_probe.audio_sfx_stream_wait_system_state_before, g_ps_hw6_owner_probe.audio_sfx_stream_wait_current_thread_before, &ps_threads[1]
printf "SFX source package/window reads/failures/bytes/status = %u / %u / %u / %u / 0x%x\n", g_ps_hw6_owner_probe.audio_sfx_package_backed, g_ps_hw6_owner_probe.audio_sfx_source_window_read_count, g_ps_hw6_owner_probe.audio_sfx_source_window_failure_count, g_ps_hw6_owner_probe.audio_sfx_source_window_bytes, g_ps_hw6_owner_probe.audio_sfx_source_window_status
printf "SFX prefetch start/complete/miss/pending/cleanup = %u / %u / %u / %u / 0x%x\n", g_ps_hw6_owner_probe.audio_sfx_source_prefetch_start_count, g_ps_hw6_owner_probe.audio_sfx_source_prefetch_complete_count, g_ps_hw6_owner_probe.audio_sfx_source_prefetch_miss_count, g_ps_hw6_owner_probe.audio_sfx_source_prefetch_pending, g_ps_hw6_owner_probe.audio_sfx_source_prefetch_cleanup_status
printf "pre-cleanup IRQ/tx callback/error callback = %u / %u / %u\n", g_ps_hw6_owner_probe.audio_pre_cleanup_dma_irq_delta, g_ps_hw6_owner_probe.audio_pre_cleanup_tx_callback_delta, g_ps_hw6_owner_probe.audio_pre_cleanup_error_callback_delta
printf "pre-cleanup SAI kernel/state/error CR1/CR2/FRCR/SLOTR/IMR/SR/GCR = %u / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", g_ps_hw6_owner_probe.audio_pre_cleanup_sai_kernel_hz, g_ps_hw6_owner_probe.audio_pre_cleanup_sai_state, g_ps_hw6_owner_probe.audio_pre_cleanup_sai_error, g_ps_hw6_owner_probe.audio_pre_cleanup_sai_cr1, g_ps_hw6_owner_probe.audio_pre_cleanup_sai_cr2, g_ps_hw6_owner_probe.audio_pre_cleanup_sai_frcr, g_ps_hw6_owner_probe.audio_pre_cleanup_sai_slotr, g_ps_hw6_owner_probe.audio_pre_cleanup_sai_imr, g_ps_hw6_owner_probe.audio_pre_cleanup_sai_sr, g_ps_hw6_owner_probe.audio_pre_cleanup_sai_gcr
printf "pre-cleanup DMA state/error CCR/CSR/CBR1/CTR1/CTR2/CSAR/CDAR/CLLR = 0x%x / 0x%x / 0x%x / 0x%x / %u / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", g_ps_hw6_owner_probe.audio_pre_cleanup_dma_state, g_ps_hw6_owner_probe.audio_pre_cleanup_dma_error, g_ps_hw6_owner_probe.audio_pre_cleanup_dma_ccr, g_ps_hw6_owner_probe.audio_pre_cleanup_dma_csr, g_ps_hw6_owner_probe.audio_pre_cleanup_dma_cbr1, g_ps_hw6_owner_probe.audio_pre_cleanup_dma_ctr1, g_ps_hw6_owner_probe.audio_pre_cleanup_dma_ctr2, g_ps_hw6_owner_probe.audio_pre_cleanup_dma_csar, g_ps_hw6_owner_probe.audio_pre_cleanup_dma_cdar, g_ps_hw6_owner_probe.audio_pre_cleanup_dma_cllr
set $ok = &g_ps_hw6_rtos_probe.audio_sfx_first_success_capture
set $fail = &g_ps_hw6_rtos_probe.audio_sfx_first_post_stop_failure_capture
printf "A/B success valid/tick/STOP2/status apply before/after = %u / %u / %u / 0x%x / %u / %u\n", $ok->valid, $ok->capture_tick, $ok->stop2_entry_count, $ok->owner_status, $ok->clock_apply_count_before, $ok->clock_apply_count_after
printf "A/B success PLL2 on/off before/after = %u/%u / %u/%u\n", $ok->clock_pll2_on_count_before, $ok->clock_pll2_on_count_after, $ok->clock_pll2_off_count_before, $ok->clock_pll2_off_count_after
printf "A/B success grant stat/stage req/managed/readback PLL2/outputs/SAI = 0x%x / %u / 0x%x / 0x%x / 0x%x / %u / 0x%x / %u\n", $ok->grant_policy_status, $ok->grant_policy_stage, $ok->grant_required_domains, $ok->grant_managed_domains, $ok->grant_readback_domains, $ok->grant_pll2_ready, $ok->grant_pll2_outputs, $ok->grant_sai_kernel_hz
printf "A/B success final active/caps req/managed/readback PLL2/outputs/SAI = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / %u / 0x%x / %u\n", $ok->final_requester_active_mask, $ok->final_aggregated_capabilities, $ok->final_required_domains, $ok->final_managed_domains, $ok->final_readback_domains, $ok->final_pll2_ready, $ok->final_pll2_outputs, $ok->final_sai_kernel_hz
printf "A/B success audio kernel start/end rearm/start/wait/callback/stop IRQ/txcb/errcb = %u / %u / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / %u / %u / %u\n", $ok->audio_sai_kernel_hz_start, $ok->audio_sai_kernel_hz_end, $ok->audio_rearm_status, $ok->audio_start_status, $ok->audio_wait_status, $ok->audio_callback_status, $ok->audio_stop_status, $ok->dma_irq_delta, $ok->tx_callback_delta, $ok->error_callback_delta
printf "A/B success SAI state/error CR1/CR2/FRCR/SLOTR/IMR/SR/GCR = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", $ok->sai_state, $ok->sai_error, $ok->sai_cr1, $ok->sai_cr2, $ok->sai_frcr, $ok->sai_slotr, $ok->sai_imr, $ok->sai_sr, $ok->sai_gcr
printf "A/B success DMA state/error CCR/CSR/CBR1/CTR1/CTR2/CSAR/CDAR/CLLR = 0x%x / 0x%x / 0x%x / 0x%x / %u / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", $ok->dma_state, $ok->dma_error, $ok->dma_ccr, $ok->dma_csr, $ok->dma_cbr1, $ok->dma_ctr1, $ok->dma_ctr2, $ok->dma_csar, $ok->dma_cdar, $ok->dma_cllr
printf "A/B success RCC AHB1/AHB2/APB2/RST/SM/CCIPR2 = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", $ok->rcc_ahb1enr, $ok->rcc_ahb2enr1, $ok->rcc_apb2enr, $ok->rcc_apb2rstr, $ok->rcc_apb2smenr, $ok->rcc_ccipr2
printf "A/B success SAI pins PA8 mode/AF PA10 mode/AF PB9 mode/AF = %u/%u / %u/%u / %u/%u\n", ($ok->gpioa_moder >> 16) & 3, $ok->gpioa_afrh & 15, ($ok->gpioa_moder >> 20) & 3, ($ok->gpioa_afrh >> 8) & 15, ($ok->gpiob_moder >> 18) & 3, ($ok->gpiob_afrh >> 4) & 15
printf "A/B failure valid/tick/STOP2/status apply before/after = %u / %u / %u / 0x%x / %u / %u\n", $fail->valid, $fail->capture_tick, $fail->stop2_entry_count, $fail->owner_status, $fail->clock_apply_count_before, $fail->clock_apply_count_after
printf "A/B failure PLL2 on/off before/after = %u/%u / %u/%u\n", $fail->clock_pll2_on_count_before, $fail->clock_pll2_on_count_after, $fail->clock_pll2_off_count_before, $fail->clock_pll2_off_count_after
printf "A/B failure grant stat/stage req/managed/readback PLL2/outputs/SAI = 0x%x / %u / 0x%x / 0x%x / 0x%x / %u / 0x%x / %u\n", $fail->grant_policy_status, $fail->grant_policy_stage, $fail->grant_required_domains, $fail->grant_managed_domains, $fail->grant_readback_domains, $fail->grant_pll2_ready, $fail->grant_pll2_outputs, $fail->grant_sai_kernel_hz
printf "A/B failure final active/caps req/managed/readback PLL2/outputs/SAI = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / %u / 0x%x / %u\n", $fail->final_requester_active_mask, $fail->final_aggregated_capabilities, $fail->final_required_domains, $fail->final_managed_domains, $fail->final_readback_domains, $fail->final_pll2_ready, $fail->final_pll2_outputs, $fail->final_sai_kernel_hz
printf "A/B failure audio kernel start/end rearm/start/wait/callback/stop IRQ/txcb/errcb = %u / %u / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / %u / %u / %u\n", $fail->audio_sai_kernel_hz_start, $fail->audio_sai_kernel_hz_end, $fail->audio_rearm_status, $fail->audio_start_status, $fail->audio_wait_status, $fail->audio_callback_status, $fail->audio_stop_status, $fail->dma_irq_delta, $fail->tx_callback_delta, $fail->error_callback_delta
printf "A/B failure SAI state/error CR1/CR2/FRCR/SLOTR/IMR/SR/GCR = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", $fail->sai_state, $fail->sai_error, $fail->sai_cr1, $fail->sai_cr2, $fail->sai_frcr, $fail->sai_slotr, $fail->sai_imr, $fail->sai_sr, $fail->sai_gcr
printf "A/B failure DMA state/error CCR/CSR/CBR1/CTR1/CTR2/CSAR/CDAR/CLLR = 0x%x / 0x%x / 0x%x / 0x%x / %u / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", $fail->dma_state, $fail->dma_error, $fail->dma_ccr, $fail->dma_csr, $fail->dma_cbr1, $fail->dma_ctr1, $fail->dma_ctr2, $fail->dma_csar, $fail->dma_cdar, $fail->dma_cllr
printf "A/B failure RCC AHB1/AHB2/APB2/RST/SM/CCIPR2 = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", $fail->rcc_ahb1enr, $fail->rcc_ahb2enr1, $fail->rcc_apb2enr, $fail->rcc_apb2rstr, $fail->rcc_apb2smenr, $fail->rcc_ccipr2
printf "A/B failure SAI pins PA8 mode/AF PA10 mode/AF PB9 mode/AF = %u/%u / %u/%u / %u/%u\n", ($fail->gpioa_moder >> 16) & 3, $fail->gpioa_afrh & 15, ($fail->gpioa_moder >> 20) & 3, ($fail->gpioa_afrh >> 8) & 15, ($fail->gpiob_moder >> 18) & 3, ($fail->gpiob_afrh >> 4) & 15
printf "STOP2 SAI-port MODER before/after A/B = 0x%x/0x%x / 0x%x/0x%x\n", $fail->stop2_gpioa_moder_before, $fail->stop2_gpioa_moder_after, $fail->stop2_gpiob_moder_before, $fail->stop2_gpiob_moder_after
printf "audio/speaker states STOP2 entries/block = %u / %u / %u / 0x%x\n", g_ps_hw6_owner_sm_probe.current_state[3], g_ps_hw6_owner_sm_probe.current_state[4], g_ps_hw6_rtos_probe.stop2_auto_entry_count, g_ps_hw6_rtos_probe.stop2_auto_blocker_mask
printf "expected clock grant: required/managed/readback=0x6/0x6/0x6 with SAI Hz=4096000; package SFX holds PLL2P+Q through playback and post-STOP DMA reaches CBR1=0 with IRQ/tx callback >=1\n"
printf "expected power ownership: completed-playback RCC capture has SAI1EN with reset clear; idle power SAI active/gate/reset=0/0/0 with epoch advanced; STOP2 prepare owner/status=0/0 physical=1 fail=0\n"
printf "diagnostic split: completed DMA has IRQ and tx callback deltas >=1 with CBR1=0; stalled SAI requests retain CBR1>0 before cleanup; IRQ without callback isolates HAL callback dispatch\n"
printf "expected PLL2 epoch: after STOP invalidate>=1; OSPI may clear bit 0x2, then SAI clears bit 0x4; mux handoff count=success>=1/status=0 with park gate/reset=0/0 on HSI and restore gate/reset=0/0 on PLL2\n"
printf "expected A/B: success valid=1 and post-STOP failure valid=0; final domains retain SAI while playback is active\n"
printf "expected prerequisites: the first post-STOP PLL2 request increments rearm success; later same-epoch requests may use the fast path; RCC APB2ENR includes SAI1EN with reset clear; PA8/PA10/PB9 mode/AF are 2/13\n"
printf "expected playback: after STOP mark>=1, recovery attempt=success, pending=0/status=0; every completed DMA has IRQ/tx callback>=1 and CBR1=0\n"
printf "expected package-backed playback: loader resident < package, audio package-backed=1, source windows>=1 with failures=0/status=0, and stream underrun=0\n"
printf "expected prefetch: start=complete, miss=0, pending=0, cleanup=0; completed windows are fetched by thStorage before the decoder crosses each boundary\n"
printf "--- end HW6 STATE sampled-SFX proof ---\n"
