set pagination off
printf "--- HW6 STATE sampled-SFX proof ---\n"
printf "loader api/load/status/reason package/chunks/scenes = %u / %u / 0x%x / %u / %u / %u / %u\n", g_ps_egg_state_loader_probe.api_version, g_ps_egg_state_loader_probe.load_count, g_ps_egg_state_loader_probe.last_status, g_ps_egg_state_loader_probe.reason, g_ps_egg_state_loader_probe.package_size, g_ps_egg_state_loader_probe.chunk_count, g_ps_egg_state_loader_probe.scene_count
printf "audio chunks asset/bank/cue assets/cues/adpcm = %u / %u / %u / %u / %u / %u\n", g_ps_egg_state_loader_probe.audio_asset_chunk_index, g_ps_egg_state_loader_probe.audio_bank_chunk_index, g_ps_egg_state_loader_probe.audio_cue_chunk_index, g_ps_egg_state_loader_probe.audio_asset_count, g_ps_egg_state_loader_probe.audio_cue_count, g_ps_egg_state_loader_probe.audio_adpcm_bytes
printf "scene api/active/status action errors SFX commit/take/cue = %u / %u / 0x%x / %u / %u / %u / %u\n", g_ps_scene_runtime_probe.api_version, g_ps_scene_runtime_probe.active, g_ps_scene_runtime_probe.last_status, g_ps_scene_runtime_probe.action_error_count, g_ps_scene_runtime_probe.sfx_action_commit_count, g_ps_scene_runtime_probe.sfx_request_take_count, g_ps_scene_runtime_probe.last_sfx_cue_index
printf "RTOS api dispatch/send owner/status clock req/release cue = %u / %u / 0x%x / %u / 0x%x / 0x%x / 0x%x / %u\n", g_ps_hw6_rtos_probe.version, g_ps_hw6_rtos_probe.audio_sfx_dispatch_count, g_ps_hw6_rtos_probe.audio_sfx_send_status, g_ps_hw6_rtos_probe.audio_sfx_owner_count, g_ps_hw6_rtos_probe.audio_sfx_owner_status, g_ps_hw6_rtos_probe.audio_sfx_clock_request_status, g_ps_hw6_rtos_probe.audio_sfx_clock_release_status, g_ps_hw6_rtos_probe.audio_sfx_last_cue_index
printf "owner api request/cue/asset priority/volume adpcm/samples/blocks = %u / %u / %u / %u / %u / %u / %u / %u / %u\n", g_ps_hw6_owner_probe.version, g_ps_hw6_owner_probe.audio_sfx_request_count, g_ps_hw6_owner_probe.audio_sfx_cue_index, g_ps_hw6_owner_probe.audio_sfx_asset_index, g_ps_hw6_owner_probe.audio_sfx_priority, g_ps_hw6_owner_probe.audio_sfx_volume, g_ps_hw6_owner_probe.audio_sfx_adpcm_bytes, g_ps_hw6_owner_probe.audio_sfx_sample_count, g_ps_hw6_owner_probe.audio_sfx_block_count
printf "decode/status samples start/stop complete/success = 0x%x / %u / 0x%x / 0x%x / %u / %u\n", g_ps_hw6_owner_probe.audio_sfx_decode_status, g_ps_hw6_owner_probe.audio_sfx_decoded_samples, g_ps_hw6_owner_probe.audio_start_status, g_ps_hw6_owner_probe.audio_stop_status, g_ps_hw6_owner_probe.audio_complete, g_ps_hw6_owner_probe.audio_success
printf "audio/speaker states STOP2 entries/block = %u / %u / %u / 0x%x\n", g_ps_hw6_owner_sm_probe.current_state[3], g_ps_hw6_owner_sm_probe.current_state[4], g_ps_hw6_rtos_probe.stop2_auto_entry_count, g_ps_hw6_rtos_probe.stop2_auto_blocker_mask
printf "expected: loader=13/>=1/0/0 package=6124/15/2 audio chunks=12/13/14 assets/cues/adpcm=1/1/1340; scene=17/1/0 errors=0 SFX commit/take>=1 cue=0; RTOS=71 dispatch/owner>=1 all statuses=0; owner=34 cue/asset=0/0 priority/volume=96/224 samples/blocks=2560/10 decode=0 decoded=2560 start/stop=0/0 complete/success=1/1; STOP2 entries advance after playback\n"
printf "--- end HW6 STATE sampled-SFX proof ---\n"
