set pagination off
printf "--- HW6 STATE_SCENE reactive loop ---\n"
printf "package source api/override/selected/resolve/success/status/reason/bytes = %u / %u / %u / %u / %u / 0x%x / %u / %u\n", g_ps_package_source_probe.api_version, g_ps_package_source_override, g_ps_package_source_probe.selected_source, g_ps_package_source_probe.resolve_count, g_ps_package_source_probe.success_count, g_ps_package_source_probe.last_status, g_ps_package_source_probe.reason, g_ps_package_source_probe.package_size
printf "egg loader api/load/status/reason = %u / %u / 0x%x / %u\n", g_ps_egg_state_loader_probe.api_version, g_ps_egg_state_loader_probe.load_count, g_ps_egg_state_loader_probe.last_status, g_ps_egg_state_loader_probe.reason
printf "egg HASH api/count/status HAL/error bytes/ticks = %u / %u / 0x%x / 0x%x / 0x%x / %u / %u\n", g_ps_hw6_hash_probe.api_version, g_ps_hw6_hash_probe.sha256_count, g_ps_hw6_hash_probe.last_status, g_ps_hw6_hash_probe.hal_status, g_ps_hw6_hash_probe.hal_error, g_ps_hw6_hash_probe.input_bytes, g_ps_hw6_hash_probe.duration_ticks
printf "egg package bytes/hash low/high/chunks/scenes = %u / 0x%x / 0x%x / %u / %u\n", g_ps_egg_state_loader_probe.package_size, g_ps_egg_state_loader_probe.package_id_hash_low, g_ps_egg_state_loader_probe.package_id_hash_high, g_ps_egg_state_loader_probe.chunk_count, g_ps_egg_state_loader_probe.scene_count
printf "egg entry/selected scene/decode count = %u / %u / %u\n", g_ps_egg_state_loader_probe.entry_scene_id, g_ps_egg_state_loader_probe.selected_scene_id, g_ps_egg_state_loader_probe.scene_decode_count
printf "egg graph/render/wait chunks = %u / %u / %u\n", g_ps_egg_state_loader_probe.graph_chunk_index, g_ps_egg_state_loader_probe.render_chunk_index, g_ps_egg_state_loader_probe.waiting_chunk_index
printf "egg asset/sprite/animation chunks frames = %u / %u / %u / %u\n", g_ps_egg_state_loader_probe.asset_chunk_index, g_ps_egg_state_loader_probe.sprite_chunk_index, g_ps_egg_state_loader_probe.animation_chunk_index, g_ps_egg_state_loader_probe.sprite_frame_count
printf "egg audio asset/bank/cue chunks assets/cues/adpcm bytes = %u / %u / %u / %u / %u / %u\n", g_ps_egg_state_loader_probe.audio_asset_chunk_index, g_ps_egg_state_loader_probe.audio_bank_chunk_index, g_ps_egg_state_loader_probe.audio_cue_chunk_index, g_ps_egg_state_loader_probe.audio_asset_count, g_ps_egg_state_loader_probe.audio_cue_count, g_ps_egg_state_loader_probe.audio_adpcm_bytes
printf "egg states/inputs/routes/transitions = %u / %u / %u / %u\n", g_ps_egg_state_loader_probe.state_count, g_ps_egg_state_loader_probe.input_count, g_ps_egg_state_loader_probe.route_count, g_ps_egg_state_loader_probe.transition_count
printf "egg render models/elements waiting visuals/elements = %u / %u / %u / %u\n", g_ps_egg_state_loader_probe.render_model_count, g_ps_egg_state_loader_probe.render_element_count, g_ps_egg_state_loader_probe.waiting_visual_count, g_ps_egg_state_loader_probe.waiting_element_count
printf "scene api/type/active/status/activation source/status = %u / %u / %u / 0x%x / 0x%x / %u / 0x%x\n", g_ps_scene_runtime_probe.api_version, g_ps_scene_runtime_probe.scene_type, g_ps_scene_runtime_probe.active, g_ps_scene_runtime_probe.last_status, g_ps_scene_runtime_probe.activation_status, g_ps_scene_runtime_probe.package_source, g_ps_scene_runtime_probe.package_source_status
printf "render model resolve/status scene/state/visual = %u / 0x%x / %u / %u / %u\n", g_ps_scene_runtime_probe.render_model_resolve_count, g_ps_scene_runtime_probe.render_model_status, g_ps_scene_runtime_probe.render_model_scene_id, g_ps_scene_runtime_probe.render_model_state_id, g_ps_scene_runtime_probe.render_model_visual_binding_id
printf "render model content/timeline/focus = %u / %u / %u\n", g_ps_scene_runtime_probe.render_model_content_revision, g_ps_scene_runtime_probe.render_model_timeline_revision, g_ps_scene_runtime_probe.render_model_focus_index
printf "render model elements/focus element/sprites = %u / %u / %u\n", g_ps_scene_runtime_probe.render_model_element_count, g_ps_scene_runtime_probe.render_model_focus_element_id, g_ps_scene_runtime_probe.render_model_sprite_count
printf "scene enter/exit/action/change = %u / %u / %u / %u\n", g_ps_scene_runtime_probe.enter_count, g_ps_scene_runtime_probe.exit_count, g_ps_scene_runtime_probe.action_count, g_ps_scene_runtime_probe.state_change_count
printf "scene state/content revision/timeline revision/last action = %u / %u / %u / %u\n", g_ps_scene_runtime_probe.state_index, g_ps_scene_runtime_probe.state_revision, g_ps_scene_runtime_probe.timeline_revision, g_ps_scene_runtime_probe.last_action
printf "scene descriptor validate/scene/states/transitions = %u / %u / %u / %u\n", g_ps_scene_runtime_probe.descriptor_validate_count, g_ps_scene_runtime_probe.scene_id, g_ps_scene_runtime_probe.descriptor_state_count, g_ps_scene_runtime_probe.descriptor_transition_count
printf "scene descriptor visual bindings = %u\n", g_ps_scene_runtime_probe.descriptor_visual_binding_count
printf "scene descriptor routes/variables/guards/actions = %u / %u / %u / %u\n", g_ps_scene_runtime_probe.descriptor_input_route_count, g_ps_scene_runtime_probe.descriptor_variable_count, g_ps_scene_runtime_probe.descriptor_guard_count, g_ps_scene_runtime_probe.descriptor_action_count
printf "scene descriptor waiting animations = %u\n", g_ps_scene_runtime_probe.descriptor_waiting_animation_count
printf "scene interaction mode/route/meaningful mask = %u / %u / 0x%x\n", g_ps_scene_runtime_probe.descriptor_interaction_mode, g_ps_scene_runtime_probe.descriptor_inactive_route, g_ps_scene_runtime_probe.descriptor_meaningful_input_mask
printf "scene state id/visual/focus transition match/miss = %u / %u / %u / %u / %u\n", g_ps_scene_runtime_probe.state_id, g_ps_scene_runtime_probe.visual_binding_id, g_ps_scene_runtime_probe.focus_index, g_ps_scene_runtime_probe.transition_match_count, g_ps_scene_runtime_probe.transition_miss_count
printf "scene route match/miss guard eval/pass/reject = %u / %u / %u / %u / %u\n", g_ps_scene_runtime_probe.input_route_match_count, g_ps_scene_runtime_probe.input_route_miss_count, g_ps_scene_runtime_probe.guard_evaluate_count, g_ps_scene_runtime_probe.guard_pass_count, g_ps_scene_runtime_probe.guard_reject_count
printf "scene action commit/error event/transition/variable = %u / %u / %u / %u / %d\n", g_ps_scene_runtime_probe.action_commit_count, g_ps_scene_runtime_probe.action_error_count, g_ps_scene_runtime_probe.last_scene_event_id, g_ps_scene_runtime_probe.last_transition_id, g_ps_scene_runtime_probe.primary_variable_value
printf "scene element action commit/last kind/binding/element/value/secondary = %u / %u / %u / %u / %d / %d\n", g_ps_scene_runtime_probe.element_action_commit_count, g_ps_scene_runtime_probe.last_element_action_kind, g_ps_scene_runtime_probe.last_element_action_binding_id, g_ps_scene_runtime_probe.last_element_action_id, g_ps_scene_runtime_probe.last_element_action_value, g_ps_scene_runtime_probe.last_element_action_secondary_value
printf "scene waiting animation commit/rebase = %u / %u\n", g_ps_scene_runtime_probe.waiting_animation_commit_count, g_ps_scene_runtime_probe.waiting_animation_rebase_count
printf "scene SFX commit/take/last cue = %u / %u / %u\n", g_ps_scene_runtime_probe.sfx_action_commit_count, g_ps_scene_runtime_probe.sfx_request_take_count, g_ps_scene_runtime_probe.last_sfx_cue_index
printf "scene replace count/fail source/target/status = %u / %u / %u / %u / 0x%x\n", g_ps_scene_runtime_probe.scene_replace_count, g_ps_scene_runtime_probe.scene_replace_fail_count, g_ps_scene_runtime_probe.scene_replace_source_id, g_ps_scene_runtime_probe.scene_replace_target_id, g_ps_scene_runtime_probe.scene_replace_status
printf "runtime class/exec/lifecycle/caps = %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.runtime_current_class, g_ps_hw6_rtos_probe.runtime_execution, g_ps_hw6_rtos_probe.runtime_lifecycle, g_ps_hw6_rtos_probe.runtime_active_capabilities
printf "runtime stack bytes/start/end/ptr/lower margin = %u / 0x%x / 0x%x / 0x%x / %u\n", g_ps_hw6_rtos_probe.thread_stack_config_bytes[8], ps_threads[8].tx_thread_stack_start, ps_threads[8].tx_thread_stack_end, ps_threads[8].tx_thread_stack_ptr, (unsigned int)ps_threads[8].tx_thread_stack_ptr - (unsigned int)ps_threads[8].tx_thread_stack_start
printf "input policy runtime deliver/target/status = %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.input_policy_runtime_deliver_count, g_ps_hw6_rtos_probe.input_policy_last_target, g_ps_hw6_rtos_probe.input_policy_last_status
printf "runtime input event/button/id/status = %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.runtime_input_event_count, g_ps_hw6_rtos_probe.runtime_input_button_count, g_ps_hw6_rtos_probe.runtime_input_last_button_id, g_ps_hw6_rtos_probe.runtime_input_last_status
printf "SFX dispatch/send owner/status clock req/release cue = %u / 0x%x / %u / 0x%x / 0x%x / 0x%x / %u\n", g_ps_hw6_rtos_probe.audio_sfx_dispatch_count, g_ps_hw6_rtos_probe.audio_sfx_send_status, g_ps_hw6_rtos_probe.audio_sfx_owner_count, g_ps_hw6_rtos_probe.audio_sfx_owner_status, g_ps_hw6_rtos_probe.audio_sfx_clock_request_status, g_ps_hw6_rtos_probe.audio_sfx_clock_release_status, g_ps_hw6_rtos_probe.audio_sfx_last_cue_index
printf "SFX request/cue/asset priority/volume adpcm/samples/blocks = %u / %u / %u / %u / %u / %u / %u / %u\n", g_ps_hw6_owner_probe.audio_sfx_request_count, g_ps_hw6_owner_probe.audio_sfx_cue_index, g_ps_hw6_owner_probe.audio_sfx_asset_index, g_ps_hw6_owner_probe.audio_sfx_priority, g_ps_hw6_owner_probe.audio_sfx_volume, g_ps_hw6_owner_probe.audio_sfx_adpcm_bytes, g_ps_hw6_owner_probe.audio_sfx_sample_count, g_ps_hw6_owner_probe.audio_sfx_block_count
printf "SFX decode status/decoded audio start/stop/complete/success = 0x%x / %u / 0x%x / 0x%x / %u / %u\n", g_ps_hw6_owner_probe.audio_sfx_decode_status, g_ps_hw6_owner_probe.audio_sfx_decoded_samples, g_ps_hw6_owner_probe.audio_start_status, g_ps_hw6_owner_probe.audio_stop_status, g_ps_hw6_owner_probe.audio_complete, g_ps_hw6_owner_probe.audio_success
printf "interaction mode/state deadline refresh active/inactive = %u / %u / %u / %u / %u / %u\n", g_ps_hw6_rtos_probe.runtime_interaction_mode, g_ps_hw6_rtos_probe.runtime_interaction_state, g_ps_hw6_rtos_probe.runtime_interaction_deadline_tick, g_ps_hw6_rtos_probe.runtime_interaction_activity_refresh_count, g_ps_hw6_rtos_probe.runtime_interaction_active_count, g_ps_hw6_rtos_probe.runtime_interaction_inactive_count
printf "ui page/focus = %u / %u\n", g_ps_ui_router_probe.current_page, g_ps_ui_router_probe.focus_index
printf "display page/focus dirty count/first/last = %u / %u / %u / %u / %u\n", g_ps_hw6_owner_probe.display_ui_page, g_ps_hw6_owner_probe.display_ui_current_focus_row, g_ps_hw6_owner_probe.display_dirty_row_count, g_ps_hw6_owner_probe.display_dirty_first_row, g_ps_hw6_owner_probe.display_dirty_last_row
printf "display UI request/render count = %u / %u\n", g_ps_hw6_owner_probe.display_ui_request_count, g_ps_hw6_owner_probe.display_ui_render_count
printf "display UI primitive id = %u\n", g_ps_hw6_owner_probe.display_ui_primitive_id
printf "waiting presentation/steps/elements/status = %u / %u / %u / 0x%x\n", g_ps_hw6_owner_probe.display_waiting_presentation_id, g_ps_hw6_owner_probe.display_waiting_sequence_frame_count, g_ps_hw6_owner_probe.display_waiting_element_count, g_ps_hw6_owner_probe.display_waiting_snapshot_status
printf "timeline preserve/rebase/frame/deadline/status = %u / %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.display_waiting_preserve_count, g_ps_hw6_rtos_probe.display_waiting_rebase_count, g_ps_hw6_rtos_probe.display_waiting_preserve_frame, g_ps_hw6_rtos_probe.display_waiting_preserve_deadline_tick, g_ps_hw6_rtos_probe.display_waiting_preserve_status
printf "LPBAM ready/active STOP2 entries = %u / %u / %u\n", g_ps_hw6_owner_probe.display_lpbam_ready, g_ps_hw6_owner_probe.display_lpbam_active, g_ps_hw6_rtos_probe.stop2_auto_entry_count
printf "expected embedded source: api/override/selected/status/reason=3/2/1/0/0; loader api/load/status/reason=12/1/0/0 package bytes/chunks/scenes=5380/15/2 audio chunks=12/13/14 assets/cues/adpcm=1/1/1340 states/inputs/routes/transitions=3/3/7/9\n"
printf "expected scene replacement: runtime api/type/active/status/activation/source=16/1/1/0/0/1; after two A presses replace count>=2 fail=0 source/target alternates 1/2 and status=0; selected scene matches active descriptor scene\n"
printf "expected active scene and SFX: source descriptor actions/waiting animations=17/2; center-to-right R commits/takes cue 0 once, qAudio send/owner/clock/decode/start/stop statuses=0, cue asset=0 priority/volume=96/224 samples/blocks=2560/10 decoded=2560 success=1; STOP2 resumes after the 160 ms burst\n"
printf "--- end HW6 STATE_SCENE reactive loop ---\n"
