set pagination off
printf "--- HW6 USB atomic A/B package install and launch ---\n"
printf "rtos/owner/source api = %u / %u / %u\n", g_ps_hw6_rtos_probe.version, g_ps_hw6_owner_sm_probe.version, g_ps_package_source_probe.api_version
printf "UI actions scan/install/complete-launch send = %u / %u / 0x%x / 0x%x\n", g_ps_hw6_rtos_probe.ui_action_package_scan_count, g_ps_hw6_rtos_probe.ui_action_package_install_stub_count, g_ps_hw6_rtos_probe.package_install_runtime_complete_send_status, g_ps_hw6_rtos_probe.package_install_runtime_launch_send_status
printf "UI router pending/action request/take/status = %u / %u / %u / 0x%x\n", g_ps_ui_router_probe.pending_action, g_ps_ui_router_probe.action_request_count, g_ps_ui_router_probe.action_take_count, g_ps_ui_router_probe.last_status
printf "UI action count/last/send = %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.ui_action_count, g_ps_hw6_rtos_probe.ui_action_last, g_ps_hw6_rtos_probe.ui_action_send_status
printf "admission count/allow/deny/suspend = %u / %u / %u / %u\n", g_ps_hw6_rtos_probe.admission_request_count, g_ps_hw6_rtos_probe.admission_allow_count, g_ps_hw6_rtos_probe.admission_deny_count, g_ps_hw6_rtos_probe.admission_suspend_count
printf "admission last action/result/reason/status/overlay = %u / %u / %u / 0x%x / %u\n", g_ps_hw6_rtos_probe.admission_last_action, g_ps_hw6_rtos_probe.admission_last_result, g_ps_hw6_rtos_probe.admission_last_reason, g_ps_hw6_rtos_probe.admission_last_status, g_ps_hw6_rtos_probe.admission_last_overlay_active
printf "MSC host active/export enabled = %u / %u\n", g_ps_hw6_owner_sm_probe.usb_host_msc_active, g_ps_storage_msc_bridge_probe.export_enabled
printf "staging scan status/class/pkg/unsupported/pending = 0x%x / %u / %u / %u / %u\n", g_ps_hw6_owner_sm_probe.usb_stage_rescan_status, g_ps_hw6_owner_sm_probe.usb_stage_rescan_classification, g_ps_hw6_owner_sm_probe.usb_stage_rescan_package_candidate_count, g_ps_hw6_owner_sm_probe.usb_stage_rescan_unsupported_count, g_ps_hw6_owner_sm_probe.package_candidate_pending
printf "staging validate status/reason/file/header/read = 0x%x / %u / %u / %u / %u\n", g_ps_hw6_owner_sm_probe.package_validate_status, g_ps_hw6_owner_sm_probe.package_validate_reason, g_ps_hw6_owner_sm_probe.package_validate_file_size, g_ps_hw6_owner_sm_probe.package_validate_header_bytes, g_ps_hw6_owner_sm_probe.package_validate_bytes_read
printf "staging install request/status load/status/reason = %u / 0x%x / 0x%x / 0x%x / %u\n", g_ps_hw6_owner_sm_probe.package_install_stub_request_count, g_ps_hw6_owner_sm_probe.package_install_stub_last_status, g_ps_hw6_owner_sm_probe.package_install_stub_load_status, g_ps_hw6_owner_sm_probe.package_install_stub_persistent_status, g_ps_hw6_owner_sm_probe.package_install_stub_load_reason
printf "staging file/read/declared/capacity = %u / %u / %u / %u\n", g_ps_hw6_owner_sm_probe.package_install_stub_file_size, g_ps_hw6_owner_sm_probe.package_install_stub_bytes_read, g_ps_hw6_owner_sm_probe.package_install_stub_declared_size, g_ps_hw6_owner_sm_probe.package_install_stub_capacity
printf "staging file/FileX/LevelX close = 0x%x / 0x%x / 0x%x\n", g_ps_hw6_owner_sm_probe.package_install_stub_file_close_status, g_ps_hw6_owner_sm_probe.package_install_stub_fx_close_status, g_ps_hw6_owner_sm_probe.package_install_stub_lx_close_status
printf "A/B source record/slot target record/slot/generation = %u / %u / %u / %u / %u\n", g_ps_storage_package_install_probe.source_record, g_ps_storage_package_install_probe.source_slot, g_ps_storage_package_install_probe.target_record, g_ps_storage_package_install_probe.target_slot, g_ps_storage_package_install_probe.target_generation
printf "A/B target package/index address = 0x%x / 0x%x\n", g_ps_storage_package_install_probe.target_package_start, g_ps_storage_package_install_probe.target_index_start
printf "package erase/program/verify status bytes/mismatches = 0x%x / 0x%x / 0x%x / %u / %u\n", g_ps_storage_package_install_probe.package_erase_status, g_ps_storage_package_install_probe.package_program_status, g_ps_storage_package_install_probe.package_verify_status, g_ps_storage_package_install_probe.package_verify_bytes, g_ps_storage_package_install_probe.package_verify_mismatches
printf "index erase/program/verify status mismatches/crc = 0x%x / 0x%x / 0x%x / %u / 0x%x\n", g_ps_storage_package_install_probe.index_erase_status, g_ps_storage_package_install_probe.index_program_status, g_ps_storage_package_install_probe.index_verify_status, g_ps_storage_package_install_probe.index_verify_mismatches, g_ps_storage_package_install_probe.index_crc32
printf "commit program/verify/marker rescan/status/stage = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / %u\n", g_ps_storage_package_install_probe.commit_status, g_ps_storage_package_install_probe.commit_verify_status, g_ps_storage_package_install_probe.commit_marker, g_ps_storage_package_install_probe.rescan_status, g_ps_storage_package_install_probe.status, g_ps_storage_package_install_probe.stage
printf "selected record/slot/generation valid/available = %u / %u / %u / %u / %u\n", g_ps_storage_package_index_probe.selected_record, g_ps_storage_package_index_probe.selected_slot, g_ps_storage_package_index_probe.selected_generation, g_ps_storage_package_index_probe.valid_record_count, g_ps_storage_package_index_probe.installed_available
printf "owner persistent target record/slot/generation publish/source = %u / %u / %u / 0x%x / %u\n", g_ps_hw6_owner_sm_probe.package_install_stub_target_record, g_ps_hw6_owner_sm_probe.package_install_stub_target_slot, g_ps_hw6_owner_sm_probe.package_install_stub_target_generation, g_ps_hw6_owner_sm_probe.package_install_stub_publish_status, g_ps_hw6_owner_sm_probe.package_install_stub_source
printf "resident selected/source/available/generation/bytes = %u / %u / %u / %u / %u\n", g_ps_package_source_probe.selected_source, g_ps_package_source_probe.resident_source, g_ps_package_source_probe.staged_available, g_ps_package_source_probe.generation, g_ps_package_source_probe.package_size
printf "runtime complete/launch send = 0x%x / 0x%x\n", g_ps_hw6_rtos_probe.package_install_runtime_complete_send_status, g_ps_hw6_rtos_probe.package_install_runtime_launch_send_status
printf "scene active/activation/source egg/hash = %u / 0x%x / %u / 0x%x / 0x%x\n", g_ps_scene_runtime_probe.active, g_ps_scene_runtime_probe.activation_status, g_ps_scene_runtime_probe.package_source, g_ps_egg_state_loader_probe.last_status, g_ps_hw6_hash_probe.last_status
printf "scene id/state joystick policy/mask routes match/miss = %u / %u / %u / 0x%x / %u / %u / %u\n", g_ps_scene_runtime_probe.scene_id, g_ps_scene_runtime_probe.state_id, g_ps_scene_runtime_probe.descriptor_joystick_policy, g_ps_scene_runtime_probe.descriptor_meaningful_input_mask, g_ps_scene_runtime_probe.descriptor_input_route_count, g_ps_scene_runtime_probe.input_route_match_count, g_ps_scene_runtime_probe.input_route_miss_count
printf "input policy events/deliver UI/runtime/suppress lock last target/reason/status = %u / %u / %u / %u / %u / %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.input_policy_event_count, g_ps_hw6_rtos_probe.input_policy_deliver_count, g_ps_hw6_rtos_probe.input_policy_ui_deliver_count, g_ps_hw6_rtos_probe.input_policy_runtime_deliver_count, g_ps_hw6_rtos_probe.input_policy_suppress_count, g_ps_hw6_rtos_probe.input_policy_lock_active, g_ps_hw6_rtos_probe.input_policy_last_target, g_ps_hw6_rtos_probe.input_policy_last_reason, g_ps_hw6_rtos_probe.input_policy_last_status
printf "joystick IRQ/enqueue/dequeue/drop/pending logical change/event/mask/source/target/status = %u / %u / %u / %u / %u / %u / %u / 0x%x / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.joystick_irq_count, g_ps_hw6_rtos_probe.joystick_irq_enqueue_count, g_ps_hw6_rtos_probe.joystick_irq_dequeue_count, g_ps_hw6_rtos_probe.joystick_irq_drop_count, g_ps_hw6_rtos_probe.joystick_irq_pending_count, g_ps_hw6_rtos_probe.joystick_logical_change_count, g_ps_hw6_rtos_probe.joystick_logical_last_event, g_ps_hw6_rtos_probe.joystick_logical_last_direction_mask, g_ps_hw6_rtos_probe.joystick_logical_last_source, g_ps_hw6_rtos_probe.joystick_logical_last_target, g_ps_hw6_rtos_probe.joystick_logical_last_status
printf "joystick awake poll count/errors/next/status = %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.joystick_awake_poll_count, g_ps_hw6_rtos_probe.joystick_awake_poll_error_count, g_ps_hw6_rtos_probe.joystick_awake_poll_next_tick, g_ps_hw6_rtos_probe.joystick_awake_poll_last_status
printf "joystick cardinal request/status failures/stage driver/HAL/error = %u / 0x%x / %u / %u / 0x%x / 0x%x / 0x%x\n", g_ps_hw6_owner_sm_probe.joystick_cardinal_request_count, g_ps_hw6_owner_sm_probe.joystick_cardinal_status, g_ps_hw6_owner_sm_probe.joystick_cardinal_failure_count, g_ps_hw6_owner_sm_probe.joystick_cardinal_last_failure_stage, g_ps_hw6_owner_sm_probe.joystick_cardinal_last_driver_status, g_ps_hw6_owner_sm_probe.joystick_cardinal_last_hal_status, g_ps_hw6_owner_sm_probe.joystick_cardinal_last_hal_error
printf "joystick driver state/status input status/faults I2C state/error = %u / 0x%x / 0x%x / %u / 0x%x / 0x%x\n", g_ps_hw6_owner_sm_probe.joystick_driver_state, g_ps_hw6_owner_sm_probe.joystick_driver_last_status, g_ps_hw6_owner_sm_probe.joystick_input_last_status, g_ps_hw6_owner_sm_probe.joystick_input_fault_count, g_ps_hw6_owner_sm_probe.joystick_i2c_state_after, g_ps_hw6_owner_sm_probe.joystick_i2c_error_after
printf "joystick recovery attempt/success/failure/status ready/identity = %u / %u / %u / 0x%x / 0x%x / 0x%x\n", g_ps_hw6_owner_sm_probe.joystick_recovery_attempt_count, g_ps_hw6_owner_sm_probe.joystick_recovery_success_count, g_ps_hw6_owner_sm_probe.joystick_recovery_failure_count, g_ps_hw6_owner_sm_probe.joystick_recovery_last_status, g_ps_hw6_owner_sm_probe.joystick_ready_status, g_ps_hw6_owner_sm_probe.joystick_identity_status
printf "joystick recovery id/mfg/match writes/verifies/sleep = 0x%x / 0x%x / 0x%x / %u / 0x%x / 0x%x / 0x%x\n", g_ps_hw6_owner_sm_probe.joystick_device_id, g_ps_hw6_owner_sm_probe.joystick_manufacturer_lsb, g_ps_hw6_owner_sm_probe.joystick_manufacturer_msb, g_ps_hw6_owner_sm_probe.joystick_identity_match, g_ps_hw6_owner_sm_probe.joystick_write_ok_mask, g_ps_hw6_owner_sm_probe.joystick_verify_ok_mask, g_ps_hw6_owner_sm_probe.joystick_sleep_write_status
printf "runtime input events/last event/button/mask/status = %u / %u / %u / 0x%x / 0x%x\n", g_ps_hw6_rtos_probe.runtime_input_event_count, g_ps_hw6_rtos_probe.runtime_input_last_event, g_ps_hw6_rtos_probe.runtime_input_last_button_id, g_ps_hw6_rtos_probe.runtime_input_last_mask, g_ps_hw6_rtos_probe.runtime_input_last_status
printf "SFX dispatch/send owner/status clock on/off cue = %u / 0x%x / %u / 0x%x / 0x%x / 0x%x / %u\n", g_ps_hw6_rtos_probe.audio_sfx_dispatch_count, g_ps_hw6_rtos_probe.audio_sfx_send_status, g_ps_hw6_rtos_probe.audio_sfx_owner_count, g_ps_hw6_rtos_probe.audio_sfx_owner_status, g_ps_hw6_rtos_probe.audio_sfx_clock_request_status, g_ps_hw6_rtos_probe.audio_sfx_clock_release_status, g_ps_hw6_rtos_probe.audio_sfx_last_cue_index
printf "SFX stream frames/half refills callbacks half/full underrun silence decoded/wait/status = %u / %u / %u / %u / %u / %u / %u / %u / 0x%x / 0x%x\n", g_ps_hw6_owner_probe.audio_sfx_stream_buffer_frames, g_ps_hw6_owner_probe.audio_sfx_stream_half_frames, g_ps_hw6_owner_probe.audio_sfx_stream_refill_count, g_ps_hw6_owner_probe.audio_sfx_stream_first_half_callback_count, g_ps_hw6_owner_probe.audio_sfx_stream_second_half_callback_count, g_ps_hw6_owner_probe.audio_sfx_stream_underrun_count, g_ps_hw6_owner_probe.audio_sfx_stream_silence_frames, g_ps_hw6_owner_probe.audio_sfx_decoded_samples, g_ps_hw6_owner_probe.audio_sfx_stream_wait_status, g_ps_hw6_owner_probe.audio_sfx_stream_status
printf "display queue enqueued/capacity/available thread state = %u / %u / %u / %u\n", ps_queues[3].tx_queue_enqueued, ps_queues[3].tx_queue_capacity, ps_queues[3].tx_queue_available_storage, ps_threads[3].tx_thread_state
printf "power queue enqueued/capacity/available thread state = %u / %u / %u / %u\n", ps_queues[0].tx_queue_enqueued, ps_queues[0].tx_queue_capacity, ps_queues[0].tx_queue_available_storage, ps_threads[0].tx_thread_state
printf "display UI request/render page/focus/status blink request/render/status = %u / %u / %u / %u / 0x%x / %u / %u / 0x%x\n", g_ps_hw6_owner_probe.display_ui_request_count, g_ps_hw6_owner_probe.display_ui_render_count, g_ps_hw6_owner_probe.display_ui_page, g_ps_hw6_owner_probe.display_ui_focus_index, g_ps_hw6_owner_probe.display_ui_status, g_ps_hw6_owner_probe.display_blink_request_count, g_ps_hw6_owner_probe.display_blink_render_count, g_ps_hw6_owner_probe.display_blink_status
printf "display driver state/status complete/success clock transfer/release = %u / 0x%x / %u / %u / 0x%x / 0x%x\n", g_ps_hw6_owner_probe.display_driver_state, g_ps_hw6_owner_probe.display_driver_last_status, g_ps_hw6_owner_probe.display_complete, g_ps_hw6_owner_probe.display_success, g_ps_hw6_rtos_probe.display_clock_transfer_status, g_ps_hw6_rtos_probe.display_clock_release_status
printf "runtime interaction mode/state active/inactive cue/activation wake allowed = %u / %u / %u / %u / %u / %u / %u\n", g_ps_hw6_rtos_probe.runtime_interaction_mode, g_ps_hw6_rtos_probe.runtime_interaction_state, g_ps_hw6_rtos_probe.runtime_interaction_active_count, g_ps_hw6_rtos_probe.runtime_interaction_inactive_count, g_ps_hw6_rtos_probe.runtime_interaction_cue_active, g_ps_hw6_rtos_probe.runtime_interaction_activation_active, g_ps_hw6_rtos_probe.runtime_interaction_joystick_wake_allowed
printf "UI page/package/shutdown/last event runtime class/lifecycle STOP2 = %u / %u / %u / %u / %u / %u / %u\n", g_ps_ui_router_probe.current_page, g_ps_ui_router_probe.package_state, g_ps_ui_router_probe.shutdown_state, g_ps_ui_router_probe.last_event, g_ps_hw6_rtos_probe.runtime_current_class, g_ps_hw6_rtos_probe.runtime_lifecycle, g_ps_hw6_rtos_probe.stop2_auto_entry_count
printf "STOP2 enabled/checks/entries/skips/status physical/failure = %u / %u / %u / %u / 0x%x / %u / 0x%x\n", g_ps_hw6_rtos_probe.stop2_auto_enabled, g_ps_hw6_rtos_probe.stop2_auto_check_count, g_ps_hw6_rtos_probe.stop2_auto_entry_count, g_ps_hw6_rtos_probe.stop2_auto_skip_count, g_ps_hw6_rtos_probe.stop2_auto_last_status, g_ps_hw6_clock_policy_probe.stop2_physical_ready, g_ps_hw6_clock_policy_probe.stop2_physical_failure_mask
printf "STOP2 display barriers handoff req/send/wait/flags/owner/status = %u / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", g_ps_hw6_rtos_probe.stop2_blink_handoff_request_count, g_ps_hw6_rtos_probe.stop2_blink_handoff_send_status, g_ps_hw6_rtos_probe.stop2_blink_handoff_wait_status, g_ps_hw6_rtos_probe.stop2_blink_handoff_ack_flags, g_ps_hw6_rtos_probe.stop2_blink_handoff_owner_status, g_ps_hw6_rtos_probe.stop2_blink_handoff_status
printf "STOP2 display barriers prepare req/send/wait/flags/owner/ready abort req/send/wait/flags/owner = %u / 0x%x / 0x%x / 0x%x / 0x%x / %u / %u / 0x%x / 0x%x / 0x%x / 0x%x\n", g_ps_hw6_rtos_probe.stop2_lpbam_prepare_request_count, g_ps_hw6_rtos_probe.stop2_lpbam_prepare_send_status, g_ps_hw6_rtos_probe.stop2_lpbam_prepare_wait_status, g_ps_hw6_rtos_probe.stop2_lpbam_prepare_ack_flags, g_ps_hw6_rtos_probe.stop2_lpbam_prepare_owner_status, g_ps_hw6_rtos_probe.stop2_lpbam_prepare_ready_after, g_ps_hw6_rtos_probe.stop2_lpbam_abort_request_count, g_ps_hw6_rtos_probe.stop2_lpbam_abort_send_status, g_ps_hw6_rtos_probe.stop2_lpbam_abort_wait_status, g_ps_hw6_rtos_probe.stop2_lpbam_abort_ack_flags, g_ps_hw6_rtos_probe.stop2_lpbam_abort_owner_status
printf "owner storage/flash state OSPI state/error = %u / %u / 0x%x / 0x%x\n", g_ps_hw6_owner_sm_probe.current_state[7], g_ps_hw6_owner_sm_probe.current_state[8], hospi1.State, hospi1.ErrorCode
printf "expected explicit flow: after MSC reclaim package scan does not auto-run; select PACKAGE INSTALL to scan and show scan status=0 class=2 pkg=1 pending=1 with validate status/reason=0/1 and a non-zero file size for the current Peep Studio egg; pressing A on VALID installs to A/B and leaves package state=INSTALLED; complete send=0 and launch send=0 means install completion was sent and launch was intentionally deferred; pressing A on INSTALLED launches scene source=3.\n"
printf "--- end HW6 USB atomic A/B package install and launch ---\n"
