printf "--- HW6 ThreadX init failure / stack allocation probe ---\n"
printf "Use while halted in tx_application_define App_ThreadX_Init_Error loop.\n"
printf "rtos init status/step/index = 0x%lx / %lu / %lu\n", g_ps_hw6_rtos_probe.init_status, g_ps_hw6_rtos_probe.init_error_step, g_ps_hw6_rtos_probe.init_error_index
printf "pool before status/avail/frags = 0x%lx / %lu / %lu\n", g_ps_hw6_rtos_probe.pool_info_before_status, g_ps_hw6_rtos_probe.pool_available_before, g_ps_hw6_rtos_probe.pool_fragments_before
printf "pool after status/avail/frags  = 0x%lx / %lu / %lu\n", g_ps_hw6_rtos_probe.pool_info_after_status, g_ps_hw6_rtos_probe.pool_available_after, g_ps_hw6_rtos_probe.pool_fragments_after
printf "stack alloc P/A/I/D/S/ST/C/UI/RT = 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx\n", g_ps_hw6_rtos_probe.stack_alloc_status[0], g_ps_hw6_rtos_probe.stack_alloc_status[1], g_ps_hw6_rtos_probe.stack_alloc_status[2], g_ps_hw6_rtos_probe.stack_alloc_status[3], g_ps_hw6_rtos_probe.stack_alloc_status[4], g_ps_hw6_rtos_probe.stack_alloc_status[5], g_ps_hw6_rtos_probe.stack_alloc_status[6], g_ps_hw6_rtos_probe.stack_alloc_status[7], g_ps_hw6_rtos_probe.stack_alloc_status[8]
printf "queue alloc P/A/I/D/S/ST/C/UI/RT = 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx\n", g_ps_hw6_rtos_probe.queue_alloc_status[0], g_ps_hw6_rtos_probe.queue_alloc_status[1], g_ps_hw6_rtos_probe.queue_alloc_status[2], g_ps_hw6_rtos_probe.queue_alloc_status[3], g_ps_hw6_rtos_probe.queue_alloc_status[4], g_ps_hw6_rtos_probe.queue_alloc_status[5], g_ps_hw6_rtos_probe.queue_alloc_status[6], g_ps_hw6_rtos_probe.queue_alloc_status[7], g_ps_hw6_rtos_probe.queue_alloc_status[8]
printf "queue create P/A/I/D/S/ST/C/UI/RT = 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx\n", g_ps_hw6_rtos_probe.queue_create_status[0], g_ps_hw6_rtos_probe.queue_create_status[1], g_ps_hw6_rtos_probe.queue_create_status[2], g_ps_hw6_rtos_probe.queue_create_status[3], g_ps_hw6_rtos_probe.queue_create_status[4], g_ps_hw6_rtos_probe.queue_create_status[5], g_ps_hw6_rtos_probe.queue_create_status[6], g_ps_hw6_rtos_probe.queue_create_status[7], g_ps_hw6_rtos_probe.queue_create_status[8]
printf "thread create P/A/I/D/S/ST/C/UI/RT = 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx / 0x%lx\n", g_ps_hw6_rtos_probe.thread_create_status[0], g_ps_hw6_rtos_probe.thread_create_status[1], g_ps_hw6_rtos_probe.thread_create_status[2], g_ps_hw6_rtos_probe.thread_create_status[3], g_ps_hw6_rtos_probe.thread_create_status[4], g_ps_hw6_rtos_probe.thread_create_status[5], g_ps_hw6_rtos_probe.thread_create_status[6], g_ps_hw6_rtos_probe.thread_create_status[7], g_ps_hw6_rtos_probe.thread_create_status[8]
printf "stack cfg P/A/I/D/S/ST/C/UI/RT = %lu / %lu / %lu / %lu / %lu / %lu / %lu / %lu / %lu\n", g_ps_hw6_rtos_probe.thread_stack_config_bytes[0], g_ps_hw6_rtos_probe.thread_stack_config_bytes[1], g_ps_hw6_rtos_probe.thread_stack_config_bytes[2], g_ps_hw6_rtos_probe.thread_stack_config_bytes[3], g_ps_hw6_rtos_probe.thread_stack_config_bytes[4], g_ps_hw6_rtos_probe.thread_stack_config_bytes[5], g_ps_hw6_rtos_probe.thread_stack_config_bytes[6], g_ps_hw6_rtos_probe.thread_stack_config_bytes[7], g_ps_hw6_rtos_probe.thread_stack_config_bytes[8]
printf "stack size P/A/I/D/S/ST/C/UI/RT = %lu / %lu / %lu / %lu / %lu / %lu / %lu / %lu / %lu\n", g_ps_hw6_rtos_probe.thread_stack_size[0], g_ps_hw6_rtos_probe.thread_stack_size[1], g_ps_hw6_rtos_probe.thread_stack_size[2], g_ps_hw6_rtos_probe.thread_stack_size[3], g_ps_hw6_rtos_probe.thread_stack_size[4], g_ps_hw6_rtos_probe.thread_stack_size[5], g_ps_hw6_rtos_probe.thread_stack_size[6], g_ps_hw6_rtos_probe.thread_stack_size[7], g_ps_hw6_rtos_probe.thread_stack_size[8]
printf "owners: P=Power A=Audio I=Input D=Display S=Sensor ST=Storage C=Comm UI=UI RT=Runtime\n"
printf "status: TX_SUCCESS=0x0 TX_NO_MEMORY=0x10 NOT_RUN=0xffffffff\n"