set $rt = &g_ps_hw6_rtos_probe
set $ow = &g_ps_hw6_owner_probe
set $ui = &g_ps_ui_router_probe
set $sm = &g_ps_hw6_owner_sm_probe
printf "--- HW6 display LPBAM STOP2 admission handshake ---\n"
printf "rtos/owner api = %u / %u\n", $rt->version, $ow->version
printf "backend override var = %u\n", g_ps_hw6_power_stop2_display_backend_override
printf "awake LPBAM hold enable/active/count/start = %u / %u / %u / %u\n", g_ps_hw6_power_stop2_lpbam_awake_hold_enable, $rt->stop2_lpbam_awake_hold_active, $rt->stop2_lpbam_awake_hold_count, $rt->stop2_lpbam_awake_hold_start_tick
printf "ui page/render = %u / %u\n", $ui->current_page, $ow->display_ui_render_count
printf "display dirty rows count/first/last = %u / %u / %u\n", $ow->display_dirty_row_count, $ow->display_dirty_first_row, $ow->display_dirty_last_row
printf "display primitive id/prev/current = %u / %u / %u\n", $ow->display_renderer_primitive_id, $ow->display_renderer_previous_focus_row, $ow->display_renderer_current_focus_row
printf "display ui primitive id/prev/current = %u / %u / %u\n", $ow->display_ui_primitive_id, $ow->display_ui_previous_focus_row, $ow->display_ui_current_focus_row
printf "display backend req/selected/status/held = %u / %u / 0x%x / %u\n", $rt->stop2_display_wait_backend_requested, $rt->stop2_display_wait_backend_selected, $rt->stop2_display_wait_backend_status, $rt->stop2_display_wait_backend_held_ready
printf "display ready/page/render/status/prearmed/active = %u / %u / %u / 0x%x / %u / %u\n", $ow->display_lpbam_ready, $ow->display_lpbam_ready_page, $ow->display_lpbam_ready_render_count, $ow->display_lpbam_status, $ow->display_lpbam_prearmed, $ow->display_lpbam_active
printf "display prep count/tick/status/prearm = %u / %u / 0x%x / 0x%x\n", $ow->display_lpbam_prepare_count, $ow->display_lpbam_prepare_tick, $ow->display_lpbam_prepare_status, $ow->display_lpbam_prearm_status
printf "display commit count/tick/status = %u / %u / 0x%x\n", $ow->display_lpbam_commit_count, $ow->display_lpbam_commit_tick, $ow->display_lpbam_commit_status
printf "display lpbam animation/source/focus = %u / %u / %u\n", $ow->display_lpbam_animation_id, $ow->display_lpbam_source_primitive_id, $ow->display_lpbam_focus_row
printf "display lpbam program phases/frames/cadence/current = %u / %u / %u / %u\n", $ow->display_lpbam_phase_count, $ow->display_lpbam_sequence_frame_count, $ow->display_lpbam_cadence_ms, $ow->display_lpbam_current_phase
printf "display lpbam elements count ids phase counts = %u / %u,%u / %u,%u\n", $ow->display_lpbam_element_count, $ow->display_lpbam_element_id[0], $ow->display_lpbam_element_id[1], $ow->display_lpbam_element_phase_count[0], $ow->display_lpbam_element_phase_count[1]
printf "display lpbam program deadline/start/candidate rows = %u / %u / %u\n", $ow->display_lpbam_next_deadline_tick, $ow->display_lpbam_sequence_start_frame, $ow->display_lpbam_candidate_row_count
printf "display lpbam program sequence phases = %u / %u / %u / %u\n", $ow->display_lpbam_sequence_phase[0], $ow->display_lpbam_sequence_phase[1], $ow->display_lpbam_sequence_phase[2], $ow->display_lpbam_sequence_phase[3]
printf "display cursor row/count col/count = %u / %u / %u / %u\n", $ow->display_lpbam_cursor_start_row, $ow->display_lpbam_cursor_row_count, $ow->display_lpbam_cursor_start_column, $ow->display_lpbam_cursor_column_count
printf "display payload frames/chunks/bytes = %u / %u / %u\n", $ow->display_lpbam_payload_frame_count, $ow->display_lpbam_payload_chunk_count, $ow->display_lpbam_payload_bytes
printf "display admission api/status/reason = %u / 0x%x / %u\n", $ow->display_lpbam_admission_api_version, $ow->display_lpbam_admission_status, $ow->display_lpbam_admission_reason
printf "display admission sequence/chunks/payload = %u/%u %u/%u %u/%u\n", ps_lpbam_display_admission.sequence_used, ps_lpbam_display_admission.sequence_capacity, ps_lpbam_display_admission.chunk_used, ps_lpbam_display_admission.chunk_capacity, ps_lpbam_display_admission.payload_used_bytes, ps_lpbam_display_admission.payload_capacity_bytes
printf "display sequence first/count dirty start/count = %u/%u %u/%u | %u/%u %u/%u | %u/%u %u/%u | %u/%u %u/%u\n", ps_lpbam_display_sequence[0].first_chunk, ps_lpbam_display_sequence[0].chunk_count, ps_lpbam_display_sequence[0].dirty_start_row, ps_lpbam_display_sequence[0].dirty_row_count, ps_lpbam_display_sequence[1].first_chunk, ps_lpbam_display_sequence[1].chunk_count, ps_lpbam_display_sequence[1].dirty_start_row, ps_lpbam_display_sequence[1].dirty_row_count, ps_lpbam_display_sequence[2].first_chunk, ps_lpbam_display_sequence[2].chunk_count, ps_lpbam_display_sequence[2].dirty_start_row, ps_lpbam_display_sequence[2].dirty_row_count, ps_lpbam_display_sequence[3].first_chunk, ps_lpbam_display_sequence[3].chunk_count, ps_lpbam_display_sequence[3].dirty_start_row, ps_lpbam_display_sequence[3].dirty_row_count
printf "display first four chunk lengths = %u / %u / %u / %u\n", ps_lpbam_display_tx_len[0], ps_lpbam_display_tx_len[1], ps_lpbam_display_tx_len[2], ps_lpbam_display_tx_len[3]
printf "display fill/clock/link/start = 0x%x / 0x%x / 0x%x / 0x%x\n", $ow->display_lpbam_fill_status, $ow->display_lpbam_clock_status, $ow->display_lpbam_link_status, $ow->display_lpbam_start_status
printf "display dma start/state/error queue nodes = 0x%x / %u / 0x%x / %u\n", $ow->display_lpbam_dma_start_status, $ow->display_lpbam_dma_state_after_start, $ow->display_lpbam_dma_error_after_start, $ow->display_lpbam_queue_node_count
printf "display lptim init/oc/arr/cmp/start/restore = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", $ow->display_lpbam_lptim_init_status, $ow->display_lpbam_lptim_oc_status, $ow->display_lpbam_lptim_arr_status, $ow->display_lpbam_lptim_cmp_status, $ow->display_lpbam_lptim_start_status, $ow->display_lpbam_lptim_restore_status
printf "display lptim CR/CFGR/CCMR1/ARR/CMP = 0x%x / 0x%x / 0x%x / %u / %u\n", $ow->display_lpbam_lptim_cr_after_config, $ow->display_lpbam_lptim_cfgr_after_config, $ow->display_lpbam_lptim_ccmr1_after_config, $ow->display_lpbam_lptim_arr_after_config, $ow->display_lpbam_lptim_cmp_after_config
printf "display rcc before/after spi autocr before/after = 0x%x / 0x%x / 0x%x / 0x%x\n", $ow->display_lpbam_rcc_srdamr_before, $ow->display_lpbam_rcc_srdamr_after, $ow->display_lpbam_spi_autocr_before, $ow->display_lpbam_spi_autocr_after
printf "display lpbam spi kernel/dir/presc/ssid/cfg1/cfg2 = %u / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", $ow->display_lpbam_spi_kernel_hz, $ow->display_lpbam_spi_init_direction, $ow->display_lpbam_spi_init_prescaler, $ow->display_lpbam_spi_init_ss_idleness, $ow->display_lpbam_spi_cfg1_after_init, $ow->display_lpbam_spi_cfg2_after_init
printf "display lpbam spi FIFO threshold frames = %u\n", ((($ow->display_lpbam_spi_cfg1_after_init >> 5) & 0xf) + 1)
printf "display debug force ready count = %u\n", $ow->display_lpbam_debug_force_ready_count
printf "display abort count/tick/status = %u / %u / 0x%x\n", $ow->display_lpbam_abort_count, $ow->display_lpbam_abort_tick, $ow->display_lpbam_abort_status
printf "display abort lptim/dma/unlink/spi/lptimrestore/spirestore = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", $ow->display_lpbam_abort_lptim_status, $ow->display_lpbam_abort_dma_status, $ow->display_lpbam_abort_unlink_status, $ow->display_lpbam_abort_spi_status, $ow->display_lpbam_lptim_restore_status, $ow->display_lpbam_restore_status
printf "display clear count/reason = %u / %u\n", $ow->display_lpbam_clear_count, $ow->display_lpbam_clear_reason
printf "rtos prep count/tick/send/wait/ack = %u / %u / 0x%x / 0x%x / 0x%x\n", $rt->stop2_lpbam_prepare_request_count, $rt->stop2_lpbam_prepare_last_tick, $rt->stop2_lpbam_prepare_send_status, $rt->stop2_lpbam_prepare_wait_status, $rt->stop2_lpbam_prepare_ack_flags
printf "rtos prep owner/ready/clear = 0x%x / %u / %u\n", $rt->stop2_lpbam_prepare_owner_status, $rt->stop2_lpbam_prepare_ready_after, $rt->stop2_lpbam_prepare_display_clear_count
printf "rtos lpbam edge state/req/run/status = %u / %u / %u / 0x%x\n", $rt->stop2_lpbam_edge_state, $rt->stop2_lpbam_edge_request_count, $rt->stop2_lpbam_edge_run_count, $rt->stop2_lpbam_edge_status
printf "rtos lpbam edge req/target/run/ready tick = %u / %u / %u / %u\n", $rt->stop2_lpbam_edge_request_tick, $rt->stop2_lpbam_edge_target_tick, $rt->stop2_lpbam_edge_run_tick, $rt->stop2_lpbam_edge_ready_tick
printf "rtos lpbam edge request/run/render phase = %u / %u / %u\n", $rt->stop2_lpbam_edge_start_phase, $rt->stop2_lpbam_edge_run_phase, $rt->stop2_lpbam_edge_render_phase
printf "rtos lpbam edge miss/defer/wake send = %u / %u / 0x%x\n", $rt->stop2_lpbam_edge_miss_count, $rt->stop2_lpbam_edge_defer_count, $rt->stop2_lpbam_edge_wake_send_status
printf "rtos lpbam edge rearm pending/count/tick = %u / %u / %u\n", $rt->stop2_lpbam_edge_rearm_pending, $rt->stop2_lpbam_edge_rearm_count, $rt->stop2_lpbam_edge_rearm_tick
printf "rtos lpbam edge render phase/status/tick = %u / 0x%x / %u\n", $rt->stop2_lpbam_edge_render_phase, $rt->stop2_lpbam_edge_render_status, $rt->stop2_lpbam_edge_render_tick
printf "rtos lpbam sequence start/queue slot = %u / %u\n", ps_lpbam_display_sequence_start_frame, ps_lpbam_display_queue_start_slot
printf "rtos display deadline wait count/last/due = %u / %u / %u\n", $rt->display_deadline_wait_count, $rt->display_deadline_wait_last_ticks, $rt->display_deadline_due_count
printf "rtos power recheck req/send/consume = %u / 0x%x / %u\n", $rt->stop2_lpbam_power_recheck_request_count, $rt->stop2_lpbam_power_recheck_send_status, $rt->stop2_lpbam_power_recheck_consume_count
printf "rtos power recheck request/consume tick = %u / %u\n", $rt->stop2_lpbam_power_recheck_request_tick, $rt->stop2_lpbam_power_recheck_consume_tick
printf "rtos abort count/tick/send/wait/ack/owner = %u / %u / 0x%x / 0x%x / 0x%x / 0x%x\n", $rt->stop2_lpbam_abort_request_count, $rt->stop2_lpbam_abort_last_tick, $rt->stop2_lpbam_abort_send_status, $rt->stop2_lpbam_abort_wait_status, $rt->stop2_lpbam_abort_ack_flags, $rt->stop2_lpbam_abort_owner_status
printf "rtos abort resume phase/status/tick = %u / 0x%x / %u\n", $rt->stop2_lpbam_abort_resume_phase, $rt->stop2_lpbam_abort_resume_status, $rt->stop2_lpbam_abort_resume_tick
printf "late abort test count/tick/status/block = %u / %u / 0x%x / 0x%x\n", $rt->stop2_lpbam_abort_late_test_count, $rt->stop2_lpbam_abort_late_test_tick, $rt->stop2_lpbam_abort_late_test_status, $rt->stop2_lpbam_abort_late_test_blocker_mask
printf "late blocker count = %u\n", $rt->stop2_lpbam_late_blocker_count
printf "auto check/entry/skip tick/next = %u / %u / %u / %u / %u\n", $rt->stop2_auto_check_count, $rt->stop2_auto_entry_count, $rt->stop2_auto_skip_count, $rt->stop2_auto_last_tick, $rt->stop2_auto_next_tick
printf "auto idle start/live/required = %u / %u / %u\n", $rt->stop2_auto_idle_start_tick, $rt->stop2_auto_idle_ticks, $rt->stop2_auto_required_idle_ticks
printf "auto block/pending = 0x%x / 0x%x\n", $rt->stop2_auto_blocker_mask, $rt->stop2_auto_pending_mask
printf "auto clock-release recheck count/tick/requester = %u / %u / %u\n", $rt->stop2_auto_clock_release_recheck_count, $rt->stop2_auto_clock_release_recheck_tick, $rt->stop2_auto_clock_release_recheck_requester
printf "auto display-clock idle preserve count/tick = %u / %u\n", $rt->stop2_auto_clock_idle_preserve_count, $rt->stop2_auto_clock_idle_preserve_tick
printf "owner stop2 count/start/WFI/wake/end = %u / %u / %u / %u / %u\n", $sm->stop2_request_count, $sm->stop2_start_tick, $sm->stop2_wfi_tick, $sm->stop2_wake_tick, $sm->stop2_end_tick
printf "power quiesce start/end commit-to-WFI ticks = %u / %u / %u\n", $sm->power_quiesce_start_tick, $sm->power_quiesce_end_tick, ($sm->stop2_wfi_tick - $ow->display_lpbam_commit_tick)
printf "pre-WFI hold enabled/active/count/tick/skip = %u / %u / %u / %u / %u\n", $sm->stop2_pre_wfi_hold_enabled, $sm->stop2_pre_wfi_hold_active, $sm->stop2_pre_wfi_hold_count, $sm->stop2_pre_wfi_hold_tick, $sm->stop2_pre_wfi_hold_skip_count
printf "pre-WFI RCC SRDAMR SPI CR1/CFG1/CFG2/AUTOCR/SR = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", $sm->stop2_pre_wfi_rcc_srdamr, $sm->stop2_pre_wfi_spi_cr1, $sm->stop2_pre_wfi_spi_cfg1, $sm->stop2_pre_wfi_spi_cfg2, $sm->stop2_pre_wfi_spi_autocr, $sm->stop2_pre_wfi_spi_sr
printf "pre-WFI LPTIM CR/CFGR/CCMR1/ARR/CMP = 0x%x / 0x%x / 0x%x / %u / %u\n", $sm->stop2_pre_wfi_lptim_cr, $sm->stop2_pre_wfi_lptim_cfgr, $sm->stop2_pre_wfi_lptim_ccmr1, $sm->stop2_pre_wfi_lptim_arr, $sm->stop2_pre_wfi_lptim_cmp
printf "SRDRUN test flag/active/count/tick = %u / %u / %u / %u\n", g_ps_hw6_power_stop2_srdrun_test_enable, $sm->stop2_srdrun_test_active, $sm->stop2_srdrun_test_count, $sm->stop2_srdrun_test_tick
printf "SRDRUN CR2 before/forced/after = 0x%x / 0x%x / 0x%x\n", $sm->stop2_srdrun_cr2_before, $sm->stop2_srdrun_cr2_forced, $sm->stop2_srdrun_cr2_after
printf "APB3 /1 test flag/active/count/tick = %u / %u / %u / %u\n", g_ps_hw6_power_stop2_apb3_div1_test_enable, $sm->stop2_apb3_div1_test_active, $sm->stop2_apb3_div1_test_count, $sm->stop2_apb3_div1_test_tick
printf "APB3 CFGR3 before/forced/after = 0x%x / 0x%x / 0x%x\n", $sm->stop2_apb3_cfgr3_before, $sm->stop2_apb3_cfgr3_forced, $sm->stop2_apb3_cfgr3_after
printf "SPI auto-trigger test flag/active/count/tick = %u / %u / %u / %u\n", g_ps_hw6_power_stop2_spi_autotrigger_test_enable, $sm->stop2_spi_autotrigger_test_active, $sm->stop2_spi_autotrigger_test_count, $sm->stop2_spi_autotrigger_test_tick
printf "SPI AUTOCR before/forced/after = 0x%x / 0x%x / 0x%x\n", $sm->stop2_spi_autocr_before, $sm->stop2_spi_autocr_forced, $sm->stop2_spi_autocr_after
printf "post-WFI snapshot count/tick/break = %u / %u / %u\n", $sm->stop2_post_wfi_snapshot_count, $sm->stop2_post_wfi_snapshot_tick, $sm->stop2_post_wfi_break_count
printf "post-WFI RCC SRDAMR/CFGR3 PWR CR2 SCB ICSR = 0x%x / 0x%x / 0x%x / 0x%x\n", $sm->stop2_post_wfi_rcc_srdamr, $sm->stop2_post_wfi_rcc_cfgr3, $sm->stop2_post_wfi_pwr_cr2, $sm->stop2_post_wfi_scb_icsr
printf "post-WFI NVIC ISPR0/1 IABR0/1 = 0x%x / 0x%x / 0x%x / 0x%x\n", $sm->stop2_post_wfi_nvic_ispr0, $sm->stop2_post_wfi_nvic_ispr1, $sm->stop2_post_wfi_nvic_iabr0, $sm->stop2_post_wfi_nvic_iabr1
printf "post-WFI LPDMA MISR CLBAR CSR CCR = 0x%x / 0x%x / 0x%x / 0x%x\n", $sm->stop2_post_wfi_lpdma_misr, $sm->stop2_post_wfi_dma_clbar, $sm->stop2_post_wfi_dma_csr, $sm->stop2_post_wfi_dma_ccr
printf "post-WFI DMA CTR1/CTR2/CBR1 = 0x%x / 0x%x / 0x%x (remaining=%u)\n", $sm->stop2_post_wfi_dma_ctr1, $sm->stop2_post_wfi_dma_ctr2, $sm->stop2_post_wfi_dma_cbr1, ($sm->stop2_post_wfi_dma_cbr1 & 0xffff)
printf "post-WFI DMA CSAR/CDAR/CLLR = 0x%x / 0x%x / 0x%x\n", $sm->stop2_post_wfi_dma_csar, $sm->stop2_post_wfi_dma_cdar, $sm->stop2_post_wfi_dma_cllr
printf "post-WFI SPI CR1/CR2/CFG1/CFG2 = 0x%x / 0x%x / 0x%x / 0x%x\n", $sm->stop2_post_wfi_spi_cr1, $sm->stop2_post_wfi_spi_cr2, $sm->stop2_post_wfi_spi_cfg1, $sm->stop2_post_wfi_spi_cfg2
printf "post-WFI SPI IER/SR/AUTOCR = 0x%x / 0x%x / 0x%x\n", $sm->stop2_post_wfi_spi_ier, $sm->stop2_post_wfi_spi_sr, $sm->stop2_post_wfi_spi_autocr
printf "post-WFI LPTIM ISR/DIER/CFGR/CR/CCMR1 = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x\n", $sm->stop2_post_wfi_lptim_isr, $sm->stop2_post_wfi_lptim_dier, $sm->stop2_post_wfi_lptim_cfgr, $sm->stop2_post_wfi_lptim_cr, $sm->stop2_post_wfi_lptim_ccmr1
printf "post-WFI LPTIM ARR/CMP/CNT = %u / %u / %u\n", $sm->stop2_post_wfi_lptim_arr, $sm->stop2_post_wfi_lptim_cmp, $sm->stop2_post_wfi_lptim_cnt
printf "gpio park default/override/active = 0x%x / 0x%x / 0x%x\n", $sm->stop2_gpio_park_group_default_mask, $sm->stop2_gpio_park_group_override_mask, $sm->stop2_gpio_park_group_active_mask
printf "blockers: INPUT=0x800 LPBAM_NOT_READY=0x2000; pending LPBAM=0x2; status: HAL_OK=0x0 HAL_ERROR=0x1 UNAVAILABLE=0xfffffffe NOT_RUN=0xffffffff\n"
printf "display backends: NONE=0 HELD_FRAME=1 LPBAM=2\n"
