printf "--- HW6 TMAG3001 sleep audit scaffold ---\n"
printf "owner magic/version = 0x%lx / %lu\n", g_ps_hw6_owner_sm_probe.magic, g_ps_hw6_owner_sm_probe.version
printf "request/count/status = %lu / %lu / 0x%lx\n", g_ps_hw6_joystick_sleep_audit_request, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_request_count, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_status
printf "ticks start/end = %lu / %lu\n", g_ps_hw6_owner_sm_probe.joystick_sleep_audit_start_tick, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_end_tick
printf "ready/identity id/mfg/match = 0x%lx / 0x%lx / 0x%lx / 0x%lx 0x%lx / %lu\n", g_ps_hw6_owner_sm_probe.joystick_sleep_audit_ready_status, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_identity_status, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_device_id, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_manufacturer_lsb, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_manufacturer_msb, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_identity_match
printf "sensor cfg1 before/after/ver = 0x%lx / 0x%lx / 0x%lx\n", g_ps_hw6_owner_sm_probe.joystick_sleep_audit_sensor_config1_before, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_sensor_config1_after, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_sensor_config1_verify_status
printf "int cfg1 before/target/after/ver = 0x%lx / 0x%lx / 0x%lx / 0x%lx\n", g_ps_hw6_owner_sm_probe.joystick_sleep_audit_int_config1_before, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_int_config1_target, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_int_config1_after, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_int_config1_verify_status
printf "device cfg2 before/after/sleep/ver = 0x%lx / 0x%lx / 0x%lx / 0x%lx\n", g_ps_hw6_owner_sm_probe.joystick_sleep_audit_device_config2_before, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_device_config2_after, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_device_config2_sleep, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_device_config2_verify_status
printf "write/verify masks = 0x%lx / 0x%lx\n", g_ps_hw6_owner_sm_probe.joystick_sleep_audit_write_ok_mask, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_verify_ok_mask
printf "sleep write/committed/post-read-omitted = 0x%lx / %lu / %lu\n", g_ps_hw6_owner_sm_probe.joystick_sleep_audit_sleep_write_status, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_terminal_sleep_committed, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_post_sleep_read_omitted
printf "i2c state/error last HAL/error = 0x%lx / 0x%lx / 0x%lx / 0x%lx\n", g_ps_hw6_owner_sm_probe.joystick_sleep_audit_i2c_state_after, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_i2c_error_after, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_last_hal_status, g_ps_hw6_owner_sm_probe.joystick_sleep_audit_last_hal_error
printf "driver state/status ops = %lu / 0x%lx / %lu\n", g_ps_hw6_owner_sm_probe.joystick_driver_state, g_ps_hw6_owner_sm_probe.joystick_driver_last_status, g_ps_hw6_owner_sm_probe.joystick_driver_operation_count
printf "expected: status 0x0, int cfg1 target/after 0x1, write mask 0xf, verify mask 0x7, committed 1, post-read-omitted 1\n"
printf "status: HAL_OK=0x0 HAL_ERROR=0x1 NOT_RUN=0xffffffff\n"