set pagination off
printf "--- HW6 production scene waiting visual ---\n"
printf "api/publish/reject/clear/resolve = %u / %u / %u / %u / %u\n", g_display_renderer_scene_waiting_probe.api_version, g_display_renderer_scene_waiting_probe.publish_count, g_display_renderer_scene_waiting_probe.reject_count, g_display_renderer_scene_waiting_probe.clear_count, g_display_renderer_scene_waiting_probe.resolve_count
printf "active/presentation/steps/elements = %u / %u / %u / %u\n", g_display_renderer_scene_waiting_probe.active, g_display_renderer_scene_waiting_probe.presentation_id, g_display_renderer_scene_waiting_probe.sequence_step_count, g_display_renderer_scene_waiting_probe.element_count
printf "publish/resolve status = 0x%x / 0x%x\n", g_display_renderer_scene_waiting_probe.last_status, g_display_renderer_scene_waiting_probe.last_resolve_status
printf "descriptor api/presentation/quantum/steps = %u / %u / %u / %u\n", s_display_scene_waiting_visual.api_version, s_display_scene_waiting_visual.presentation_id, s_display_scene_waiting_visual.phase_quantum_ms, s_display_scene_waiting_visual.sequence_step_count
printf "descriptor cycle/rebase/elements = %u / %u / %u\n", s_display_scene_waiting_visual.cycle_policy, s_display_scene_waiting_visual.rebase_policy, s_display_scene_waiting_visual.element_count
printf "element id/source/phases/bounds = %u / %u / %u / %u,%u %ux%u\n", s_display_scene_waiting_visual.elements[0].element_id, s_display_scene_waiting_visual.elements[0].visual_source_id, s_display_scene_waiting_visual.elements[0].phase_count, s_display_scene_waiting_visual.elements[0].logical_bounds.x, s_display_scene_waiting_visual.elements[0].logical_bounds.y, s_display_scene_waiting_visual.elements[0].logical_bounds.width, s_display_scene_waiting_visual.elements[0].logical_bounds.height
printf "element phase visuals = %u / %u / %u / %u\n", s_display_scene_waiting_visual.elements[0].phase_visual_id[0], s_display_scene_waiting_visual.elements[0].phase_visual_id[1], s_display_scene_waiting_visual.elements[0].phase_visual_id[2], s_display_scene_waiting_visual.elements[0].phase_visual_id[3]
printf "element sequence = %u / %u / %u / %u\n", s_display_scene_waiting_visual.elements[0].sequence_phase[0], s_display_scene_waiting_visual.elements[0].sequence_phase[1], s_display_scene_waiting_visual.elements[0].sequence_phase[2], s_display_scene_waiting_visual.elements[0].sequence_phase[3]
printf "expected shell cursor: api=1 active=1 presentation=1 steps=4 elements=1 statuses=0/0 source=1 phases=2 sequence=0/1/0/1\n"
printf "--- end HW6 production scene waiting visual ---\n"
