set pagination off
printf "--- HW6 production scene waiting visual ---\n"
printf "api/publish/reject/clear/resolve = %u / %u / %u / %u / %u\n", g_display_renderer_scene_waiting_probe.api_version, g_display_renderer_scene_waiting_probe.publish_count, g_display_renderer_scene_waiting_probe.reject_count, g_display_renderer_scene_waiting_probe.clear_count, g_display_renderer_scene_waiting_probe.resolve_count
printf "active/presentation/steps/elements = %u / %u / %u / %u\n", g_display_renderer_scene_waiting_probe.active, g_display_renderer_scene_waiting_probe.presentation_id, g_display_renderer_scene_waiting_probe.sequence_step_count, g_display_renderer_scene_waiting_probe.element_count
printf "settled step = %u\n", g_display_renderer_scene_waiting_probe.settled_sequence_step
printf "publish/resolve status = 0x%x / 0x%x\n", g_display_renderer_scene_waiting_probe.last_status, g_display_renderer_scene_waiting_probe.last_resolve_status
printf "descriptor api/presentation/quantum/steps/settled = %u / %u / %u / %u / %u\n", s_display_scene_waiting_visual.api_version, s_display_scene_waiting_visual.presentation_id, s_display_scene_waiting_visual.phase_quantum_ms, s_display_scene_waiting_visual.sequence_step_count, s_display_scene_waiting_visual.settled_sequence_step
printf "descriptor cycle/rebase/elements = %u / %u / %u\n", s_display_scene_waiting_visual.cycle_policy, s_display_scene_waiting_visual.rebase_policy, s_display_scene_waiting_visual.element_count
printf "element id/source/phases/bounds = %u / %u / %u / %u,%u %ux%u\n", s_display_scene_waiting_visual.elements[0].element_id, s_display_scene_waiting_visual.elements[0].visual_source_id, s_display_scene_waiting_visual.elements[0].phase_count, s_display_scene_waiting_visual.elements[0].logical_bounds.x, s_display_scene_waiting_visual.elements[0].logical_bounds.y, s_display_scene_waiting_visual.elements[0].logical_bounds.width, s_display_scene_waiting_visual.elements[0].logical_bounds.height
printf "element phase visuals = %u / %u / %u / %u\n", s_display_scene_waiting_visual.elements[0].phase_visual_id[0], s_display_scene_waiting_visual.elements[0].phase_visual_id[1], s_display_scene_waiting_visual.elements[0].phase_visual_id[2], s_display_scene_waiting_visual.elements[0].phase_visual_id[3]
printf "element 0 sequence = %u / %u / %u / %u / %u / %u\n", s_display_scene_waiting_visual.elements[0].sequence_phase[0], s_display_scene_waiting_visual.elements[0].sequence_phase[1], s_display_scene_waiting_visual.elements[0].sequence_phase[2], s_display_scene_waiting_visual.elements[0].sequence_phase[3], s_display_scene_waiting_visual.elements[0].sequence_phase[4], s_display_scene_waiting_visual.elements[0].sequence_phase[5]
printf "element 1 id/source/phases/sequence = %u / %u / %u / %u,%u,%u,%u,%u,%u\n", s_display_scene_waiting_visual.elements[1].element_id, s_display_scene_waiting_visual.elements[1].visual_source_id, s_display_scene_waiting_visual.elements[1].phase_count, s_display_scene_waiting_visual.elements[1].sequence_phase[0], s_display_scene_waiting_visual.elements[1].sequence_phase[1], s_display_scene_waiting_visual.elements[1].sequence_phase[2], s_display_scene_waiting_visual.elements[1].sequence_phase[3], s_display_scene_waiting_visual.elements[1].sequence_phase[4], s_display_scene_waiting_visual.elements[1].sequence_phase[5]
printf "owner api/snapshot/presentation/steps/settled/cadence/elements = %u / 0x%x / %u / %u / %u / %u / %u\n", g_ps_hw6_owner_probe.version, g_ps_hw6_owner_probe.display_waiting_snapshot_status, g_ps_hw6_owner_probe.display_waiting_presentation_id, g_ps_hw6_owner_probe.display_waiting_sequence_frame_count, g_ps_hw6_owner_probe.display_waiting_settled_sequence_frame, g_ps_hw6_owner_probe.display_waiting_cadence_ms, g_ps_hw6_owner_probe.display_waiting_element_count
printf "owner sequence phases = %u / %u / %u / %u / %u / %u\n", g_ps_hw6_owner_probe.display_waiting_sequence_phase[0], g_ps_hw6_owner_probe.display_waiting_sequence_phase[1], g_ps_hw6_owner_probe.display_waiting_sequence_phase[2], g_ps_hw6_owner_probe.display_waiting_sequence_phase[3], g_ps_hw6_owner_probe.display_waiting_sequence_phase[4], g_ps_hw6_owner_probe.display_waiting_sequence_phase[5]
printf "awake frame/count/phase/next = %u / %u / %u / %u\n", ps_display_waiting_sequence_frame, ps_display_waiting_sequence_count, ps_display_blink_visible, ps_display_blink_next_tick
printf "same-presentation preserve/rebase/frame/deadline/status = %u / %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.display_waiting_preserve_count, g_ps_hw6_rtos_probe.display_waiting_rebase_count, g_ps_hw6_rtos_probe.display_waiting_preserve_frame, g_ps_hw6_rtos_probe.display_waiting_preserve_deadline_tick, g_ps_hw6_rtos_probe.display_waiting_preserve_status
printf "expected default: api=2 presentation=1 steps=4 settled=1 elements=1; proof: presentation=4 steps=6 settled=1 elements=2 cursor=0,1,0,1,0,1 marker=2,0,1,2,0,1; statuses=0\n"
printf "--- end HW6 production scene waiting visual ---\n"
