set pagination off
printf "--- HW6 USB atomic A/B package install and launch ---\n"
printf "rtos/owner/source api = %u / %u / %u\n", g_ps_hw6_rtos_probe.version, g_ps_hw6_owner_sm_probe.version, g_ps_package_source_probe.api_version
printf "staging install request/status load/status/reason = %u / 0x%x / 0x%x / 0x%x / %u\n", g_ps_hw6_owner_sm_probe.package_install_stub_request_count, g_ps_hw6_owner_sm_probe.package_install_stub_last_status, g_ps_hw6_owner_sm_probe.package_install_stub_load_status, g_ps_hw6_owner_sm_probe.package_install_stub_persistent_status, g_ps_hw6_owner_sm_probe.package_install_stub_load_reason
printf "staging file/read/declared/capacity = %u / %u / %u / %u\n", g_ps_hw6_owner_sm_probe.package_install_stub_file_size, g_ps_hw6_owner_sm_probe.package_install_stub_bytes_read, g_ps_hw6_owner_sm_probe.package_install_stub_declared_size, g_ps_hw6_owner_sm_probe.package_install_stub_capacity
printf "staging file/FileX/LevelX close = 0x%x / 0x%x / 0x%x\n", g_ps_hw6_owner_sm_probe.package_install_stub_file_close_status, g_ps_hw6_owner_sm_probe.package_install_stub_fx_close_status, g_ps_hw6_owner_sm_probe.package_install_stub_lx_close_status
printf "A/B source record/slot target record/slot/generation = %u / %u / %u / %u / %u\n", g_ps_storage_package_install_probe.source_record, g_ps_storage_package_install_probe.source_slot, g_ps_storage_package_install_probe.target_record, g_ps_storage_package_install_probe.target_slot, g_ps_storage_package_install_probe.target_generation
printf "A/B target package/index address = 0x%x / 0x%x\n", g_ps_storage_package_install_probe.target_package_start, g_ps_storage_package_install_probe.target_index_start
printf "package erase/program/verify status bytes/mismatches = 0x%x / 0x%x / 0x%x / %u / %u\n", g_ps_storage_package_install_probe.package_erase_status, g_ps_storage_package_install_probe.package_program_status, g_ps_storage_package_install_probe.package_verify_status, g_ps_storage_package_install_probe.package_verify_bytes, g_ps_storage_package_install_probe.package_verify_mismatches
printf "index erase/program/verify status mismatches/crc = 0x%x / 0x%x / 0x%x / %u / 0x%x\n", g_ps_storage_package_install_probe.index_erase_status, g_ps_storage_package_install_probe.index_program_status, g_ps_storage_package_install_probe.index_verify_status, g_ps_storage_package_install_probe.index_verify_mismatches, g_ps_storage_package_install_probe.index_crc32
printf "commit program/verify/marker rescan/status/stage = 0x%x / 0x%x / 0x%x / 0x%x / 0x%x / %u\n", g_ps_storage_package_install_probe.commit_status, g_ps_storage_package_install_probe.commit_verify_status, g_ps_storage_package_install_probe.commit_marker, g_ps_storage_package_install_probe.rescan_status, g_ps_storage_package_install_probe.status, g_ps_storage_package_install_probe.stage
printf "selected record/slot/generation valid/available = %u / %u / %u / %u / %u\n", g_ps_storage_package_index_probe.selected_record, g_ps_storage_package_index_probe.selected_slot, g_ps_storage_package_index_probe.selected_generation, g_ps_storage_package_index_probe.valid_record_count, g_ps_storage_package_index_probe.installed_available
printf "owner persistent target record/slot/generation publish/source = %u / %u / %u / 0x%x / %u\n", g_ps_hw6_owner_sm_probe.package_install_stub_target_record, g_ps_hw6_owner_sm_probe.package_install_stub_target_slot, g_ps_hw6_owner_sm_probe.package_install_stub_target_generation, g_ps_hw6_owner_sm_probe.package_install_stub_publish_status, g_ps_hw6_owner_sm_probe.package_install_stub_source
printf "resident selected/source/available/generation/bytes = %u / %u / %u / %u / %u\n", g_ps_package_source_probe.selected_source, g_ps_package_source_probe.resident_source, g_ps_package_source_probe.staged_available, g_ps_package_source_probe.generation, g_ps_package_source_probe.package_size
printf "runtime complete/launch send = 0x%x / 0x%x\n", g_ps_hw6_rtos_probe.package_install_runtime_complete_send_status, g_ps_hw6_rtos_probe.package_install_runtime_launch_send_status
printf "scene active/activation/source egg/hash = %u / 0x%x / %u / 0x%x / 0x%x\n", g_ps_scene_runtime_probe.active, g_ps_scene_runtime_probe.activation_status, g_ps_scene_runtime_probe.package_source, g_ps_egg_state_loader_probe.last_status, g_ps_hw6_hash_probe.last_status
printf "UI page/package state runtime class/lifecycle STOP2 entries = %u / %u / %u / %u / %u\n", g_ps_ui_router_probe.current_page, g_ps_ui_router_probe.package_state, g_ps_hw6_rtos_probe.runtime_current_class, g_ps_hw6_rtos_probe.runtime_lifecycle, g_ps_hw6_rtos_probe.stop2_auto_entry_count
printf "owner storage/flash state OSPI state/error = %u / %u / 0x%x / 0x%x\n", g_ps_hw6_owner_sm_probe.current_state[7], g_ps_hw6_owner_sm_probe.current_state[8], hospi1.State, hospi1.ErrorCode
printf "expected: APIs=58/61/3 staging/install/persistent/publish=0, file=read=declared, closes=0, A/B stage=11 status=0 marker=0x54494d43, selected target generation matches resident generation, source=3 available=1, runtime sends=0/0, scene active/activation/source=1/0/3, egg/hash=0/0, package state=INSTALLED\n"
printf "--- end HW6 USB atomic A/B package install and launch ---\n"
