set pagination off
set print pretty off
printf "--- HW6 persistent package index scan ---\n"
printf "api/scan/status = %lu / %lu / 0x%lx\n", g_ps_storage_package_index_probe.api_version, g_ps_storage_package_index_probe.scan_count, g_ps_storage_package_index_probe.status
printf "index start/length package start/length = 0x%lx / %lu / 0x%lx / %lu\n", g_ps_storage_package_index_probe.index_region_start, g_ps_storage_package_index_probe.index_region_length, g_ps_storage_package_index_probe.package_region_start, g_ps_storage_package_index_probe.package_region_length
printf "valid/available selected record/slot/generation = %lu / %lu / %lu / %lu / %lu\n", g_ps_storage_package_index_probe.valid_record_count, g_ps_storage_package_index_probe.installed_available, g_ps_storage_package_index_probe.selected_record, g_ps_storage_package_index_probe.selected_slot, g_ps_storage_package_index_probe.selected_generation
printf "selected package start/size reason = 0x%lx / %lu / %lu\n", g_ps_storage_package_index_probe.selected_package_start, g_ps_storage_package_index_probe.selected_package_size, g_ps_storage_package_index_probe.selection_reason
printf "record 0 read/valid/reason magic/marker/gen/slot/size crc stored/computed = 0x%lx / %lu / %lu / 0x%lx / 0x%lx / %lu / %lu / %lu / 0x%lx / 0x%lx\n", g_ps_storage_package_index_probe.record[0].read_status, g_ps_storage_package_index_probe.record[0].valid, g_ps_storage_package_index_probe.record[0].reason, g_ps_storage_package_index_probe.record[0].magic, g_ps_storage_package_index_probe.record[0].commit_marker, g_ps_storage_package_index_probe.record[0].generation, g_ps_storage_package_index_probe.record[0].active_slot, g_ps_storage_package_index_probe.record[0].package_size, g_ps_storage_package_index_probe.record[0].stored_crc32, g_ps_storage_package_index_probe.record[0].computed_crc32
printf "record 1 read/valid/reason magic/marker/gen/slot/size crc stored/computed = 0x%lx / %lu / %lu / 0x%lx / 0x%lx / %lu / %lu / %lu / 0x%lx / 0x%lx\n", g_ps_storage_package_index_probe.record[1].read_status, g_ps_storage_package_index_probe.record[1].valid, g_ps_storage_package_index_probe.record[1].reason, g_ps_storage_package_index_probe.record[1].magic, g_ps_storage_package_index_probe.record[1].commit_marker, g_ps_storage_package_index_probe.record[1].generation, g_ps_storage_package_index_probe.record[1].active_slot, g_ps_storage_package_index_probe.record[1].package_size, g_ps_storage_package_index_probe.record[1].stored_crc32, g_ps_storage_package_index_probe.record[1].computed_crc32
printf "reasons: NONE=0 ARGUMENT=1 LAYOUT=2 READ=3 UNCOMMITTED=4 FORMAT=5 CRC=6 BOUNDS=7 RESERVED=8 CONFLICT=9\n"
printf "expected erased index: valid/available=0/0 and both records reason=4\n"
printf "expected installed index: available=1, selected record/slot/generation names the newest valid record, selected package address/size are nonzero, and selected record CRCs match\n"
printf "--- end HW6 persistent package index scan ---\n"
