set pagination off
printf "--- HW6 package interaction lifecycle ---\n"
printf "api rtos/scene/loader/owner/ui = %u / %u / %u / %u / %u\n", g_ps_hw6_rtos_probe.version, g_ps_scene_runtime_probe.api_version, g_ps_egg_state_loader_probe.api_version, g_ps_hw6_owner_sm_probe.version, g_ps_ui_router_probe.api_version
printf "loader interaction mode/route/meaningful mask = %u / %u / 0x%x\n", g_ps_egg_state_loader_probe.interaction_mode, g_ps_egg_state_loader_probe.inactive_route, g_ps_egg_state_loader_probe.meaningful_input_mask
printf "scene interaction mode/route/meaningful mask = %u / %u / 0x%x\n", g_ps_scene_runtime_probe.descriptor_interaction_mode, g_ps_scene_runtime_probe.descriptor_inactive_route, g_ps_scene_runtime_probe.descriptor_meaningful_input_mask
printf "runtime interaction mode/state/deadline = %u / %u / %u\n", g_ps_hw6_rtos_probe.runtime_interaction_mode, g_ps_hw6_rtos_probe.runtime_interaction_state, g_ps_hw6_rtos_probe.runtime_interaction_deadline_tick
printf "runtime activity refresh/active/inactive = %u / %u / %u\n", g_ps_hw6_rtos_probe.runtime_interaction_activity_refresh_count, g_ps_hw6_rtos_probe.runtime_interaction_active_count, g_ps_hw6_rtos_probe.runtime_interaction_inactive_count
printf "runtime active/inactive ticks = %u / %u\n", g_ps_hw6_rtos_probe.runtime_interaction_active_tick, g_ps_hw6_rtos_probe.runtime_interaction_inactive_tick
printf "runtime epoch / RTC arm count/status/clock/counter = %u / %u / 0x%x / 0x%x / %u\n", g_ps_hw6_rtos_probe.runtime_interaction_epoch, g_ps_hw6_rtos_probe.runtime_interaction_rtc_arm_count, g_ps_hw6_rtos_probe.runtime_interaction_rtc_arm_status, g_ps_hw6_rtos_probe.runtime_interaction_rtc_clock, g_ps_hw6_rtos_probe.runtime_interaction_rtc_counter
printf "runtime RTC remaining/elapsed/expire/command = %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.runtime_interaction_rtc_remaining_ticks, g_ps_hw6_rtos_probe.runtime_interaction_rtc_elapsed_ticks, g_ps_hw6_rtos_probe.runtime_interaction_rtc_expire_count, g_ps_hw6_rtos_probe.runtime_interaction_rtc_command_status
printf "cue active/show/clear/deadline = %u / %u / %u / %u\n", g_ps_hw6_rtos_probe.runtime_interaction_cue_active, g_ps_hw6_rtos_probe.runtime_interaction_cue_show_count, g_ps_hw6_rtos_probe.runtime_interaction_cue_clear_count, g_ps_hw6_rtos_probe.runtime_interaction_cue_deadline_tick
printf "activation active/frame/start/complete/deadline/status = %u / %u / %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.runtime_interaction_activation_active, g_ps_hw6_rtos_probe.runtime_interaction_activation_frame, g_ps_hw6_rtos_probe.runtime_interaction_activation_count, g_ps_hw6_rtos_probe.runtime_interaction_activation_complete_count, g_ps_hw6_rtos_probe.runtime_interaction_activation_deadline_tick, g_ps_hw6_rtos_probe.runtime_interaction_activation_render_status
printf "inactive suppressed/start count/status = %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.runtime_interaction_suppressed_input_count, g_ps_hw6_rtos_probe.runtime_interaction_start_count, g_ps_hw6_rtos_probe.runtime_interaction_start_status
printf "joystick wake allowed/expected pin/wake C/park C = %u / 0x%x / 0x%x / 0x%x\n", g_ps_hw6_rtos_probe.runtime_interaction_joystick_wake_allowed, g_ps_hw6_owner_sm_probe.stop2_expected_wake_pin, g_ps_hw6_owner_sm_probe.stop2_gpio_wake_mask[2], g_ps_hw6_owner_sm_probe.stop2_gpio_park_mask[2]
printf "joystick sleep arm count/status = %u / 0x%x\n", g_ps_hw6_owner_sm_probe.joystick_wake_sleep_arm_count, g_ps_hw6_owner_sm_probe.joystick_sleep_write_status
printf "runtime class/lifecycle scene active = %u / %u / %u\n", g_ps_hw6_rtos_probe.runtime_current_class, g_ps_hw6_rtos_probe.runtime_lifecycle, g_ps_scene_runtime_probe.active
printf "UI router page / display page/primitive = %u / %u / %u\n", g_ps_ui_router_probe.current_page, g_ps_hw6_owner_probe.display_ui_page, g_ps_hw6_owner_probe.display_ui_primitive_id
printf "STOP2 entries/block/pending = %u / 0x%x / 0x%x\n", g_ps_hw6_rtos_probe.stop2_auto_entry_count, g_ps_hw6_rtos_probe.stop2_auto_blocker_mask, g_ps_hw6_rtos_probe.stop2_auto_pending_mask
printf "modes: CONTINUOUS=1 TIMEOUT=2; states: NONE=0 ACTIVE=1 INACTIVE=2; cue page/primitive=9/6 activation page/primitive=10/7\n"
printf "expected timeout flow: mode=2 starts ACTIVE; after 10 s state=2 and joystick wake allowed=0; A/B/L/R shows one bounded cue then returns to page 6 and STOP2; START returns state=1, runs one three-frame activation, and restores joystick wake\n"
printf "--- end package interaction lifecycle ---\n"
