set pagination off
printf "--- HW6 STATE_SCENE reactive loop ---\n"
printf "scene api/type/active/status = %u / %u / %u / 0x%x\n", g_ps_scene_runtime_probe.api_version, g_ps_scene_runtime_probe.scene_type, g_ps_scene_runtime_probe.active, g_ps_scene_runtime_probe.last_status
printf "render model resolve/status scene/state/visual = %u / 0x%x / %u / %u / %u\n", g_ps_scene_runtime_probe.render_model_resolve_count, g_ps_scene_runtime_probe.render_model_status, g_ps_scene_runtime_probe.render_model_scene_id, g_ps_scene_runtime_probe.render_model_state_id, g_ps_scene_runtime_probe.render_model_visual_binding_id
printf "render model content/timeline/focus = %u / %u / %u\n", g_ps_scene_runtime_probe.render_model_content_revision, g_ps_scene_runtime_probe.render_model_timeline_revision, g_ps_scene_runtime_probe.render_model_selected_row
printf "scene enter/exit/action/change = %u / %u / %u / %u\n", g_ps_scene_runtime_probe.enter_count, g_ps_scene_runtime_probe.exit_count, g_ps_scene_runtime_probe.action_count, g_ps_scene_runtime_probe.state_change_count
printf "scene state/content revision/timeline revision/last action = %u / %u / %u / %u\n", g_ps_scene_runtime_probe.state_index, g_ps_scene_runtime_probe.state_revision, g_ps_scene_runtime_probe.timeline_revision, g_ps_scene_runtime_probe.last_action
printf "scene descriptor validate/scene/states/transitions = %u / %u / %u / %u\n", g_ps_scene_runtime_probe.descriptor_validate_count, g_ps_scene_runtime_probe.scene_id, g_ps_scene_runtime_probe.descriptor_state_count, g_ps_scene_runtime_probe.descriptor_transition_count
printf "scene descriptor visual bindings = %u\n", g_ps_scene_runtime_probe.descriptor_visual_binding_count
printf "scene descriptor routes/variables/guards/actions = %u / %u / %u / %u\n", g_ps_scene_runtime_probe.descriptor_input_route_count, g_ps_scene_runtime_probe.descriptor_variable_count, g_ps_scene_runtime_probe.descriptor_guard_count, g_ps_scene_runtime_probe.descriptor_action_count
printf "scene state id/visual/focus transition match/miss = %u / %u / %u / %u / %u\n", g_ps_scene_runtime_probe.state_id, g_ps_scene_runtime_probe.visual_binding_id, g_ps_scene_runtime_probe.focus_index, g_ps_scene_runtime_probe.transition_match_count, g_ps_scene_runtime_probe.transition_miss_count
printf "scene route match/miss guard eval/pass/reject = %u / %u / %u / %u / %u\n", g_ps_scene_runtime_probe.input_route_match_count, g_ps_scene_runtime_probe.input_route_miss_count, g_ps_scene_runtime_probe.guard_evaluate_count, g_ps_scene_runtime_probe.guard_pass_count, g_ps_scene_runtime_probe.guard_reject_count
printf "scene action commit/error event/transition/variable = %u / %u / %u / %u / %d\n", g_ps_scene_runtime_probe.action_commit_count, g_ps_scene_runtime_probe.action_error_count, g_ps_scene_runtime_probe.last_scene_event_id, g_ps_scene_runtime_probe.last_transition_id, g_ps_scene_runtime_probe.primary_variable_value
printf "runtime class/exec/lifecycle/caps = %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.runtime_current_class, g_ps_hw6_rtos_probe.runtime_execution, g_ps_hw6_rtos_probe.runtime_lifecycle, g_ps_hw6_rtos_probe.runtime_active_capabilities
printf "input policy runtime deliver/target/status = %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.input_policy_runtime_deliver_count, g_ps_hw6_rtos_probe.input_policy_last_target, g_ps_hw6_rtos_probe.input_policy_last_status
printf "runtime input event/button/id/status = %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.runtime_input_event_count, g_ps_hw6_rtos_probe.runtime_input_button_count, g_ps_hw6_rtos_probe.runtime_input_last_button_id, g_ps_hw6_rtos_probe.runtime_input_last_status
printf "ui page/focus = %u / %u\n", g_ps_ui_router_probe.current_page, g_ps_ui_router_probe.focus_index
printf "display page/focus dirty count/first/last = %u / %u / %u / %u / %u\n", g_ps_hw6_owner_probe.display_ui_page, g_ps_hw6_owner_probe.display_ui_current_focus_row, g_ps_hw6_owner_probe.display_dirty_row_count, g_ps_hw6_owner_probe.display_dirty_first_row, g_ps_hw6_owner_probe.display_dirty_last_row
printf "display UI request/render count = %u / %u\n", g_ps_hw6_owner_probe.display_ui_request_count, g_ps_hw6_owner_probe.display_ui_render_count
printf "waiting presentation/steps/elements/status = %u / %u / %u / 0x%x\n", g_ps_hw6_owner_probe.display_waiting_presentation_id, g_ps_hw6_owner_probe.display_waiting_sequence_frame_count, g_ps_hw6_owner_probe.display_waiting_element_count, g_ps_hw6_owner_probe.display_waiting_snapshot_status
printf "timeline preserve/rebase/frame/deadline/status = %u / %u / %u / %u / 0x%x\n", g_ps_hw6_rtos_probe.display_waiting_preserve_count, g_ps_hw6_rtos_probe.display_waiting_rebase_count, g_ps_hw6_rtos_probe.display_waiting_preserve_frame, g_ps_hw6_rtos_probe.display_waiting_preserve_deadline_tick, g_ps_hw6_rtos_probe.display_waiting_preserve_status
printf "LPBAM ready/active STOP2 entries = %u / %u / %u\n", g_ps_hw6_owner_probe.display_lpbam_ready, g_ps_hw6_owner_probe.display_lpbam_active, g_ps_hw6_rtos_probe.stop2_auto_entry_count
printf "expected active scene: api/type/active/status=6/1/1/0 render model status=0 model scene/state/visual/focus match runtime; descriptor scene/states/routes/variables/guards/actions/transitions=1/3/2/1/6/6/6; L/R applies atomically, A increments route miss only; timeline stays stable and STOP2 increments\n"
printf "--- end HW6 STATE_SCENE reactive loop ---\n"
