#!/usr/bin/env python3
"""
Build map and tileset blobs for all maps listed in Assets/game_project/maps.json.

Outputs:
- Assets/maps/build/<map_id>.tmap.bin
- Assets/maps/build/<tileset_name>.tset.bin
- Assets/game_project/build/map_registry.json
- Core/Inc/game_map_registry_autogen.h
"""

from __future__ import annotations

import argparse
import copy
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

from gen_tiled_map_blob import (
    FLAG_EMISSIVE,
    FLAG_OCCLUDER,
    FLAG_ROOF,
    FLAG_SLOW,
    FLAG_SOLID,
    FLAG_WATER,
    _load_tileset_flags_from_tsx,
    build_blob as build_map_blob,
)
from gen_tiled_tileset_blob import build_blob as build_tileset_blob
from validate_game_project import find_repo_root


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def as_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


GID_MASK = 0x1FFFFFFF


def as_int(value: Any, default: int = 0) -> int:
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(round(value))
    if isinstance(value, str):
        try:
            return int(value, 10)
        except ValueError:
            return default
    return default


def strip_gid(value: Any) -> int:
    return as_int(value, 0) & GID_MASK


def fnv1a32(text: str) -> int:
    h = 0x811C9DC5
    for byte in text.encode("utf-8"):
        h ^= byte
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


def write_map_registry_header(path: Path, entries: list[dict[str, Any]]) -> None:
    seen_ids: set[int] = set()
    seen_hashes: set[int] = set()
    lines: list[str] = []

    if len(entries) == 0:
        raise ValueError("map registry is empty; at least one map entry is required")

    lines.append("// Auto-generated by tools/build_game_maps.py. Do not edit manually.")
    lines.append("#ifndef GAME_MAP_REGISTRY_AUTOGEN_H")
    lines.append("#define GAME_MAP_REGISTRY_AUTOGEN_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("extern \"C\" {")
    lines.append("#endif")
    lines.append("")
    lines.append("typedef struct")
    lines.append("{")
    lines.append("  uint32_t target_map_hash;")
    lines.append("  uint32_t scene_map_id;")
    lines.append("  uint32_t scene_tileset_id;")
    lines.append("  uint32_t slot_index;")
    lines.append("} game_map_registry_entry_t;")
    lines.append("")
    lines.append(f"#define GAME_MAP_REGISTRY_ENTRY_COUNT ({len(entries)}u)")
    lines.append("")
    lines.append("static const game_map_registry_entry_t g_game_map_registry_entries[GAME_MAP_REGISTRY_ENTRY_COUNT] = {")

    for slot_index, entry in enumerate(entries):
        map_name = as_text(entry.get("id"))
        scene_map_id = as_int(entry.get("map_asset_id"), 0)
        scene_tileset_id = as_int(entry.get("tileset_asset_id"), 0)
        target_map_hash = fnv1a32(map_name)

        if map_name == "":
            raise ValueError(f"entry[{slot_index}] has empty map id")
        if scene_map_id <= 0:
            raise ValueError(f"entry[{slot_index}] has invalid map_asset_id {scene_map_id}")
        if scene_tileset_id <= 0:
            raise ValueError(f"entry[{slot_index}] has invalid tileset_asset_id {scene_tileset_id}")
        if scene_map_id in seen_ids:
            raise ValueError(f"duplicate map_asset_id {scene_map_id} in map registry")
        if target_map_hash in seen_hashes:
            raise ValueError(f"hash collision for map id '{map_name}' in map registry")

        seen_ids.add(scene_map_id)
        seen_hashes.add(target_map_hash)

        lines.append(
            "  { 0x%08Xu, %uu, %uu, %uu }, /* %s */"
            % (target_map_hash, scene_map_id, scene_tileset_id, slot_index, map_name)
        )

    lines.append("};")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif /* GAME_MAP_REGISTRY_AUTOGEN_H */")
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def command_suffix_from_map_id(map_id: str) -> str:
    suffix_chars: list[str] = []
    for ch in map_id:
        if ("a" <= ch <= "z") or ("A" <= ch <= "Z") or ("0" <= ch <= "9"):
            suffix_chars.append(ch.lower())
        else:
            suffix_chars.append("_")
    suffix = "".join(suffix_chars).strip("_")
    if suffix == "":
        raise ValueError(f"invalid map id '{map_id}' for debug command generation")
    return suffix


def resolve_scene_slot_geometry(knobs: dict[str, Any]) -> tuple[int, int, int, int, int]:
    installed_base = as_int(knobs.get("storage_installed_base_addr"), 0)
    installed_size = as_int(knobs.get("storage_installed_size_bytes"), 0)
    map_base = as_int(knobs.get("game_rt_scene_map_addr"), installed_base)
    map_alt = as_int(knobs.get("game_rt_scene_map_alt_addr"), 0)
    tileset_base = as_int(knobs.get("game_rt_scene_tileset_addr"), map_base + 0x1000)

    slot_stride = 0x00010000
    if map_alt > map_base:
        slot_stride = map_alt - map_base

    tileset_offset = 0x00001000
    if (tileset_base > map_base) and ((tileset_base - map_base) < slot_stride):
        tileset_offset = tileset_base - map_base

    if installed_base <= 0 or installed_size <= 0:
        raise ValueError("knobs.json has invalid installed storage bounds")
    if map_base <= 0:
        raise ValueError("knobs.json has invalid game_rt_scene_map_addr")

    return map_base, slot_stride, tileset_offset, installed_base, installed_size


def resolve_scene_slot_addrs(
    slot_index: int,
    map_base: int,
    slot_stride: int,
    tileset_offset: int,
    installed_base: int,
    installed_size: int,
) -> tuple[int, int]:
    installed_end = installed_base + installed_size
    map_addr = map_base + (slot_index * slot_stride)
    tileset_addr = map_addr + tileset_offset
    if (
        map_addr < installed_base
        or tileset_addr < installed_base
        or map_addr >= installed_end
        or tileset_addr >= installed_end
    ):
        raise ValueError(
            f"slot {slot_index} address out of installed range: "
            f"map=0x{map_addr:08X} tileset=0x{tileset_addr:08X} "
            f"installed=[0x{installed_base:08X},0x{installed_end:08X})"
        )
    return map_addr, tileset_addr


def write_debug_map_helpers(path: Path, entries: list[dict[str, Any]]) -> None:
    if len(entries) == 0:
        raise ValueError("map helper generation requires at least one map entry")

    knobs_path = find_repo_root(Path(__file__).resolve()) / "config" / "knobs.json"
    knobs_obj = load_json(knobs_path)
    if not isinstance(knobs_obj, dict):
        raise ValueError("config/knobs.json must contain a JSON object")

    map_base, slot_stride, tileset_offset, installed_base, installed_size = resolve_scene_slot_geometry(knobs_obj)

    lines: list[str] = []
    seen_suffixes: set[str] = set()

    lines.append("# Auto-generated by tools/build_game_maps.py. Do not edit manually.")
    lines.append("# Source of truth: Assets/game_project/maps.json + config/knobs.json")
    lines.append("")
    map_entries: list[tuple[int, str, str, int, int, str, str]] = []
    for slot_index, entry in enumerate(entries):
        map_id = as_text(entry.get("id"))
        suffix = command_suffix_from_map_id(map_id)
        if suffix in seen_suffixes:
            raise ValueError(f"duplicate debug command suffix '{suffix}' from map id '{map_id}'")
        seen_suffixes.add(suffix)

        map_addr, tileset_addr = resolve_scene_slot_addrs(
            slot_index=slot_index,
            map_base=map_base,
            slot_stride=slot_stride,
            tileset_offset=tileset_offset,
            installed_base=installed_base,
            installed_size=installed_size,
        )
        map_blob_rel = f"Assets/maps/build/{map_id}.tmap.bin"
        tileset_blob_rel = f"Assets/maps/build/{map_id}.tset.bin"
        map_entries.append((slot_index, map_id, suffix, map_addr, tileset_addr, map_blob_rel, tileset_blob_rel))

    lines.append("define ps_storage_scene_assets_install_all_maps")
    lines.append('  printf "== Install scene assets (all maps from maps.json) ==\\n"')
    for _, _, suffix, _, _, _, _ in map_entries:
        lines.append(f"  ps_storage_scene_assets_install_map_{suffix}")
    lines.append("end")
    lines.append("")

    lines.append("define ps_storage_scene_assets_list_maps")
    lines.append('  printf "== Scene asset install commands ==\\n"')
    for slot_index, map_id, suffix, map_addr, tileset_addr, _, _ in map_entries:
        lines.append(
            f'  printf "  {map_id}: slot={slot_index} map=0x{map_addr:08X} '
            f'tileset=0x{tileset_addr:08X} cmd=ps_storage_scene_assets_install_map_{suffix}\\n"'
        )
    lines.append("end")
    lines.append("")

    for slot_index, map_id, suffix, map_addr, tileset_addr, map_blob_rel, tileset_blob_rel in map_entries:
        lines.append(f"define ps_storage_scene_map_install_map_{suffix}")
        lines.append(f'  printf "== Install scene map ({map_id}.tmap.bin) [slot {slot_index}] ==\\n"')
        lines.append("  ps_mode_verify_static")
        lines.append("  ps_storage_probe_wait")
        lines.append(f"  restore {map_blob_rel} binary g_storage_scene_map_blob_buf")
        lines.append(f"  __ps_storage_scene_map_program_staged 0x{map_addr:08X}")
        lines.append("end")
        lines.append("")
        lines.append(f"define ps_storage_scene_tileset_install_map_{suffix}")
        lines.append(f'  printf "== Install scene tileset ({map_id}.tset.bin) [slot {slot_index}] ==\\n"')
        lines.append("  ps_mode_verify_static")
        lines.append("  ps_storage_probe_wait")
        lines.append(f"  restore {tileset_blob_rel} binary g_storage_scene_tileset_blob_buf")
        lines.append(f"  __ps_storage_scene_tileset_program_staged 0x{tileset_addr:08X}")
        lines.append("end")
        lines.append("")
        lines.append(f"define ps_storage_scene_assets_install_map_{suffix}")
        lines.append(f'  printf "== Install scene assets ({map_id}) [slot {slot_index}] ==\\n"')
        lines.append(f"  ps_storage_scene_map_install_map_{suffix}")
        lines.append(f"  ps_storage_scene_tileset_install_map_{suffix}")
        lines.append("end")
        lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def pick_build_tile_layer_indices(map_obj: dict[str, Any]) -> list[int]:
    layers = map_obj.get("layers")
    if not isinstance(layers, list):
        raise ValueError("map has no layers array")

    tile_layer_indices = [i for i, layer in enumerate(layers) if isinstance(layer, dict) and layer.get("type") == "tilelayer"]
    if len(tile_layer_indices) == 0:
        raise ValueError("map has no tilelayer")

    visible_indices = [
        i
        for i in tile_layer_indices
        if isinstance(layers[i], dict) and bool(layers[i].get("visible", True))
    ]
    return visible_indices if len(visible_indices) > 0 else [tile_layer_indices[0]]


def resolve_gid_owner(tilesets: list[dict[str, Any]], gid: int) -> tuple[int, int] | None:
    best_index = -1
    best_firstgid = -1
    for i, ts in enumerate(tilesets):
        firstgid = as_int(ts.get("firstgid"), 0)
        if firstgid <= 0:
            continue
        if firstgid <= gid and firstgid > best_firstgid:
            best_index = i
            best_firstgid = firstgid
    if best_index < 0:
        return None
    return best_index, best_firstgid


def flags_to_properties(flags: int) -> list[dict[str, Any]]:
    props: list[dict[str, Any]] = []
    if (flags & FLAG_SOLID) != 0:
        props.append({"name": "solid", "type": "bool", "value": True})
    if (flags & FLAG_WATER) != 0:
        props.append({"name": "water", "type": "bool", "value": True})
    if (flags & FLAG_SLOW) != 0:
        props.append({"name": "slow", "type": "bool", "value": True})
    if (flags & FLAG_OCCLUDER) != 0:
        props.append({"name": "occluder", "type": "bool", "value": True})
    if (flags & FLAG_ROOF) != 0:
        props.append({"name": "roof", "type": "bool", "value": True})
    if (flags & FLAG_EMISSIVE) != 0:
        props.append({"name": "emissive", "type": "bool", "value": True})
    return props


def compact_map_for_used_tiles(map_path: Path, map_obj: dict[str, Any]) -> tuple[dict[str, Any], Path, list[int]]:
    layer_indices = pick_build_tile_layer_indices(map_obj)

    layers = map_obj.get("layers")
    if not isinstance(layers, list):
        raise ValueError("map has no layers array")

    used_gids: set[int] = set()
    for idx in layer_indices:
        layer = layers[idx]
        if not isinstance(layer, dict):
            continue
        data = layer.get("data")
        if not isinstance(data, list):
            raise ValueError(f"tile layer '{layer.get('name', '')}' data must be array")
        for raw in data:
            gid = strip_gid(raw)
            if gid > 0:
                used_gids.add(gid)

    if len(used_gids) == 0:
        raise ValueError(f"{map_path.as_posix()}: map has no non-zero tiles in selected layers")

    raw_tilesets = map_obj.get("tilesets")
    if not isinstance(raw_tilesets, list) or len(raw_tilesets) == 0:
        raise ValueError(f"{map_path.as_posix()}: map has no tilesets")
    tilesets = [ts for ts in raw_tilesets if isinstance(ts, dict)]
    if len(tilesets) == 0:
        raise ValueError(f"{map_path.as_posix()}: map tilesets are invalid")

    owner_indices: set[int] = set()
    owner_firstgid = -1
    for gid in used_gids:
        owner = resolve_gid_owner(tilesets, gid)
        if owner is None:
            raise ValueError(f"{map_path.as_posix()}: gid {gid} has no matching tileset firstgid")
        owner_index, firstgid = owner
        owner_indices.add(owner_index)
        owner_firstgid = firstgid

    if len(owner_indices) != 1:
        raise ValueError(
            f"{map_path.as_posix()}: used tiles span multiple tilesets; compact pack currently supports one tileset per map"
        )

    owner_index = next(iter(owner_indices))
    owner_tileset = tilesets[owner_index]
    source = as_text(owner_tileset.get("source"))
    if source == "":
        raise ValueError(f"{map_path.as_posix()}: compact packing requires external TSX source")
    tsx_path = resolve_map_source_path(map_path, source)

    used_local_ids = sorted({gid - owner_firstgid for gid in used_gids})
    local_to_new_gid = {old_local: (i + 1) for i, old_local in enumerate(used_local_ids)}
    global_to_new_gid = {owner_firstgid + old_local: new_gid for old_local, new_gid in local_to_new_gid.items()}

    compact_obj = copy.deepcopy(map_obj)
    compact_layers = compact_obj.get("layers")
    if not isinstance(compact_layers, list):
        raise ValueError("map has no layers array")

    for idx in layer_indices:
        layer = compact_layers[idx]
        if not isinstance(layer, dict):
            continue
        data = layer.get("data")
        if not isinstance(data, list):
            raise ValueError(f"tile layer '{layer.get('name', '')}' data must be array")
        remapped: list[int] = []
        for raw in data:
            gid = strip_gid(raw)
            if gid == 0:
                remapped.append(0)
                continue
            new_gid = global_to_new_gid.get(gid)
            if new_gid is None:
                remapped.append(0)
            else:
                remapped.append(new_gid)
        layer["data"] = remapped

    tsx_flags = _load_tileset_flags_from_tsx(tsx_path)
    compact_tiles: list[dict[str, Any]] = []
    for old_local in used_local_ids:
        flags = tsx_flags.get(old_local, 0)
        if flags == 0:
            continue
        props = flags_to_properties(flags)
        if len(props) == 0:
            continue
        compact_tiles.append(
            {
                "id": local_to_new_gid[old_local] - 1,
                "properties": props,
            }
        )

    compact_obj["tilesets"] = [{"firstgid": 1, "tiles": compact_tiles}]
    return compact_obj, tsx_path, used_local_ids


def repo_display_path(repo_root: Path, path: Path) -> str:
    try:
        return str(path.resolve().relative_to(repo_root.resolve())).replace("\\", "/")
    except Exception:
        return str(path.resolve()).replace("\\", "/")


def resolve_map_source_path(map_path: Path, source: str) -> Path:
    raw = Path(source)
    candidates: list[Path] = []

    if raw.is_absolute():
        candidates.append(raw.resolve())
        candidates.append((map_path.parent / raw.name).resolve())
    else:
        candidates.append((map_path.parent / raw).resolve())
        candidates.append((map_path.parent / raw.name).resolve())

    for candidate in candidates:
        if candidate.is_file():
            return candidate

    candidate_text = ", ".join(str(x) for x in candidates)
    raise ValueError(
        f"{map_path.as_posix()}: tileset source '{source}' not found. "
        f"Tried: {candidate_text}"
    )


def int_attr(node: ET.Element, key: str, default: int = 0) -> int:
    value = node.get(key)
    if value is None:
        return default
    try:
        return int(value, 10)
    except ValueError:
        return default


def resolve_tileset_inputs(tsx_path: Path) -> tuple[Path, int, int, int, int]:
    root = ET.parse(tsx_path).getroot()
    tile_w = int_attr(root, "tilewidth", 0)
    tile_h = int_attr(root, "tileheight", 0)
    columns = int_attr(root, "columns", 0)
    tile_count = int_attr(root, "tilecount", 0)

    img = root.find("image")
    if img is None:
        raise ValueError(f"{tsx_path.as_posix()}: missing <image> node")
    src = as_text(img.get("source"))
    if src == "":
        raise ValueError(f"{tsx_path.as_posix()}: image source is missing")

    png_candidates: list[Path] = []
    src_raw = Path(src)
    if src_raw.is_absolute():
        png_candidates.append(src_raw.resolve())
        png_candidates.append((tsx_path.parent / src_raw.name).resolve())
    else:
        png_candidates.append((tsx_path.parent / src_raw).resolve())
        png_candidates.append((tsx_path.parent / src_raw.name).resolve())
    png_candidates.append(tsx_path.with_suffix(".png").resolve())

    png_path: Path | None = None
    for candidate in png_candidates:
        if candidate.is_file():
            png_path = candidate
            break
    if png_path is None:
        candidate_text = ", ".join(str(x) for x in png_candidates)
        raise ValueError(
            f"{tsx_path.as_posix()}: image source '{src}' not found. "
            f"Tried: {candidate_text}"
        )

    if tile_w <= 0 or tile_h <= 0:
        raise ValueError(f"{tsx_path.as_posix()}: invalid tile size {tile_w}x{tile_h}")

    width = int_attr(img, "width", 0)
    height = int_attr(img, "height", 0)
    if width <= 0 or height <= 0:
        from PIL import Image  # type: ignore

        with Image.open(png_path) as pic:
            width, height = pic.size

    if columns <= 0:
        if width <= 0 or (width % tile_w) != 0:
            raise ValueError(f"{tsx_path.as_posix()}: cannot derive columns from image width")
        columns = width // tile_w

    if tile_count <= 0:
        if (width <= 0) or (height <= 0) or (width % tile_w) != 0 or (height % tile_h) != 0:
            raise ValueError(f"{tsx_path.as_posix()}: cannot derive tilecount from image size")
        tile_count = (width // tile_w) * (height // tile_h)

    rows = (tile_count + columns - 1) // columns
    return png_path, tile_w, tile_h, columns, rows


def build_all(
    repo_root: Path,
    maps_file: Path,
    out_dir: Path,
    registry_out: Path,
    header_out: Path,
    debug_gdb_out: Path,
) -> None:
    maps_raw = load_json(maps_file)
    if not isinstance(maps_raw, list):
        raise ValueError(f"{maps_file.as_posix()} must contain a JSON array.")

    out_dir.mkdir(parents=True, exist_ok=True)
    registry_out.parent.mkdir(parents=True, exist_ok=True)

    registry_entries: list[dict[str, Any]] = []

    for index, rec in enumerate(maps_raw):
        if not isinstance(rec, dict):
            raise ValueError(f"maps[{index}] is not an object.")

        map_id = as_text(rec.get("id"))
        tiled_map_rel = as_text(rec.get("tiled_map"))
        if map_id == "":
            raise ValueError(f"maps[{index}] missing required field 'id'.")
        if tiled_map_rel == "":
            raise ValueError(f"maps[{index}] missing required field 'tiled_map'.")

        map_path = (repo_root / tiled_map_rel).resolve()
        if not map_path.is_file():
            raise ValueError(f"maps[{index}] map file not found: {tiled_map_rel}")

        map_obj = load_json(map_path)
        if not isinstance(map_obj, dict):
            raise ValueError(f"maps[{index}] map root must be object: {tiled_map_rel}")

        compact_map_obj, tsx_path, used_local_ids = compact_map_for_used_tiles(map_path, map_obj)
        temp_map_path = out_dir / f".{map_id}.compact.map.json"
        try:
            temp_map_path.write_text(
                json.dumps(compact_map_obj, ensure_ascii=False),
                encoding="utf-8",
            )
            map_blob = build_map_blob(temp_map_path, None, "objects")
        finally:
            if temp_map_path.exists():
                temp_map_path.unlink()
        map_out = out_dir / f"{map_id}.tmap.bin"
        map_out.write_bytes(map_blob)

        png_path, tile_w, tile_h, columns, rows = resolve_tileset_inputs(tsx_path)
        tileset_blob = build_tileset_blob(
            png_path=png_path,
            tile_w=tile_w,
            tile_h=tile_h,
            columns=columns,
            rows=rows,
            base_gid=1,
            tile_indices=used_local_ids,
        )
        tileset_name = f"{map_id}.tset.bin"
        tileset_out = out_dir / tileset_name
        tileset_out.write_bytes(tileset_blob)

        entry = {
            "id": map_id,
            "display_name": as_text(rec.get("display_name")),
            "map_asset_id": rec.get("map_asset_id", 0),
            "tileset_asset_id": rec.get("tileset_asset_id", 0),
            "music_asset_id": rec.get("music_asset_id", 0),
            "tiled_map": tiled_map_rel,
            "tileset_tsx": repo_display_path(repo_root, tsx_path),
            "map_blob": f"Assets/maps/build/{map_id}.tmap.bin",
            "tileset_blob": f"Assets/maps/build/{tileset_name}",
            "tiles_used_count": len(used_local_ids),
            "slot_index": index,
        }
        registry_entries.append(entry)

        print(f"map: {map_id} -> {entry['map_blob']}")
        print(f"tileset: {map_id} -> {entry['tileset_blob']}")

    registry = {
        "schema_version": 1,
        "source_maps_file": repo_display_path(repo_root, maps_file),
        "entries": registry_entries,
    }
    registry_out.write_text(json.dumps(registry, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    print(f"wrote registry: {registry_out}")
    write_map_registry_header(header_out, registry_entries)
    print(f"wrote header: {header_out}")
    write_debug_map_helpers(debug_gdb_out, registry_entries)
    print(f"wrote debug helpers: {debug_gdb_out}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Build all game map/tileset blobs from maps.json.")
    parser.add_argument(
        "--repo-root",
        default="",
        help="Optional explicit repo root (default: auto-detect).",
    )
    parser.add_argument(
        "--maps-file",
        default="Assets/game_project/maps.json",
        help="Path to maps domain JSON, relative to repo root.",
    )
    parser.add_argument(
        "--out-dir",
        default="Assets/maps/build",
        help="Output directory for map/tileset blobs, relative to repo root.",
    )
    parser.add_argument(
        "--registry-out",
        default="Assets/game_project/build/map_registry.json",
        help="Output registry JSON path, relative to repo root.",
    )
    parser.add_argument(
        "--header-out",
        default="Core/Inc/game_map_registry_autogen.h",
        help="Output C header for runtime map registry, relative to repo root.",
    )
    parser.add_argument(
        "--debug-gdb-out",
        default="Assets/game_project/build/map_debug_helpers_autogen.gdb",
        help="Output GDB helper commands for map install, relative to repo root.",
    )
    args = parser.parse_args(argv)

    try:
        repo_root = Path(args.repo_root).resolve() if args.repo_root else find_repo_root(Path(__file__).resolve())
        maps_file = (repo_root / args.maps_file).resolve()
        out_dir = (repo_root / args.out_dir).resolve()
        registry_out = (repo_root / args.registry_out).resolve()
        header_out = (repo_root / args.header_out).resolve()
        debug_gdb_out = (repo_root / args.debug_gdb_out).resolve()
        build_all(repo_root, maps_file, out_dir, registry_out, header_out, debug_gdb_out)
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
