#!/usr/bin/env python3
"""Generate autogen frame data for the title animation test mode.

Input:
  Assets/test/title_anim_sheet.png

Output:
  Core/Inc/ui/ui_test_title_anim_autogen.h
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INPUT_PNG = ROOT / "Assets" / "test" / "title_anim_sheet.png"
OUT_HEADER = ROOT / "Core" / "Inc" / "ui" / "ui_test_title_anim_autogen.h"

FRAME_W = 111
FRAME_H = 96
WHITE_LUMA_THRESH = 128


def _pack_frame_1bpp_rgba(img_rgba, x0: int, y0: int, w: int, h: int) -> bytes:
    stride = (w + 7) // 8
    out = bytearray(stride * h)
    for y in range(h):
        for x in range(w):
            r, g, b, a = img_rgba.getpixel((x0 + x, y0 + y))
            if a < 16:
                continue
            lum = (299 * r + 587 * g + 114 * b) // 1000
            if lum < WHITE_LUMA_THRESH:
                continue
            idx = y * stride + (x >> 3)
            out[idx] |= 1 << (7 - (x & 7))
    return bytes(out)


def _emit_u8_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[] = {{"]
    row: list[str] = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02X}")
        if len(row) == 16 or i == (len(data) - 1):
            lines.append("  " + ", ".join(row) + ",")
            row = []
    lines.append("};")
    return "\n".join(lines)


def generate() -> str:
    try:
        from PIL import Image  # type: ignore
    except Exception as exc:
        raise RuntimeError("Pillow is required: pip install pillow") from exc

    if not INPUT_PNG.is_file():
        raise FileNotFoundError(f"missing input sheet: {INPUT_PNG}")

    img = Image.open(INPUT_PNG).convert("RGBA")
    sheet_w, sheet_h = img.size
    if sheet_h != FRAME_H:
        raise ValueError(f"sheet height must be {FRAME_H}, got {sheet_h}")
    if sheet_w % FRAME_W != 0:
        raise ValueError(f"sheet width {sheet_w} must be a multiple of frame width {FRAME_W}")

    frame_count = sheet_w // FRAME_W
    stride = (FRAME_W + 7) // 8
    frame_bytes = stride * FRAME_H

    frame_arrays: list[str] = []
    frame_ptrs: list[str] = []
    for frame_idx in range(frame_count):
        x0 = frame_idx * FRAME_W
        data = _pack_frame_1bpp_rgba(img, x0, 0, FRAME_W, FRAME_H)
        sym = f"ui_test_title_anim_frame_{frame_idx:02d}"
        frame_arrays.append(_emit_u8_array(sym, data))
        frame_ptrs.append(f"  {sym},")

    header = f"""// Auto-generated by tools/gen_title_anim_test.py. Do not edit manually.
#pragma once

#include <stdint.h>

enum {{
  UI_TEST_TITLE_ANIM_FRAME_W = {FRAME_W}u,
  UI_TEST_TITLE_ANIM_FRAME_H = {FRAME_H}u,
  UI_TEST_TITLE_ANIM_FRAME_STRIDE = {stride}u,
  UI_TEST_TITLE_ANIM_FRAME_COUNT = {frame_count}u,
  UI_TEST_TITLE_ANIM_FRAME_BYTES = {frame_bytes}u
}};

{chr(10).join(frame_arrays)}

static const uint8_t *const ui_test_title_anim_frames[UI_TEST_TITLE_ANIM_FRAME_COUNT] = {{
{chr(10).join(frame_ptrs)}
}};
"""
    return header


def main() -> int:
    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_HEADER.write_text(generate(), encoding="utf-8")
    print(f"generated {OUT_HEADER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
