"""Explicit V2 awake hardware fixture, separate from ordinary build/export."""
import argparse
from copy import deepcopy
from dataclasses import replace
from pathlib import Path

from peepshow_authoring.compiler import build_development_egg_v2
from peepshow_authoring.project import load_project

DEFAULT_PROJECT = Path(__file__).resolve().parents[2] / "examples/authoring/native_v2_continuity.peepproj"


def fixture_bundle():
    bundle = load_project(Path(__file__).parent / "peepshow_authoring/test_project.peepproj")
    template = bundle.frames[0]
    frames = []
    for phase in range(4):
        pixels = bytearray(128)
        x0, y0 = ((2, 2), (18, 2), (18, 18), (2, 18))[phase]
        for y in range(y0, y0 + 12):
            for x in range(x0, x0 + 12):
                pixels[y * 4 + x // 8] |= 1 << (7 - x % 8)
        frames.append(replace(template, asset_id="orbit", frame_id=f"orbit.{phase}",
            width=32, height=32, row_stride_bytes=4, pixels=bytes(pixels),
            mask=bytes([255] * 128), opaque=True))
    assets = [{"asset_id": "orbit", "asset_type": "masked_1bpp",
        "frames": [{"frame_id": frame.frame_id,
                    "source_rect": {"x": 0, "y": 0, "width": 32, "height": 32}}
                   for frame in frames]}]
    scene = {
        "schema_id": "peepshow.authoring.state_scene", "schema_version": 2,
        "scene_id": "object_awake", "display_name": "Object Awake", "scene_type": "STATE_SCENE",
        "entry_state": "base", "variables": [], "scene_exits": [],
        "input_actions": [{"action_id": "toggle", "logical_source": "BUTTON_A"},
                          {"action_id": "exit", "logical_source": "BUTTON_B"}],
        "objects": [
            {"object_id": "orbit", "kind": "sprite", "layer": "SCENE", "z_order": 0,
             "width": 32, "height": 32, "defaults": {"x": 68, "y": 28, "visible": True,
             "visual_ref": "orbit.0"}, "animation_ref": "orbit.loop"},
            {"object_id": "marker", "kind": "filled_rect", "layer": "UI", "z_order": 1,
             "width": 16, "height": 16, "defaults": {"x": 24, "y": 100, "visible": True}}],
        "states": [{"state_id": "base", "display_name": "Base", "object_overrides": []},
                   {"state_id": "shifted", "display_name": "Shifted",
                    "object_overrides": [{"object_ref": "marker", "x": 128}]}],
        "routes": [
            {"route_id": "to_shifted", "action_ref": "toggle", "from_states": ["base"],
             "guards": [], "actions": [], "target_state": "shifted"},
            {"route_id": "to_base", "action_ref": "toggle", "from_states": ["shifted"],
             "guards": [], "actions": [], "target_state": "base"},
            {"route_id": "exit", "action_ref": "exit", "from_states": ["base", "shifted"],
             "guards": [], "actions": [{"kind": "exit_to_shell"}], "target_state": "base"}],
        "interaction_policy": {"policy_id": "awake", "mode": "continuous",
            "meaningful_activity_actions": ["toggle", "exit"],
            "bounded_deferrals": []},
        "reactive_wait_default": {"policy_id": "awake", "hold_fallback_allowed": True,
                                  "event_interests": ["toggle", "exit"]}}
    project = deepcopy(bundle.project)
    project.update(entry_scene="object_awake", scene_sources=["scenes/object_awake.state.json"])
    project["package"]["package_id"] = "dev.peepshow.object_awake"
    return replace(bundle, project=project, scenes=(scene,), frames=tuple(frames), assets=assets,
        animations=({"animation_id": "orbit.loop", "loop_policy": "loop",
                     "frame_refs": [frame.frame_id for frame in frames],
                     "frame_duration_ms": [250] * 4},), audio_assets=(), audio_cues=(), issues=())


def render_c(blob):
    rows = ["  " + ", ".join(f"0x{byte:02x}" for byte in blob[i:i + 16]) + ","
            for i in range(0, len(blob), 16)]
    return ('/* Generated by tools/authoring/build_object_development.py. */\n'
            '#include "ps_hw6_object_development.h"\n\n'
            'const uint8_t g_ps_object_development_egg[] = {\n' + "\n".join(rows) +
            '\n};\nconst uint32_t g_ps_object_development_egg_size = '
            'sizeof(g_ps_object_development_egg);\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, default=DEFAULT_PROJECT,
                        help="Native V2 project; defaults to the checked-in Studio continuity fixture")
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[2] /
                        "firmware/peepshow_hw6_fw0/Core/Src/ps_object_development_egg_autogen.c")
    args = parser.parse_args()
    blob = build_development_egg_v2(load_project(args.project))
    args.output.write_text(render_c(blob), encoding="ascii", newline="\n")
    print(f"Development-only V2 egg: {len(blob)} bytes -> {args.output}")


if __name__ == "__main__":
    main()
