"""Explicit V2 awake hardware fixture, separate from ordinary build/export."""
import argparse
from copy import deepcopy
from dataclasses import replace
from pathlib import Path

from peepshow_authoring.compiler import build_development_egg_v2
from peepshow_authoring.project import load_project
from peepshow_authoring.audio_assets import CompiledAudioAsset, encode_ima_adpcm

DEFAULT_PROJECT = Path(__file__).resolve().parents[2] / "examples/authoring/native_v2_continuity.peepproj"


def fixture_bundle():
    bundle = load_project(Path(__file__).parent / "peepshow_authoring/test_project.peepproj")
    template = bundle.frames[0]
    frames = []
    for phase in range(4):
        pixels = bytearray(128)
        x0, y0 = ((2, 2), (18, 2), (18, 18), (2, 18))[phase]
        for y in range(y0, y0 + 12):
            for x in range(x0, x0 + 12):
                pixels[y * 4 + x // 8] |= 1 << (7 - x % 8)
        frames.append(replace(template, asset_id="orbit", frame_id=f"orbit.{phase}",
            width=32, height=32, row_stride_bytes=4, pixels=bytes(pixels),
            mask=bytes([255] * 128), opaque=True))
    assets = [{"asset_id": "orbit", "asset_type": "masked_1bpp",
        "frames": [{"frame_id": frame.frame_id,
                    "source_rect": {"x": 0, "y": 0, "width": 32, "height": 32}}
                   for frame in frames]}]
    scene = {
        "schema_id": "peepshow.authoring.state_scene", "schema_version": 2,
        "scene_id": "object_awake", "display_name": "Object Awake", "scene_type": "STATE_SCENE",
        "entry_state": "base", "variables": [], "scene_exits": [],
        "input_actions": [{"action_id": "toggle", "logical_source": "BUTTON_A"},
                          {"action_id": "exit", "logical_source": "BUTTON_B"}],
        "objects": [
            {"object_id": "orbit", "kind": "sprite", "layer": "SCENE", "z_order": 0,
             "width": 32, "height": 32, "defaults": {"x": 68, "y": 28, "visible": True,
             "visual_ref": "orbit.0"}, "animation_ref": "orbit.loop"},
            {"object_id": "marker", "kind": "filled_rect", "layer": "UI", "z_order": 1,
             "width": 16, "height": 16, "defaults": {"x": 24, "y": 100, "visible": True}}],
        "states": [{"state_id": "base", "display_name": "Base", "object_overrides": []},
                   {"state_id": "shifted", "display_name": "Shifted",
                    "object_overrides": [{"object_ref": "marker", "x": 128}]}],
        "routes": [
            {"route_id": "to_shifted", "action_ref": "toggle", "from_states": ["base"],
             "guards": [], "actions": [], "target_state": "shifted"},
            {"route_id": "to_base", "action_ref": "toggle", "from_states": ["shifted"],
             "guards": [], "actions": [], "target_state": "base"},
            {"route_id": "exit", "action_ref": "exit", "from_states": ["base", "shifted"],
             "guards": [], "actions": [{"kind": "exit_to_shell"}], "target_state": "base"}],
        "interaction_policy": {"policy_id": "awake", "mode": "continuous",
            "meaningful_activity_actions": ["toggle", "exit"],
            "bounded_deferrals": []},
        "reactive_wait_default": {"policy_id": "awake", "hold_fallback_allowed": True,
                                  "event_interests": ["toggle", "exit"]}}
    project = deepcopy(bundle.project)
    project.update(entry_scene="object_awake", scene_sources=["scenes/object_awake.state.json"])
    project["package"]["package_id"] = "dev.peepshow.object_awake"
    return replace(bundle, project=project, scenes=(scene,), frames=tuple(frames), assets=assets,
        animations=({"animation_id": "orbit.loop", "loop_policy": "loop",
                     "frame_refs": [frame.frame_id for frame in frames],
                     "frame_duration_ms": [250] * 4},), audio_assets=(), audio_cues=(), issues=())


def render_c(blob):
    rows = ["  " + ", ".join(f"0x{byte:02x}" for byte in blob[i:i + 16]) + ","
            for i in range(0, len(blob), 16)]
    return ('/* Generated by tools/authoring/build_object_development.py. */\n'
            '#include "ps_hw6_object_development.h"\n\n'
            'const uint8_t g_ps_object_development_egg[] = {\n' + "\n".join(rows) +
            '\n};\nconst uint32_t g_ps_object_development_egg_size = '
            'sizeof(g_ps_object_development_egg);\n')


def timer_fixture_bundle():
    """OS-only timer proof derived from, without editing, GUI's pinned source."""
    bundle = load_project(DEFAULT_PROJECT)
    scene = deepcopy(bundle.scenes[0])
    scene["objects"].append({"object_id": "timer_marker", "kind": "filled_rect",
        "width": 12, "height": 12, "z_order": 2, "layer": "SCENE",
        "defaults": {"x": 16, "y": 16, "visible": True}})
    scene["event_bindings"] = [
        {"binding_id": "scene_delay", "event_type": "time.scene_elapsed",
         "configuration": {"delay_ms": 5000, "start_policy": "scene_entry"}},
        {"binding_id": "state_delay", "event_type": "time.state_entry_elapsed",
         "configuration": {"delay_ms": 3000}}]
    scene["event_handlers"] = [{"handler_id": "scene_delay_handler", "event_ref": "scene_delay",
        "guards": [], "actions": [{"kind": "object.set_position",
                                    "object_ref": "timer_marker", "x": 140}]}]
    scene["routes"].append({"route_id": "state_delay_route", "event_ref": "state_delay",
        "from_states": ["marker_right"], "guards": [], "actions": [], "target_state": "start"})
    for name, button, actions in (
        ("restart", "BUTTON_L", [{"kind": "restart_timer", "timer_ref": "scene_delay"},
                                  {"kind": "object.set_position", "object_ref": "timer_marker", "x": 16}]),
        ("cancel", "BUTTON_R", [{"kind": "cancel_timer", "timer_ref": "scene_delay"}]),
    ):
        scene["input_actions"].append({"action_id": name, "logical_source": button, "event_kind": "press"})
        for state in ("start", "marker_right"):
            scene["routes"].append({"route_id": f"{name}_{state}", "action_ref": name,
                "from_states": [state], "guards": [], "actions": deepcopy(actions), "target_state": state})
    scene["reactive_wait_default"]["event_interests"].extend(["scene_delay", "state_delay", "restart", "cancel"])
    project = deepcopy(bundle.project)
    project["package"]["package_id"] = "dev.peepshow.native_v2_timers"
    return replace(bundle, project=project, scenes=(scene,))


def sfx_fixture_bundle():
    """OS audio integration variant; both pinned GUI projects remain unchanged."""
    bundle = load_project(DEFAULT_PROJECT.parent / "native_v2_scene_timer.peepproj")
    orbit = fixture_bundle()
    scene = deepcopy(bundle.scenes[0])
    scene["objects"][0].update(width=32, height=32, animation_ref="orbit.loop")
    scene["objects"][0]["defaults"]["visual_ref"] = "orbit.0"
    for route in scene["routes"]:
        route["actions"].append({"kind": "play_sfx", "cue_ref": "short.cue"})
    scene["event_handlers"][0]["actions"].append({"kind": "play_sfx", "cue_ref": "long.cue"})
    for name, button, actions in (
        ("sound", "BUTTON_L", [{"kind": "play_sfx", "cue_ref": "short.cue"},
                                 {"kind": "play_sfx", "cue_ref": "long.cue"}]),
        ("shell", "BUTTON_R", [{"kind": "exit_to_shell"}]),
    ):
        scene["input_actions"].append({"action_id": name, "logical_source": button, "event_kind": "press"})
        for state in ("start", "marker_right"):
            scene["routes"].append({"route_id": f"{name}_{state}", "action_ref": name,
                "from_states": [state], "guards": [], "actions": deepcopy(actions), "target_state": state})
        scene["reactive_wait_default"]["event_interests"].append(name)
    audio = []
    for name, duration in (("short", 80), ("long", 6000)):
        count = duration * 16
        # Low-level integer triangle, with source ramps in addition to the mixer envelope.
        samples = [((i % 32 if i % 32 < 16 else 32 - i % 32) - 8) * 600 *
                   min(i, count - 1 - i, 160) // 160 for i in range(count)]
        adpcm, blocks = encode_ima_adpcm(samples)
        audio.append(CompiledAudioAsset(name, "generated", 16000, 1, 16000, 1,
            count, duration, count * 2, 256, blocks, adpcm))
    cues = tuple({"cue_id": f"{name}.cue", "asset_ref": name, "priority": 1, "volume": 96}
                 for name in ("short", "long"))
    project = deepcopy(bundle.project)
    project["package"]["package_id"] = "dev.peepshow.native_v2_sfx"
    return replace(bundle, project=project, scenes=(scene,), frames=orbit.frames,
                   assets=orbit.assets, animations=orbit.animations,
                   audio_assets=tuple(audio), audio_cues=cues)


def structured_fixture_bundle():
    """Labelled OS sleep/wake test; the original GUI fixture stays unchanged."""
    bundle = load_project(DEFAULT_PROJECT.parent / "native_v2_timer_four_frames.peepproj")
    scene = deepcopy(bundle.scenes[0])
    scene["display_name"] = "Structured Sleep Wake"
    scene["objects"][0]["defaults"].update(x=72, y=12)
    scene["objects"][1]["defaults"].update(x=32, y=68)
    scene["objects"][2]["defaults"].update(x=76, y=116)
    for name, x, y in (("left_slot", 28, 64), ("right_slot", 116, 64), ("timer_slot", 72, 112)):
        scene["objects"].append({"object_id": name, "kind": "outline_rect",
            "width": 24, "height": 24, "z_order": 3, "layer": "SCENE",
            "defaults": {"x": x, "y": y, "visible": True}})
    frames = list(bundle.frames)
    assets = deepcopy(list(bundle.assets))
    for name, x, rows in (
        ("label_b", 35, (30, 17, 17, 30, 17, 17, 30)),
        ("label_a", 123, (14, 17, 17, 31, 17, 17, 17)),
    ):
        pixels = bytearray(28)
        for y, row in enumerate(rows):
            for bit in range(5):
                if row & (1 << (4 - bit)):
                    for dy in range(2):
                        for dx in range(2):
                            px = bit * 2 + dx
                            pixels[(y * 2 + dy) * 2 + px // 8] |= 1 << (7 - px % 8)
        frame_id = name + ".0"
        frames.append(replace(bundle.frames[0], asset_id=name, frame_id=frame_id,
            width=10, height=14, row_stride_bytes=2, pixels=bytes(pixels),
            mask=bytes([255] * 28), opaque=True))
        assets.append({"asset_id": name, "asset_type": "masked_1bpp",
            "frames": [{"frame_id": frame_id,
                "source_rect": {"x": 0, "y": 0, "width": 10, "height": 14}}]})
        scene["objects"].append({"object_id": name, "kind": "sprite",
            "width": 10, "height": 14, "z_order": 4, "layer": "SCENE",
            "defaults": {"x": x, "y": 44, "visible": True, "visual_ref": frame_id}})
    project = deepcopy(bundle.project)
    project["package"]["package_id"] = "dev.peepshow.structured_sleep_wake"
    return replace(bundle, project=project, scenes=(scene,), frames=tuple(frames), assets=assets)


def dual_fixture_bundle():
    """Two independent clips with a deliberately compatible common interval."""
    bundle = structured_fixture_bundle()
    scene = deepcopy(bundle.scenes[0])
    scene["display_name"] = "Dual Animation Sleep Wake"
    frames = list(bundle.frames)
    refs = []
    for phase in range(4):
        pixels = bytearray(36)
        for y in range(12):
            for x in range(24):
                cell, column = divmod(x, 6)
                if column < 5 and (column in (0, 4) or y in (0, 11) or cell == phase):
                    pixels[y * 3 + x // 8] |= 1 << (7 - x % 8)
        ref = f"slow_indicator.{phase}"
        refs.append(ref)
        frames.append(replace(bundle.frames[0], asset_id="slow_indicator", frame_id=ref,
            width=24, height=12, row_stride_bytes=3, pixels=bytes(pixels),
            mask=bytes([255] * 36), opaque=True))
    assets = deepcopy(list(bundle.assets))
    assets.append({"asset_id": "slow_indicator", "asset_type": "masked_1bpp",
        "frames": [{"frame_id": ref,
            "source_rect": {"x": 0, "y": 0, "width": 24, "height": 12}} for ref in refs]})
    animations = deepcopy(list(bundle.animations))
    animations.append({"animation_id": "slow_indicator_loop", "loop_policy": "loop",
        "frame_refs": refs, "frame_duration_ms": [800] * 4})
    scene["objects"].append({"object_id": "slow_indicator", "kind": "sprite",
        "width": 24, "height": 12, "z_order": 5, "layer": "SCENE",
        "defaults": {"x": 72, "y": 44, "visible": True, "visual_ref": refs[0]},
        "animation_ref": "slow_indicator_loop"})
    project = deepcopy(bundle.project)
    project["package"]["package_id"] = "dev.peepshow.dual_sleep_wake"
    return replace(bundle, project=project, scenes=(scene,), frames=tuple(frames),
        assets=assets, animations=animations)


def scene_exit_fixture_bundle():
    """Labelled HOME/AWAY fresh-entry proof; no installed/export capability change."""
    bundle = structured_fixture_bundle()
    frames = list(bundle.frames)
    assets = deepcopy(list(bundle.assets))
    glyphs = {
        "A": (14, 17, 17, 31, 17, 17, 17),
        "E": (31, 16, 16, 30, 16, 16, 31),
        "H": (17, 17, 17, 31, 17, 17, 17),
        "L": (16, 16, 16, 16, 16, 16, 31),
        "M": (17, 27, 21, 21, 17, 17, 17),
        "O": (14, 17, 17, 17, 17, 17, 14),
        "R": (30, 17, 17, 30, 20, 18, 17),
        "W": (17, 17, 17, 21, 21, 27, 17),
        "Y": (17, 17, 10, 4, 4, 4, 4),
    }
    for text in ("HOME", "AWAY", "L", "R"):
        width = (len(text) * 6 - 1) * 2
        stride = (width + 7) // 8
        pixels = bytearray(stride * 14)
        for letter, character in enumerate(text):
            for row, bits in enumerate(glyphs[character]):
                for column in range(5):
                    if bits & (1 << (4 - column)):
                        for dy in range(2):
                            for dx in range(2):
                                x = letter * 12 + column * 2 + dx
                                pixels[(row * 2 + dy) * stride + x // 8] |= 128 >> (x % 8)
        name = "exit_label_" + text.lower()
        frames.append(replace(bundle.frames[0], asset_id=name, frame_id=name + ".0",
            width=width, height=14, row_stride_bytes=stride, pixels=bytes(pixels),
            mask=bytes([255] * len(pixels)), opaque=True))
        assets.append({"asset_id": name, "asset_type": "masked_1bpp", "frames": [
            {"frame_id": name + ".0", "source_rect": {"x": 0, "y": 0, "width": width, "height": 14}}]})
    scenes = []
    for scene_id, label, delay in (("home", "HOME", 2000), ("visit", "AWAY", 6000)):
        scene = deepcopy(bundle.scenes[0])
        scene.update(scene_id=scene_id, display_name=label, entry_state="start", scene_exits=[])
        scene["variables"] = [{"variable_id": "moves", "value_type": "int32",
            "initial": 0, "minimum": 0, "maximum": 1000000}]
        scene["objects"][0]["defaults"].update(x=72, y=28)
        scene["objects"][1]["defaults"].update(x=32, y=84)
        scene["objects"][3]["defaults"]["y"] = 80
        scene["objects"][4]["defaults"]["y"] = 80
        for index, text in ((6, "l"), (7, "r")):
            scene["objects"][index]["defaults"].update(y=60, visual_ref=f"exit_label_{text}.0")
        scene["objects"].append({"object_id": "scene_label", "kind": "sprite",
            "width": 46, "height": 14, "z_order": 5, "layer": "SCENE",
            "defaults": {"x": 61, "y": 4, "visible": True,
                         "visual_ref": "exit_label_" + label.lower() + ".0"}})
        scene["input_actions"] = [{"action_id": name, "logical_source": button, "event_kind": "press"}
            for name, button in (("go_away", "BUTTON_A"), ("go_home", "BUTTON_B"),
                                 ("left", "BUTTON_L"), ("right", "BUTTON_R"))
            if name != ("go_home" if scene_id == "home" else "go_away")]
        scene["routes"] = [{"route_id": name, "action_ref": name, "from_states": [source],
            "guards": [], "actions": [{"kind": "set_variable", "variable_ref": "moves",
                                         "operation": "add", "value": 1}], "target_state": target}
            for name, source, target in (("left", "marker_right", "start"),
                                         ("right", "start", "marker_right"))]
        scene["routes"].append({"route_id": "leave", "action_ref": "go_away" if scene_id == "home" else "go_home",
            "from_states": ["start", "marker_right"], "guards": [], "actions": [],
            "target_scene": "visit" if scene_id == "home" else "home"})
        scene["event_bindings"] = [{"binding_id": "scene_delay", "event_type": "time.scene_elapsed",
            "configuration": {"delay_ms": delay, "start_policy": "scene_entry"}}]
        handler = {"handler_id": "scene_delay_handler", "event_ref": "scene_delay", "guards": [], "actions": []}
        if scene_id == "home":
            handler["actions"] = [{"kind": "object.set_visibility", "object_ref": "timer_marker", "visible": True}]
        else:
            handler["target_scene"] = "home"
        scene["event_handlers"] = [handler]
        inputs = [action["action_id"] for action in scene["input_actions"]]
        scene["interaction_policy"]["meaningful_activity_actions"] = inputs
        scene["reactive_wait_default"]["event_interests"] = inputs + ["scene_delay"]
        scenes.append(scene)
    project = deepcopy(bundle.project)
    project.update(entry_scene="home", scene_sources=["scenes/home.state.json", "scenes/visit.state.json"])
    project["package"]["package_id"] = "dev.peepshow.fresh_scene_exit"
    return replace(bundle, project=project, scenes=tuple(scenes), frames=tuple(frames), assets=assets)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, default=DEFAULT_PROJECT,
                        help="Native V2 project; defaults to the checked-in Studio continuity fixture")
    parser.add_argument("--timers", action="store_true",
                        help="Use the OS timer variant of the checked-in Studio fixture (source stays unchanged)")
    parser.add_argument("--sfx", action="store_true",
                        help="Use the OS four-frame/audio variant (GUI sources stay unchanged)")
    parser.add_argument("--structured", action="store_true",
                        help="Use labelled B/A slots and a fixed timer slot (GUI source stays unchanged)")
    parser.add_argument("--dual", action="store_true",
                        help="Use structured slots with independent 400 ms / 800 ms animations")
    parser.add_argument("--scene-exits", action="store_true",
                        help="Use development-only HOME/AWAY fresh scene replacement with input and timer exits")
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[2] /
                        "firmware/peepshow_hw6_fw0/Core/Src/ps_object_development_egg_autogen.c")
    parser.add_argument("--egg-output", type=Path,
                        help="Write a development egg instead of changing the linked C fixture; normal export stays disabled")
    args = parser.parse_args()
    if any((args.timers, args.sfx, args.structured, args.dual, args.scene_exits)) and args.project.resolve() != DEFAULT_PROJECT.resolve():
        parser.error("fixture variants use checked-in sources; omit --project")
    if sum((args.timers, args.sfx, args.structured, args.dual, args.scene_exits)) > 1:
        parser.error("choose one fixture variant")
    bundle = (scene_exit_fixture_bundle() if args.scene_exits else dual_fixture_bundle() if args.dual else structured_fixture_bundle() if args.structured else sfx_fixture_bundle() if args.sfx
              else timer_fixture_bundle() if args.timers else load_project(args.project))
    blob = build_development_egg_v2(bundle)
    if args.egg_output is not None:
        args.egg_output.parent.mkdir(parents=True, exist_ok=True)
        args.egg_output.write_bytes(blob)
        print(f"Development-only V2 egg: {len(blob)} bytes -> {args.egg_output}")
        return
    args.output.write_text(render_c(blob), encoding="ascii", newline="\n")
    print(f"Development-only V2 egg: {len(blob)} bytes -> {args.output}")


if __name__ == "__main__":
    main()
