/* TMAG5273.h
 *
 * Public interface + register/bit definitions for the TMAG5273 driver.
 * - STM32 HAL I2C memory transactions are used in the .c file.
 * - This header intentionally includes only the subset of registers/fields used.
 */

#ifndef TMAG5273_H
#define TMAG5273_H

#include "stm32u5xx_hal.h"
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" {
#endif

//==============================================================================
// I2C address & handle
//==============================================================================
//
// Address notes:
// - TMAG5273_I2C_ADDR_7B is the 7-bit device address
// - TMAG5273_I2C_ADDR_8B is the HAL "8-bit" address (7-bit << 1)
//

#ifndef TMAG5273_I2C_ADDR_7B
#define TMAG5273_I2C_ADDR_7B   (0x78u)
#endif

#ifndef TMAG5273_I2C_ADDR_8B
#define TMAG5273_I2C_ADDR_8B   (TMAG5273_I2C_ADDR_7B << 1)
#endif

// Project must define this (typically generated by CubeMX).
// This driver uses I2C3, as in the original code.
extern I2C_HandleTypeDef hi2c3;

//==============================================================================
// Registers (subset used)
//==============================================================================

#define TMAG5273_REG_DEVICE_CONFIG_1      0x00u
#define TMAG5273_REG_DEVICE_CONFIG_2      0x01u
#define TMAG5273_REG_SENSOR_CONFIG_1      0x02u
#define TMAG5273_REG_SENSOR_CONFIG_2      0x03u
#define TMAG5273_REG_X_THR_CONFIG         0x04u
#define TMAG5273_REG_Y_THR_CONFIG         0x05u
#define TMAG5273_REG_Z_THR_CONFIG         0x06u
#define TMAG5273_REG_T_CONFIG             0x07u
#define TMAG5273_REG_INT_CONFIG_1         0x08u

#define TMAG5273_REG_I2C_ADDRESS          0x0Cu
#define TMAG5273_REG_DEVICE_ID            0x0Du
#define TMAG5273_REG_MANUFACTURER_ID_LSB  0x0Eu
#define TMAG5273_REG_MANUFACTURER_ID_MSB  0x0Fu

#define TMAG5273_REG_T_MSB_RESULT         0x10u
#define TMAG5273_REG_T_LSB_RESULT         0x11u
#define TMAG5273_REG_X_MSB_RESULT         0x12u
#define TMAG5273_REG_X_LSB_RESULT         0x13u
#define TMAG5273_REG_Y_MSB_RESULT         0x14u
#define TMAG5273_REG_Y_LSB_RESULT         0x15u
#define TMAG5273_REG_Z_MSB_RESULT         0x16u
#define TMAG5273_REG_Z_LSB_RESULT         0x17u

#define TMAG5273_REG_CONV_STATUS          0x18u
#define TMAG5273_REG_DEVICE_STATUS        0x1Cu

//==============================================================================
// Bit fields (positions only; widths are in the .c helper calls)
//==============================================================================

// DEVICE_CONFIG_2
#define TMAG5273_DEVICE_CONFIG_2_OPERATING_Pos   0u  // [1:0]

// SENSOR_CONFIG_1
#define TMAG5273_SENSOR_CONFIG_1_MAG_CH_EN_Pos   4u  // [7:4]
#define TMAG5273_SENSOR_CONFIG_1_SLEEPTIME_Pos   0u  // [3:0]

// SENSOR_CONFIG_2
#define TMAG5273_SENSOR_CONFIG_2_XY_RANGE_Pos    1u
#define TMAG5273_SENSOR_CONFIG_2_Z_RANGE_Pos     0u

// T_CONFIG
#define TMAG5273_T_CONFIG_T_CH_EN_Pos            0u

// INT_CONFIG_1
#define TMAG5273_INT_CONFIG_1_RSLT_INT_Pos       7u
#define TMAG5273_INT_CONFIG_1_THRSLD_INT_Pos     6u
#define TMAG5273_INT_CONFIG_1_INT_STATE_Pos      5u  // 0=latched, 1=pulse 10us
#define TMAG5273_INT_CONFIG_1_INT_MODE_Pos       2u  // [4:2]
#define TMAG5273_INT_CONFIG_1_MASK_INTB_Pos      0u  // 1=mask

//==============================================================================
// Enums / masks
//==============================================================================

/**
 * @brief Operating modes for DEVICE_CONFIG_2.OPERATING field.
 */
typedef enum {
    TMAG5273_MODE_STANDBY_TRIGGER = 0,
    TMAG5273_MODE_LOW_POWER       = 1,
    TMAG5273_MODE_CONTINUOUS      = 2,
    TMAG5273_MODE_WAKE_SLEEP      = 3
} TMAG5273_mode_t;

/**
 * @brief MAG_CH_EN field values (bits [7:4]) used by TMAG5273_set_magnetic_channels().
 *
 * NOTE: Driver currently masks to 3 bits in .c (ch & 0x7), preserved from original code.
 */
#define TMAG5273_CH_NONE 0x0u
#define TMAG5273_CH_X    0x1u
#define TMAG5273_CH_Y    0x2u
#define TMAG5273_CH_XY   0x3u
#define TMAG5273_CH_Z    0x4u
#define TMAG5273_CH_XZ   0x5u
#define TMAG5273_CH_YZ   0x6u
#define TMAG5273_CH_XYZ  0x7u

/**
 * @brief Range selector values used by TMAG5273_set_xy_range()/TMAG5273_set_z_range().
 */
#define TMAG5273_RANGE_40mT 0u
#define TMAG5273_RANGE_80mT 1u

/**
 * @brief Interrupt mode values for INT_CONFIG_1.INT_MODE field.
 */
typedef enum {
    TMAG5273_INT_MODE_NONE                = 0,
    TMAG5273_INT_MODE_INT                 = 1,
    TMAG5273_INT_MODE_INT_EXCEPT_I2C_BUSY = 2,
    TMAG5273_INT_MODE_SCL                 = 3,
    TMAG5273_INT_MODE_SCL_EXCEPT_I2C_BUSY = 4
} TMAG5273_int_mode_t;

//==============================================================================
// Base driver API
//==============================================================================

/**
 * @brief Convenience init: XYZ + Temp, continuous, ±80 mT.
 */
int TMAG5273_init_default(void);

int TMAG5273_set_operating_mode(TMAG5273_mode_t mode);
int TMAG5273_set_magnetic_channels(uint8_t ch_mask_3bit);

int TMAG5273_set_xy_range(uint8_t range40or80);
int TMAG5273_set_z_range(uint8_t range40or80);

int TMAG5273_set_sleep_time_n(uint8_t n);  // SLEEPTIME field [3:0]

int TMAG5273_read_raw(int16_t* x, int16_t* y, int16_t* z);
int TMAG5273_read_mT(float* x, float* y, float* z);
int TMAG5273_get_temp_raw(int16_t* t_raw);

uint8_t  TMAG5273_get_device_id(void);
uint16_t TMAG5273_get_manufacturer_id(void);
uint8_t  TMAG5273_get_device_status(void); // also useful to clear latched INT (device-dependent)

// Low-level register access
int TMAG5273_write_reg(uint8_t reg, uint8_t val);
int TMAG5273_read_reg(uint8_t reg, uint8_t* val);
int TMAG5273_read_regs(uint8_t reg, uint8_t* buf, uint16_t len);

//==============================================================================
// Interrupts & thresholds
//==============================================================================

/**
 * @brief Generic INT configuration (INTB pin behavior).
 */
int TMAG5273_config_int(bool result_int,
                        bool threshold_int,
                        bool pulse_10us,
                        TMAG5273_int_mode_t mode,
                        bool mask_intb);

// Convenience wrappers (inline)
static inline int TMAG5273_int_result_pulse(void)
{
    return TMAG5273_config_int(true, false, true, TMAG5273_INT_MODE_INT, false);
}

static inline int TMAG5273_int_result_latched(void)
{
    return TMAG5273_config_int(true, false, false, TMAG5273_INT_MODE_INT, false);
}

static inline int TMAG5273_int_threshold_latched(void)
{
    return TMAG5273_config_int(false, true, false, TMAG5273_INT_MODE_INT, false);
}

// Axis thresholds (mT -> internal code handled in .c)
int TMAG5273_set_x_threshold_mT(float mT);
int TMAG5273_set_y_threshold_mT(float mT);
int TMAG5273_set_z_threshold_mT(float mT);

#ifdef __cplusplus
}
#endif

#endif /* TMAG5273_H */
