// Auto-generated by tools/gen_game_package_manifest.py. Do not edit manually.
#ifndef UI_PAGE_REGISTRY_AUTOGEN_H
#define UI_PAGE_REGISTRY_AUTOGEN_H

#include "ui/ui_page_registry.h"
#include "ui/ui_page_native.h"
#include "ui/ui_menu_tree.h"

#define UI_PAGE_REGISTRY_ENTRY_COUNT (5u)

static const ui_page_registry_entry_t g_ui_page_registry_entries[UI_PAGE_REGISTRY_ENTRY_COUNT] = {
  { 1u, UI_PAGE_ROUTE_NATIVE_PAGE, &UI_PAGE_HOME_NATIVE, 0u, (const ui_menu_t *)0 },
  { 2u, UI_PAGE_ROUTE_NATIVE_PAGE, &UI_PAGE_PET_NATIVE, 0u, (const ui_menu_t *)0 },
  { 3u, UI_PAGE_ROUTE_NATIVE_TREE, (const ui_page_t *)0, UI_TREE_ID_SYSTEM_ROOT, &UI_MENU_SYSTEM },
  { 4u, UI_PAGE_ROUTE_NATIVE_TREE, (const ui_page_t *)0, UI_TREE_ID_PET_FEED, &UI_MENU_PET_FEED },
  { 5u, UI_PAGE_ROUTE_NATIVE_PAGE, &UI_PAGE_JOY_TARGET_NATIVE, 0u, (const ui_menu_t *)0 },
};

#endif /* UI_PAGE_REGISTRY_AUTOGEN_H */
