// Auto-generated by tools/build_game_maps.py. Do not edit manually.
#ifndef GAME_MAP_REGISTRY_AUTOGEN_H
#define GAME_MAP_REGISTRY_AUTOGEN_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct
{
  uint32_t target_map_hash;
  uint32_t scene_map_id;
  uint32_t scene_tileset_id;
  uint32_t slot_index;
} game_map_registry_entry_t;

#define GAME_MAP_REGISTRY_ENTRY_COUNT (4u)

static const game_map_registry_entry_t g_game_map_registry_entries[GAME_MAP_REGISTRY_ENTRY_COUNT] = {
  { 0x30E55CADu, 1001u, 2001u, 0u }, /* pet_house */
  { 0x95C6D168u, 1002u, 2002u, 1u }, /* town_map */
  { 0xB5F82E71u, 1003u, 2003u, 2u }, /* market */
  { 0x3E4ECD77u, 1004u, 2004u, 3u }, /* outdoor */
};

#ifdef __cplusplus
}
#endif

#endif /* GAME_MAP_REGISTRY_AUTOGEN_H */
